echo "check bad symlink in /bin ......"
grep -rnH --binary-files=text "\!<symlink>" /bin | grep --binary-files=text ":1:\!<symlink>"
echo "check bad symlink in /etc ......"
grep -rnH --binary-files=text "\!<symlink>" /etc | grep --binary-files=text ":1:\!<symlink>"
echo "check bad symlink in /lib ......"
grep -rnH --binary-files=text "\!<symlink>" /lib | grep --binary-files=text ":1:\!<symlink>"
echo "check bad symlink in /var ......"
grep -rnH --binary-files=text "\!<symlink>" /var | grep --binary-files=text ":1:\!<symlink>"
echo "check bad symlink in /usr ......"
grep -rnH --binary-files=text "\!<symlink>" /usr | grep --binary-files=text ":1:\!<symlink>"
