.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"   Fri Apr  2 11:32:09 MET DST 1993
.\" and Andries Brouwer (aeb@cwi.nl), Fri Feb 14 21:47:50 1997.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Sun Jul 25 10:45:30 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Jul 21 21:25:26 1996 by Andries Brouwer (aeb@cwi.nl)
.\" Modified Mon Oct 21 17:47:19 1996 by Eric S. Raymond (esr@thyrsus.com)
.\" Modified Wed Aug 27 20:28:58 1997 by Nicolas Lichtmaier (nick@debian.org)
.\" Modified Mon Sep 21 00:00:26 1998 by Andries Brouwer (aeb@cwi.nl)
.\" Modified Wed Jan 24 06:37:24 2001 by Eric S. Raymond (esr@thyrsus.com)
.\" Modified Thu Dec 13 23:53:27 2001 by Martin Schulze <joey@infodrom.org>
.\"
.\" nakano 注: Nicolas さんの a はオリジナルでは \'a だが,
.\" キャラクタを壊すので a に変更した.
.\"
.\" Japanese Version Copyright (c) 1997 KURODA Masaru all rights reserved.
.\" Translated May 27, 1997 by KURODA Masaru <kuro@st.rim.or.jp>
.\" Modified Sat 25 Jul 1998 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Modified Sun 6 Dec 1998 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Sat Aug 21 1999
.\"       by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Sat 18 Mar 2000 by NAKANO Takeo
.\" Updated Sat Dec 22 JST 2001 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Sat Mar 23 JST 2002 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated 2010-04-11, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v3.24
.\"
.\"WORD:	environment		環境
.\"WORD:	environment variable	環境変数
.\"WORD:	shell variable		シェル変数
.\"WORD:	locale			ロケール
.\"WORD:	locale category		ロケールカテゴリ
.\"
.TH ENVIRON 7 2009-07-25 "Linux" "Linux Programmer's Manual"
.SH 名前
environ \- ユーザ環境
.SH 書式
.nf
.BI "extern char **" environ ;
.br
.fi
.SH 説明
変数
.I environ
は「環境 (environment)」と呼ばれる文字列へのポインタの配列である。
この配列の最後のポインタの値は NULL である。
(この変数はユーザープログラムで宣言しなければならない。
ただし libc4 や libc5 のヘッダーファイルなら
.I <unistd.h>
で宣言されているし、これが glibc 由来のものでも
.B _GNU_SOURCE
が define されていれば宣言済みとなる)。
この文字列配列は、
プロセスを起動する
.BR exec (3)
によって、その起動されたプロセスで利用できるようになる。

通例では、
.I environ
の文字列は "\fIname\fP\fB=\fP\fIvalue\fP" という書式をとる。
よく用いられる例を以下に示す。
.TP
.B USER
ユーザのログイン名 (BSD 起源のプログラムなどによって使用される)。
.TP
.B LOGNAME
ユーザのログイン名(System V 起源のプログラムなどによって使用される)。
.TP
.B HOME
ユーザのログインディレクトリ。
.BR login (1)
がパスワードファイル
.BR passwd (5)
から取得して設定する。
.TP
.B LANG
ロケールの各カテゴリで使用されるロケールの名前。\fBLC_ALL\fP や、
より狭い範囲を対象とする環境変数
.RB ( LC_COLLATE ,
.BR LC_CTYPE ,
.BR LC_MESSAGES ,
.BR LC_MONETARY ,
.BR LC_NUMERIC ,
.B LC_TIME
など)
によって上書きされることもある。
.BR locale (5)
を見よ。
.TP
.B PATH
.BR sh (1)
や他のプログラムが、フルパスで与えられなかった実行ファイルを検索するとき、
ファイル名に前置されるディレクトリの配列。
各ディレクトリは \(aq\fB:\fP\(aq によって区切られる。
(同じようなものに、
シェルがディレクトリ変更コマンドの変更先を探すために用いる
\fBCDPATH\fP や、
.BR man (1)
がマニュアルページの検索に用いる \fBMANPATH\fP などがある。)
.TP
.B PWD
現在のワーキングディレクトリ。いくつかのシェルが設定する。
.TP
.B SHELL
ユーザーのログインシェルのパス名。
.TP
.B TERM
端末の種類。出力はこれにあわせて用意される。
.TP
.B PAGER
テキストファイルを表示するユーテリティ。ユーザーが好みのものを設定する。
.TP
.BR EDITOR / VISUAL
テキストファイルを編集するユーテリティ。ユーザーが好みのものを設定する。
.\" .TP
.\" .B BROWSER
.\" URL の閲覧に用いるユーティリティ。ユーザーが好みのものを設定する。
.\" コロンで区切ってブラウザコマンドを並べる。
.\" http://www.catb.org/~esr/BROWSER/ を見よ。
.PP
環境に名前を追加する場合には、
.BR sh (1)
では \fIexport\fP コマンドと "name=value" を使用する。
.BR csh (1)
では \fIsetenv\fP コマンドを使用する。
.BR exec (3)
の引数としても環境を設定することができる。
C プログラムからは、
.BR getenv (3),
.BR putenv (3),
.BR setenv (3),
.BR unsetenv (3)
などの関数を用いて環境を扱うことができる。

プログラムやライブラリルーチンの多くは、それぞれ適当な環境変数の存在
や値によって、動作に影響を受けることがある。以下、適宜挙げてみよう。
.LP
.BR LANG ", " LANGUAGE ", " NLSPATH ", " LOCPATH ", "
.BR LC_ALL ", " LC_MESSAGES ", "
などの変数。ロケールの扱いに影響する。
.BR locale (5)
を見よ。
.LP
.B TMPDIR
は
.BR tmpnam (3)
などのルーチンによって作成されるファイル名に前置されるパスに影響する。また
.BR sort (1)
の一時ディレクトリに用いられたり、他のプログラムからも利用される。
.LP
.BR LD_LIBRARY_PATH ", " LD_PRELOAD
などの LD_* 変数はダイナミックローダ・リンカの動作に影響する。
.LP
.B POSIXLY_CORRECT
が指定されると、ある種のプログラムやライブラリルーチンは
POSIX の規定に従うようになる。
.LP
.BR malloc (3)
の動作は
.B MALLOC_*
変数によって影響される。
.LP
.B HOSTALIAS
変数は、
.BR gethostbyname (3)
が用いるエイリアスが書かれているファイル名を与える。
.LP
.BR TZ " と " TZDIR
は
.BR tzset (3)
および、この関数を使う
.BR ctime (3),
.BR localtime (3),
.BR mktime (3),
.BR strftime (3)
といった関数で用いられるタイムゾーンの情報を与える。
.BR tzselect (8)
も参照のこと。
.LP
.B TERMCAP
は、現在の端末情報の取得先
(あるいはそのような情報が書かれているファイル名) を与える。
.LP
.BR COLUMNS " と " LINES
アプリケーションにウインドウのサイズを伝える。
実際のサイズとは違う値を与えることもできる。
.LP
.BR PRINTER " または " LPDEST
用いたいプリンタを指定する。
.BR lpr (1)
を参照のこと。
.LP
などなど...
.SH バグ
これらの中には、明らかにセキュリティ上の危険が存在する。
ユーザーが
.BR IFS " や " LD_LIBRARY_PATH
に異常な値を与えたことによって、
これまで多くのシステムコマンドがだまされて、
システムをひどい目にあわせてきた。

名前空間が汚染される危険性も存在する。
.I make
や
.I autoconf
のようなプログラムでは、デフォルトのユーティリティを
環境にある似たような名前の変数で上書きすることができる
(通常はすべて大文字の変数を用いる)。
すなわち、利用したい C コンパイラは
.B CC
で選択できる。また同様に
.BR MAKE ,
.BR AR ,
.BR AS ,
.BR FC ,
.BR LD ,
.BR LEX ,
.BR RM ,
.B YACC
なども用いることができる。
ところが一方では、このような変数を
(パス名ではなく)
プログラムに対するオプションとして扱うような流儀も存在してきた。
例えば
.BR MORE ,
.BR LESS ,
.B GZIP
などがそうである。
このような利用法は間違っていると考えるべきで、
新しいプログラムでは避けるべきである。
.I gzip
の作者たちは、オプションを与える環境変数を
.B GZIP_OPT
に改名することを考えるほうがよい。
.SH 関連項目
.BR bash (1),
.BR csh (1),
.BR login (1),
.BR sh (1),
.BR tcsh (1),
.BR execve (2),
.BR clearenv (3),
.BR exec (3),
.BR getenv (3),
.BR putenv (3),
.BR setenv (3),
.BR unsetenv (3),
.BR locale (5)
