'\" t
.\" Copyright 1999      Dimitri Papadopoulos (dpo@club-internet.fr)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Japanese Version Copyright (c) 1999 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Thu Jan  6 01:46:08 JST 2000
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Updated Tue Sep  9 JST 2003 by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH ISO_8859-7 7 2008-10-30 "Linux" "Linux Programmer's Manual"
.nh
.SH 名前
iso_8859-7 \- ISO 8859-7 文字集合の 8進数、10進数、16進数による符号化
.SH 説明
ISO 8859 規格は ASCII 文字集合 (ISO 646-IRV とも呼ばれる) の
いくつかの 8 ビット拡張を含んでいる。ISO 8859-7 は現代の単調の
ギリシア語に使用される文字を符号化している。
.SS "ISO 8859 アルファベット"
完全な ISO 8859 アルファベットは以下のものを含んでいる:
.TS
l l.
ISO 8859-1	西ヨーロッパの言語 (Latin-1)
ISO 8859-2	中央・東ヨーロッパの言語 (Latin-2)
ISO 8859-3	東南ヨーロッパやその他の言語 (Latin-3)
ISO 8859-4	スカンジナビア/バルト語派の言語 (Latin-4)
ISO 8859-5	ラテン/キリル文字
ISO 8859-6	ラテン/アラビア文字
ISO 8859-7	ラテンギリシャ文字
ISO 8859-8	ラテン/ヘブライ語
ISO 8859-9	トルコ語修正を行なった Latin-1 (Latin-5)
ISO 8859-10	ラップ/ノルディック/エスキモーの言語 (Latin-6)
ISO 8859-11	ラテン/タイ語
ISO 8859-13	バルト諸国の言語 (Latin-7)
ISO 8859-14	ケルト語 (Latin-8)
ISO 8859-15	西ヨーロッパの言語 (Latin-9)
ISO 8859-16	ルーマニア語 (Latin-10)
.TE
.SS "ISO 8859-7 文字"

以下の表は ISO 8859-7 の表示可能な文字のうち
.BR ascii (7)
マニュアル・ページに載っていないものを示している。
4列目は ISO 8859-7 用に設定された環境でのみ正しく表示できるだろう。

[ 訳注  原文では Char の部分に ISO 8859-7 の文字があったが、
日本語 EUC との併用は難しいので削除し、JIS X 0208 の同じ文字を
示すようにした。その他の文字に関しては
英語版の iso_8859-7(7) を適切なフォントを準備して参照してほしい。 ]
.TS
l l l c lp-1.
Oct	Dec	Hex	Char	Description
_
240	160	A0		NO-BREAK SPACE
241	161	A1		LEFT SINGLE QUOTATION MARK
242	162	A2		RIGHT SINGLE QUOTATION MARK
243	163	A3	£	POUND SIGN
244	164	A4		EURO SIGN
245	165	A5		DRACHMA SIGN
246	166	A6		BROKEN BAR
247	167	A7	§	SECTION SIGN
250	168	A8	¨	DIAERESIS
251	169	A9		COPYRIGHT SIGN
252	170	AA		GREEK YPOGEGRAMMENI
253	171	AB	《	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
254	172	AC	¬	NOT SIGN
255	173	AD		SOFT HYPHEN
257	175	AF	—	HORIZONTAL BAR
260	176	B0	°	DEGREE SIGN
261	177	B1	±	PLUS-MINUS SIGN
262	178	B2		SUPERSCRIPT TWO
263	179	B3		SUPERSCRIPT THREE
264	180	B4		GREEK TONOS
265	181	B5		GREEK DIALYTIKA TONOS
266	182	B6		GREEK CAPITAL LETTER ALPHA WITH TONOS
267	183	B7	・	MIDDLE DOT
270	184	B8		GREEK CAPITAL LETTER EPSILON WITH TONOS
271	185	B9		GREEK CAPITAL LETTER ETA WITH TONOS
272	186	BA		GREEK CAPITAL LETTER IOTA WITH TONOS
273	187	BB	》	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
274	188	BC		GREEK CAPITAL LETTER OMICRON WITH TONOS
275	189	BD		VULGAR FRACTION ONE HALF
276	190	BE		GREEK CAPITAL LETTER UPSILON WITH TONOS
277	191	BF		GREEK CAPITAL LETTER OMEGA WITH TONOS
300	192	C0		GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
301	193	C1	Α	GREEK CAPITAL LETTER ALPHA
302	194	C2	Β	GREEK CAPITAL LETTER BETA
303	195	C3	Γ	GREEK CAPITAL LETTER GAMMA
304	196	C4	Δ	GREEK CAPITAL LETTER DELTA
305	197	C5	Ε	GREEK CAPITAL LETTER EPSILON
306	198	C6	Ζ	GREEK CAPITAL LETTER ZETA
307	199	C7	Η	GREEK CAPITAL LETTER ETA
310	200	C8	Θ	GREEK CAPITAL LETTER THETA
311	201	C9	Ι	GREEK CAPITAL LETTER IOTA
312	202	CA	Κ	GREEK CAPITAL LETTER KAPPA
313	203	CB	Λ	GREEK CAPITAL LETTER LAMBDA
314	204	CC	Μ	GREEK CAPITAL LETTER MU
315	205	CD	Ν	GREEK CAPITAL LETTER NU
316	206	CE	Ξ	GREEK CAPITAL LETTER XI
317	207	CF	Ο	GREEK CAPITAL LETTER OMICRON
320	208	D0	Π	GREEK CAPITAL LETTER PI
321	209	D1	Ρ	GREEK CAPITAL LETTER RHO
323	211	D3	Σ	GREEK CAPITAL LETTER SIGMA
324	212	D4	Τ	GREEK CAPITAL LETTER TAU
325	213	D5	Υ	GREEK CAPITAL LETTER UPSILON
326	214	D6	Φ	GREEK CAPITAL LETTER PHI
327	215	D7	Χ	GREEK CAPITAL LETTER CHI
330	216	D8	Ψ	GREEK CAPITAL LETTER PSI
331	217	D9	Ω	GREEK CAPITAL LETTER OMEGA
332	218	DA		GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
333	219	DB		GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
334	220	DC		GREEK SMALL LETTER ALPHA WITH TONOS
335	221	DD		GREEK SMALL LETTER EPSILON WITH TONOS
336	222	DE		GREEK SMALL LETTER ETA WITH TONOS
337	223	DF		GREEK SMALL LETTER IOTA WITH TONOS
340	224	E0		GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
341	225	E1	α	GREEK SMALL LETTER ALPHA
342	226	E2	β	GREEK SMALL LETTER BETA
343	227	E3	γ	GREEK SMALL LETTER GAMMA
344	228	E4	δ	GREEK SMALL LETTER DELTA
345	229	E5	ε	GREEK SMALL LETTER EPSILON
346	230	E6	ζ	GREEK SMALL LETTER ZETA
347	231	E7	η	GREEK SMALL LETTER ETA
350	232	E8	θ	GREEK SMALL LETTER THETA
351	233	E9	ι	GREEK SMALL LETTER IOTA
352	234	EA	κ	GREEK SMALL LETTER KAPPA
353	235	EB	λ	GREEK SMALL LETTER LAMBDA
354	236	EC	μ	GREEK SMALL LETTER MU
355	237	ED	ν	GREEK SMALL LETTER NU
356	238	EE	ξ	GREEK SMALL LETTER XI
357	239	EF	ο	GREEK SMALL LETTER OMICRON
360	240	F0	π	GREEK SMALL LETTER PI
361	241	F1	ρ	GREEK SMALL LETTER RHO
362	242	F2		GREEK SMALL LETTER FINAL SIGMA
363	243	F3	σ	GREEK SMALL LETTER SIGMA
364	244	F4	τ	GREEK SMALL LETTER TAU
365	245	F5	υ	GREEK SMALL LETTER UPSILON
366	246	F6	φ	GREEK SMALL LETTER PHI
367	247	F7	χ	GREEK SMALL LETTER CHI
370	248	F8	ψ	GREEK SMALL LETTER PSI
371	249	F9	ω	GREEK SMALL LETTER OMEGA
372	250	FA		GREEK SMALL LETTER IOTA WITH DIALYTIKA
373	251	FB		GREEK SMALL LETTER UPSILON WITH DIALYTIKA
374	252	FC		GREEK SMALL LETTER OMICRON WITH TONOS
375	253	FD		GREEK SMALL LETTER UPSILON WITH TONOS
376	254	FE		GREEK SMALL LETTER OMEGA WITH TONOS
.TE
.SH 備考
ISO 8859-7 は以前は ELOT-928 とか ECMA-118:1986 と呼ばれていた。
.SH 関連項目
.BR ascii (7)
