.\" Copyright (C) 2001 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Text fragments inspired by Martin Schulze <joey@infodrom.org>.
.\"
.\" Japanese Version Copyright (c) 2002 NAKANO Takeo all rights reserved.
.\" Translated Mon 14 Jan 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH ASPRINTF 3 2001-12-18 "GNU" "Linux Programmer's Manual"
.SH 名前
asprintf, vasprintf \- 文字列を割り当ててそれに出力する
.SH 書式
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.br
.B #include <stdio.h>
.sp
.BI "int asprintf(char **" strp ", const char *" fmt ", ...);"
.sp
.BI "int vasprintf(char **" strp ", const char *" fmt ", va_list " ap );
.SH 説明
.BR asprintf ()
関数と
.BR vasprintf ()
関数とは、それぞれ
.BR sprintf (3)
関数と
.BR vsprintf (3)
関数とに似ているが、
出力文字列を (終端の NULL バイトも含めて)
保持するのに十分な大きさのメモリを確保し、
最初の引数にその文字列へのポインタを返す。
このポインタは、不要になったら
.BR free (3)
に渡し、割り当てられた記憶領域を解放すべきである。
.SH 返り値
成功すると、これらの関数は出力されたバイト数を
.RB ( sprintf (3)
のように) 返す。
メモリの割り当てができなかったり、
その他エラーが生じると、
これらの関数は \-1 を返し、
.I strp
の内容は未定義となる。
.SH 準拠
これらの関数は GNU の拡張であり、C や POSIX のものではない。
これらは *BSD でも利用できる。
FreeBSD の実装では、エラーの際には
.I strp
を NULL にセットする。
.SH 関連項目
.BR free (3),
.BR malloc (3),
.BR printf (3)
