.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Thu Jul 24 00:07:40 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	arc sine	逆正弦
.\"WORD:	arc cosine	逆余弦
.\"WORD:	arc tangent	逆正接
.\"WORD:	real part	実部
.\"WORD:	imaginary part	虚部
.\"
.TH CASIN 3 2008-08-06 "" "Linux Programmer's Manual"
.SH 名前
casin, casinf, casinl \- 複素数の逆正弦 (arc sine)
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex casin(double complex " z );
.br
.BI "float complex casinf(float complex " z );
.br
.BI "long double complex casinl(long double complex " z );
.sp
\fI\-lm\fP でリンクする。
.SH 説明
.BR casin ()
関数は複素数
.I z
の逆正弦 (arg sine) を計算する。
\fIy\ =\ casin(z)\fP ならば、 \fIz\ =\ csin(y)\fP が成立する。
.I y
の実部の値は区間 [\-pi/2,pi/2] から選択される。
.LP
次の関係が成立する:
.nf

    casin(z) = \-i clog(iz + csqrt(1 \- z * z))
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR clog (3),
.BR csin (3),
.BR complex (7)
