.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" and Copyright (C) 2011 Michael Kerrisk <mtk.manpages@gamil.com>
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Thu Jul 24 00:43:35 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	hyperbolic	双曲(線の)
.\"WORD:	arc sine	逆正弦
.\"WORD:	arc cosine	逆余弦
.\"WORD:	arc tangent	逆正接
.\"WORD:	real part	実部
.\"WORD:	imaginary part	虚部
.\"
.TH CATANH 3 2011-09-15 "" "Linux Programmer's Manual"
.SH 名前
catanh, catanhf, catanhl \- 複素数の逆双曲線正接 (arc tangents hyperbolic)
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex catanh(double complex " z );
.br
.BI "float complex catanhf(float complex " z );
.br
.BI "long double complex catanhl(long double complex " z );
.sp
\fI\-lm\fP でリンクする。
.SH 説明
.BR catanh ()
関数は複素数
.I z
の逆双曲線正弦 (arc hyperbolic tangent) を計算する。
\fIy = catanh(z)\fP ならば、 \fIz = ctanh(y)\fP が成立する。
.I y
の虚部の値は区間 [\-pi/2,pi/2] から選択される。
.LP
次の関係が成立する:
.nf

    catanh(z) = 0.5 * (clog(1 + z) \- clog(1 \- z))
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 例
.nf
/* Link with "\-lm" */

#include <complex.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

int
main(int argc, char *argv[])
{
    double complex z, c, f;

    if (argc != 3) {
        fprintf(stderr, "Usage: %s <real> <imag>\\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    z = atof(argv[1]) + atof(argv[2]) * I;

    c = catanh(z);
    printf("catanh() = %6.3f %6.3f*i\\n", creal(c), cimag(c));

    f = 0.5 * (clog(1 + z) \- clog(1 \- z));
    printf("formula  = %6.3f %6.3f*i\\n", creal(f2), cimag(f2));

    exit(EXIT_SUCCESS);
}
.fi
.SH 関連項目
.BR atanh (3),
.BR cabs (3),
.BR cimag (3),
.BR ctanh (3),
.BR complex (7)
