.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Wed Jul 23 05:24:15 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	sine		正弦
.\"WORD:	cosine		余弦
.\"WORD:	tangent		正接
.\"
.TH CCOS 3 2008-08-06 "" "Linux Programmer's Manual"
.SH 名前
ccos, ccosf, ccosl \- 複素数の余弦 (cosine)
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex ccos(double complex " z ");"
.br
.BI "float complex ccosf(float complex " z ");"
.br
.BI "long double complex ccosl(long double complex " z ");"
.sp
\fI\-lm\fP でリンクする。
.SH 説明
複素数の余弦 (cosine) 関数 ccos(z) は以下のように定義される。
.nf

    ccos(z) = (exp(i * z) + exp(\-i * z)) / 2
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR cabs (3),
.BR cacos (3),
.BR csin (3),
.BR ctan (3),
.BR complex (7)
