.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Thu Jul 24 02:05:20 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" 
.\"WORD:	exponential		指数
.\"WORD:	natural logarithm	自然対数
.\"WORD:	base			底
.\" 
.TH CEXP 3 2008-08-06 "" "Linux Programmer's Manual"
.SH 名前
cexp, cexpf, cexpl \- 複素数の指数関数
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex cexp(double complex " z ");"
.br
.BI "float complex cexpf(float complex " z ");"
.br
.BI "long double complex cexpl(long double complex " z ");"
.sp
\fI\-lm\fP でリンクする。
.SH 説明
この関数は e (2.71828..., 自然対数の底) の \fIz\fR 乗を計算する。
.LP
次の関係が成立する:
.nf

    cexp(I * z) = ccos(z) + I * csin(z)
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR cabs (3),
.BR cexp2 (3),
.BR clog (3),
.BR cpow (3),
.BR complex (7)
