.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2003-07-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-02-24, Akihiro MOTOKI
.\"
.\"WORD:	exponent	累乗
.\"
.TH CEXP2 3 2008-08-11 "" "Linux Programmer's Manual"
.SH 名前
cexp2, cexp2f, cexp2l \- 複素数の 2 の累乗
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex cexp2(double complex " z ");"
.br
.BI "float complex cexp2f(float complex " z ");"
.br
.BI "long double complex cexp2l(long double complex " z ");"
.sp
\fI\-lm\fP でリンクする。
.SH 説明
この関数は 2 の \fIz\fR 乗を返す。
.SH 準拠
関数名は C99 で今後使用するために予約されている。
.SH 可用性
バージョン 2.8 時点では、glibc にはまだ実装されていない。
.\" しかし、名前空間は予約済である。
.SH 関連項目
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3),
.BR complex (7)
