.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Thu Jul 24 01:47:42 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	natural logarithm	自然対数
.\"WORD:	logarithm		対数
.\"WORD:	exponential		指数
.\"WORD:	inverse function	逆関数
.\"
.TH CLOG 3 2008-08-11 "" "Linux Programmer's Manual"
.SH 名前
clog, clogf, clogl \- 複素数の自然対数
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex clog(double complex " z );
.br
.BI "float complex clogf(float complex " z );
.br
.BI "long double complex clogl(long double complex " z );
.sp
\fI\-lm\fP でリンクする。
.SH 説明
対数
.BR clog ()
は指数関数
.BR cexp ()
の逆関数である。
したがって、 \fIy = clog(z)\fP ならば、 \fIz = cexp(y)\fP が成立する。
.I y
の虚数部の値は区間 [\-pi,pi] から選択される。
.LP
次の関係が成立する:
.nf

    clog(z) = log(cabs(z)) + I * carg(z)
.fi
.LP
.I z
として 0 に近い値を入れると、オーバーフローを起こすため、
注意が必要である。
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3),
.BR clog2 (3),
.BR complex (7)
