.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2003-07-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-02-26, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2007-01-05, Akihiro MOTOKI, catch up to LDP v2.43
.\"
.\"WORD:	logarithm	対数
.\"WORD:	base		底
.\"
.TH CLOG10 3 2008-08-11 "" "Linux Programmer's Manual"
.SH 名前
clog10, clog10f, clog10l \- 底が 10 の複素数の対数
.SH 書式
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.br
.B #include <complex.h>
.sp
.BI "double complex clog10(double complex " z );
.br
.BI "float complex clog10f(float complex " z );
.br
.BI "long double complex clog10l(long double complex " z );
.sp
\fI\-lm\fP でリンクする。
.SH 説明
.I clog10(z)
の呼び出しは
.I clog(z)/log(10)
と等価である。
他の関数は同じ機能を持つ
.I float
版と
.I "long double"
版である。

.I z
として 0 に近い値を入れると、オーバーフローを起こすため、
注意が必要である。
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
この関数は GNU による拡張である。
C99 では今後のために予約されている。
.SH 関連項目
.BR cabs (3),
.BR cexp (3),
.BR clog (3),
.BR clog2 (3),
.BR complex (7)
