.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Thu Jul 24 02:38:18 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	complex conjugate	複素共役
.\"WORD:	imaginary part		虚部
.\"
.TH CONJ 3 2008-08-11 "" "Linux Programmer's Manual"
.SH 名前
conj, conjf, conjl \- 複素共役を計算する
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex conj(double complex " z );
.br
.BI "float complex conjf(float complex " z );
.br
.BI "long double complex conjl(long double complex " z );
.sp
\fI\-lm\fP でリンクする。
.SH 説明
.BR conj ()
関数は \fIz\fR の複素共役を返す。
その値は虚部の符号を反転して得られる。
.LP
次の関係が成立する:
.nf

    cabs(z) = csqrt(z * conj(z))
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR cabs (3),
.BR csqrt (3),
.BR complex (7)
