.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2003-07-23, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-02-21, Akihiro MOTOKI
.\" 
.\"WORD:	hyperbolic	双曲(線の)
.\"WORD:	sine		正弦
.\"WORD:	cosine		余弦
.\"WORD:	tangent		正接
.\" 
.TH CTANH 3 2008-08-11 "" "Linux Programmer's Manual"
.SH 名前
ctanh, ctanhf, ctanhl \- 複素数の双曲線正接 (hyperbolic tangent)
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex ctanh(double complex " z ");"
.br
.BI "float complex ctanhf(float complex " z );
.br
.BI "long double complex ctanhl(long double complex " z ");"
.sp
\fI\-lm\fP でリンクする。
.SH 説明
複素数の双曲線正接 (hyperbolic tangent) 関数は以下のように定義される。
.nf

    ctanh(z) = csinh(z) / ccosh(z)
.fi
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
C99.
.SH 関連項目
.BR cabs (3),
.BR catanh (3),
.BR ccosh (3),
.BR csinh (3),
.BR complex (7)
