.\"  Copyright 2001 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" aeb: some corrections
.\"
.\" Japanese Version Copyright (c) 2002 NAKANO Takeo all rights reserved.
.\" Translated Sun 6 Jan 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH DYSIZE 3 2010-09-22 "GNU" "Linux Programmer's Manual"
.SH 名前
dysize \- 与えた年の日数を返す
.SH 書式
.B "#include <time.h>"
.sp
.BI "int dysize(int " year );
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR dysize ():
_BSD_SOURCE || _SVID_SOURCE
.SH 説明
この関数は通常の年には 365 を返し、うるう年には 366 を返す。
うるう年の計算は次の式による:
.sp
(year) %4 == 0 && ((year) %100 != 0 || (year) %400 == 0)
.sp
この式は
.I __isleap(year)
マクロで定義されており、
.I <time.h>
にもある。
.SH 準拠
この関数は SunOS 4.x で生まれた。
.SH 注意
これは互換用の関数に過ぎない。新しいプログラムでは使わないこと。
.\" この関数の SCO 版には 2000 年問題が含まれていた。
.SH 関連項目
.BR strftime (3)
