.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\" and Copyright 2008, Linux Foundation, written by Michael Kerrisk
.\"     <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified 1993-07-24 by Rik Faith (faith@cs.unc.edu)
.\" Modified 1995-08-14 by Arnt Gulbrandsen <agulbra@troll.no>
.\" Modified 2002-07-27 by Walter Harms
.\" 	(walter.harms@informatik.uni-oldenburg.de)
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Tue Sep 23 20:30:22 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH EXP10 3  2008-08-11  "GNU" "Linux Programmer's Manual"
.SH 名前
exp10, exp10f, exp10l \- 基数が 10 の指数関数
.SH 書式
.nf
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.br
.B #include <math.h>
.sp
.BI "double exp10(double " x );
.br
.BI "float exp10f(float " x );
.br
.BI "long double exp10l(long double " x );
.fi
.sp
\fI\-lm\fP でリンクする。
.SH 説明
.BR exp10 ()
関数は 10 の \fIx\fP 乗の値を返す。
.SH 返り値
成功すると、これらの関数は 10 の
.I x
乗を返す。

無限大や NaN の扱いや、オーバーフローとアンダーフローなどの
さまざまな特別な状況については、
.BR exp (3)
を参照のこと。
.SH エラー
これらの関数を呼び出した際にエラーが発生したかの判定方法についての情報は
.BR math_error (7)
を参照のこと。

これらの関数で発生するエラーについては、
.BR exp (3)
を参照のこと。
.\" FIXME . exp10 doesn't give ERANGE for an underflow, unlike exp() and exp2()
.\" Bug raised: http://sources.redhat.com/bugzilla/show_bug.cgi?id=6787
.SH バージョン
これらの関数は glibc バージョン 2.1 で初めて登場した。
.SH 準拠
これらの関数は GNU による拡張である。
.SH 関連項目
.BR cbrt (3),
.BR exp (3),
.BR exp2 (3),
.BR log10 (3),
.BR sqrt (3)
