.\" Copyright (c) 2006 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\"
.\" Japanese Version Copyright (c) 2000 Yuichi SATO
.\"         all rights reserved.
.\" Translated 2000-06-24, Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\" Updated 2007-05-04, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v2.46
.\"
.\"WORD:	standard streams	標準入出力
.\"
.TH FCLOSEALL 3  2006-12-27 "GNU" "Linux Programmer's Manual"
.SH 名前
fcloseall \- 開いているすべてのストリームを閉じる
.SH 書式
.nf
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.B #include <stdio.h>
.sp
.B int fcloseall(void);
.fi
.SH 説明
.BR fcloseall ()
関数は、呼び出し元プロセスが開いているすべてのストリームを閉じる。
ストリームを閉じる前に、
.RB ( fflush (3)
と同じように) 各ストリームのバッファに溜っている出力データは書き出される。
入力バッファ内のデータは破棄される。

標準入出力
.IR stdin ,
.IR stdout ,
.I stderr
も閉じられる。
.SH 返り値
この関数は、すべてのファイルが正常に閉じられた場合 0 を返す。
エラーの場合、
.B EOF
を返す。
.SH 準拠
この関数は GNU 拡張である。
.SH 関連項目
.BR close (2),
.BR fclose (3),
.BR fflush (3),
.BR fopen (3),
.BR setbuf (3)
