.\" Copyright (C) 2002 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" This replaces an earlier man page written by Walter Harms
.\" <walter.harms@informatik.uni-oldenburg.de>.
.\"
.\" Japanese Version Copyright (c) 2002 Akihiro MOTOKI all rights reserved.
.\" Translated Thu 05 Dec 2002 by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH GETUMASK 3 2010-09-10 "GNU" "Linux Programmer's Manual"
.SH 名前
getumask \- ファイル作成マスクを取得する
.SH 書式
.nf
.BR "#define _GNU_SOURCE" "             /* feature_test_macros(7) 参照 */"
.br
.B "#include <sys/types.h>"
.br
.B "#include <sys/stat.h>"
.sp
.B "mode_t getumask(void);"
.fi
.SH 説明
この関数は現在のファイル作成マスクを返す。
基本的には以下と等価である。
.in +4n
.nf

mode_t getumask(void)
{
    mode_t mask = umask( 0 );
    umask(mask);
    return mask;
}

.fi
.in
ドキュメントによると、この関数は
スレッド・セーフである
.RB ( umask (2)
ライブラリ・コールとロックを共有する)
点が異なる。
.SH 準拠
ドキュメントに書いてあるだけの GNU 拡張である。
.SH 注意
バージョン 2.9 時点の glibc では、
この関数についての記載はあるが、まだ実装されていない。
.SH 関連項目
.BR umask (2)
