.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain. - aeb
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Tue Jul  8 01:56:27 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	pseudoterminal		擬似端末
.\"WORD:	pseudotty		擬似端末
.\"
.TH GRANTPT 3 2008-06-14 "GNU" "Linux Programmer's Manual"
.SH 名前
grantpt \- スレーブ擬似端末へのアクセスを許可する
.SH 書式
.nf
.BR "#define _XOPEN_SOURCE" "       /* feature_test_macros(7) 参照 */"
.br
.B #include <stdlib.h>
.sp
.BI "int grantpt(int " fd ");"
.fi
.SH 説明
.BR grantpt ()
関数は、
.I fd
で参照されたマスタ擬似端末に対応するスレーブ擬似端末デバイス
のモードと所有者を変更する。
スレーブのユーザID は呼び出したプロセスの実 UID に設定される。
グループID として設定される値は規定されていない (例えば \fItty\fP になる)。
スレーブのモードは 0620 (crw\-\-w\-\-\-\-) に設定される。
.PP
.B SIGCHLD
シグナルを捕捉するためにシグナル・ハンドラが設定されている場合の
.BR grantpt ()
の動作は規定されていない。
.SH 返り値
成功した場合、
.BR grantpt ()
は 0 を返す。そうでない場合、\-1 を返し、
.I errno
に適切な値がセットされる。
.SH エラー
.TP
.B EACCES
対応するスレーブ擬似端末にアクセスできなかった。
.TP
.B EBADF
引き数
.I fd
が有効なオープンされたファイル・ディスクリプタでない。
.TP
.B EINVAL
引き数
.I fd
は有効だが、マスタ擬似端末に対応するものではない。
.SH バージョン
.BR grantpt ()
は、バージョン 2.1 以降の glibc で提供されている。
.SH 準拠
POSIX.1-2001.
.SH 備考
これは UNIX 98 擬似端末 (pseudoterminal) 仕様の一部である。
.BR pts (4)
を参照のこと。
多くのシステムでは、この関数は "pt_chown" と呼ばれる set-user-ID された
補助バイナリを用いて実装されている。
Linux の devpts では、このような補助バイナリを必要としない。
.SH 関連項目
.BR open (2),
.BR posix_openpt (3),
.BR ptsname (3),
.BR unlockpt (3),
.BR pts (4),
.BR pty (7)
