.\" Copyright 2004 Andries Brouwer <aeb@cwi.nl>.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Japanese Version Copyright (c) 2005 Yuichi SATO
.\"         all rights reserved.
.\" Translated Thu Jan 27 00:33:04 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH INFINITY 3  2007-07-26 "" "Linux Programmer's Manual"
.SH 名前
INFINITY, NAN, HUGE_VAL, HUGE_VALF, HUGE_VALL \- 浮動小数点数の定数
.SH 書式
.nf
.BR "#define _ISOC99_SOURCE" "      /* feature_test_macros(7) 参照 */"
.br
.B #include <math.h>
.sp
.B INFINITY
.sp
.B NAN
.sp
.B HUGE_VAL
.br
.B HUGE_VALF
.br
.B HUGE_VALL
.fi
.SH 説明
マクロ
.B INFINITY
は正の無限大を表す
\fIfloat\fP 型の定数に展開される。

(サポートされている場合) マクロ
.B NAN
は quiet NaN を表す \fIfloat\fP 型の定数に展開される。
.I quiet
NaN は計算式の中で使われたときに例外を起こさない
NaN ("not-a-number") である。
この反対は
.I signalling
NaN である。
IEC 60559:1989 を参照すること。

マクロ
.BR HUGE_VAL ,
.BR HUGE_VALF ,
.B HUGE_VALL
はそれぞれ \fIdouble\fP, \fIfloat\fP, \fIlong double\fP 型の定数で、
大きな正の値を表し、可能な場合には正の無限大を表す。
.SH 準拠
C99.
.SH 可用性
glibc システムではマクロ
.B HUGE_VAL
が常に使用可能である。
.B NAN
マクロが使用できるかは、
.B "#ifdef NAN"
を使ってテストできる。
.BR INFINITY ,
.BR HUGE_VALF ,
.B HUGE_VALL
も同様である。
.B _ISOC99_SOURCE
か
.B _GNU_SOURCE
が定義されている場合、
または
.B __STDC_VERSION__
が定義されていて、その値が 199901L 以上である場合、
これらのマクロは
.I <math.h>
で定義される。
.SH 関連項目
.BR fpclassify (3),
.BR math_error (7)
