.\" Copyright (C) 2007 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" 2007-10-23 mtk, Nearly a complete rewrite of the earlier page.
.\"
.\" Japanese Version Copyright (c) 2008  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2008-02-10, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" 
.TH INTRO 3 2010-11-11 "Linux" "Linux Programmer's Manual"
.SH 名前
intro \- ライブラリ関数の紹介
.SH 説明
マニュアルの 3 章では、システムコールを実装した 2 章で説明された
ライブラリ関数 (システムコールのラッパー) を除いた
全てのライブラリ関数について説明している。

この章で説明している関数の多くは標準 C ライブラリ
.RI ( libc )
のものである。
また、いくつかの関数は、他のライブラリ (例えば、数学ライブラリの
.I libm
やリアルタイムライブラリ
.I librt )
のものである。後者の場合は、マニュアルページに、
必要なライブラリとリンクするために必要なリンカオプションが
示されている (例えば、前述のライブラリの場合はそれぞれ
.I \-lm
や
.I \-lrt
である)。

マニュアルページの「書式」の節に規定されたヘッダファイルから関数の定義を
得るために、プログラマが機能検査マクロを定義しなければならない場合がある。
このような場合には、必要なマクロがマニュアルページで説明されている。
(機能検査マクロの定義が必要な場合、これらの機能検査マクロの定義は
「どの」ヘッダファイルのインクルードよりも前で行われなければならない)。
機能検査マクロのさらなる情報については、
.BR feature_test_macros (7)
を参照のこと。
.\"
.\" 章番号に付け加えられている文字によって識別できる様々な関数のグループがある:
.\" .IP (3C)
.\" これら2章と3S章からの関数は標準Cライブラリ libc 中に含まれるものであり、
.\" デフォルトで
.\" .BR cc (1)
.\" によって使用されるであろう。
.\" .IP (3S)
.\" これらの関数は
.\" .BR stdio (3)
.\" ライブラリの一部である。標準Cライブラリ libc に含まれる。
.\" .IP (3M)
.\" これらの関数は数学関数ライブラリ libm に含まれる。これらは
.\" デフォルトで
.\" .BR f77 (1)
.\" フォートランコンパイラによって使用される、しかし
.\" .BR cc (1)
.\" Cコンパイラで使用するときは、\fI\-lm\fP オプションが必要となる。
.\" .IP (3F)
.\" これらの関数はフォートランライブラリ libF77 の一部である。
.\" これらの関数を使用するために特別なコンパイラフラグは必要ない。
.\" .IP (3X)
.\" 様々な特別なライブラリである。これらの関数を文書化したマニュアルページは
.\" ライブラリ名を指定する。
.SH 準拠
この章の関数が準拠する UNIX システムや標準を示すのにいくつかの単語や略号が
使用されている。
.BR standards (7)
を参照のこと。
.SH 備考
.SS 著者と著作権
著者と著作権の状態はマニュアルページのヘッダを見ること。
これらはページ毎に異なる可能性があることに注意。
.SH 関連項目
.BR intro (2),
.BR errno (3),
.BR capabilities (7),
.BR credentials (7),
.BR feature_test_macros (7),
.BR libc (7),
.BR math_error (7),
.BR environ (7),
.BR path_resolution (7),
.BR pthreads (7),
.BR signal (7),
.BR standards (7)
