.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\" and Copyright 2008, Linux Foundation, written by Michael Kerrisk
.\"     <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified 1993-07-24 by Rik Faith (faith@cs.unc.edu)
.\" Modified 1995-08-14 by Arnt Gulbrandsen <agulbra@troll.no>
.\" Modified 2002-07-27 by Walter Harms
.\" 	(walter.harms@informatik.uni-oldenburg.de)
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated Wed Aug  6 00:35:20 JST 2003
.\"         by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2008-09-16, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH LOG10 3  2010-09-20  "" "Linux Programmer's Manual"
.SH 名前
log10, log10f, log10l \-  底が 10 の対数関数
.SH 書式
.nf
.B #include <math.h>
.sp
.BI "double log10(double " x );
.br
.BI "float log10f(float " x );
.br
.BI "long double log10l(long double " x );
.fi
.sp
\fI\-lm\fP でリンクする。
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.ad l
.BR log10f (),
.BR log10l ():
.RS 4
_BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE\ >=\ 600 || _ISOC99_SOURCE ||
_POSIX_C_SOURCE\ >=\ 200112L;
.br
or
.I cc\ -std=c99
.RE
.ad
.SH 説明
.BR log10 ()
関数は \fIx\fP の常用対数 (底が 10 の対数) を返す。
.SH 返り値
成功すると、これらの関数は
.I x
の常用対数 (底が 10 の対数) を返す。

.I x
が 0、1、負、無限大、NaN などのさまざまな特別な状況については、
.BR log (3)
を参照のこと。
.SH エラー
これらの関数を呼び出した際にエラーが発生したかの判定方法についての情報は
.BR math_error (7)
を参照のこと。

これらの関数で発生するエラーについては、
.BR log (3)
を参照のこと。
.SH 準拠
C99, POSIX.1-2001.
.I double
版の関数は SVr4, 4.3BSD, C89 にも準拠している。
.SH 関連項目
.BR cbrt (3),
.BR clog10 (3),
.BR exp10 (3),
.BR log (3),
.BR log2 (3),
.BR sqrt (3)
