.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:55:27 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Japanese Version Copyright (c) 1997 HIROFUMI Nishizuka
.\"	all rights reserved.
.\" Translated Wed Dec 17 12:12:15 JST 1997
.\"	by HIROFUMI Nishizuka <nishi@rpts.cl.nec.co.jp>
.\"
.TH MEMCMP 3  2011-09-14 "" "Linux Programmer's Manual"
.SH 名前
memcmp \- メモリ領域を比較する
.SH 書式
.nf
.B #include <string.h>
.sp
.BI "int memcmp(const void *" s1 ", const void *" s2 ", size_t " n );
.fi
.SH 説明
.BR memcmp ()
関数は、メモリ領域 \fIs1\fP と\fIs2\fP の最初の \fIn\fP
バイトを比較する (各バイトは
.I "unsigned char"
として解釈される)。
\fIs1\fP が \fIs2\fP より小さいか、同じか、あるいは大きいかによって
それぞれ、負の整数、0、正の整数を返す。
.SH 返り値
.BR memcmp ()
関数は、\fIs1\fP の最初の \fIn\fP バイトが
\fIs2\fP の最初の \fIn\fP バイトよりも
小さいか、同じか、あるいは大きいかによってそれぞれ、負の整数、0、
正の整数を返す。
.SH 準拠
SVr4, 4.3BSD, C89, C99, POSIX.1-2001.
.SH 関連項目
.BR bcmp (3),
.BR strcasecmp (3),
.BR strcmp (3),
.BR strcoll (3),
.BR strncasecmp (3),
.BR strncmp (3),
.BR wmemcmp (3)
