.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Mar 10 00:40:50 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH NBP_NAME 3 "12 Jan 1994" "netatalk 1.3"
.SH 名前
nbp_name \- NBP 名を解釈する
.SH 書式
.nf
nbp_name( name, obj, type, zone )
char *name, **obj, **type, **zone;
.fi
.SH 説明
.B nbp_name()
はユーザーがコンポーネントオブジェクト・
タイプ・ゾーンに与えた名前を解釈する。
.BR obj ,
.BR type ,
.B zone
は参照として渡すべきであり、
呼び出し側のデフォルトの値を指しているべきである。
.B nbp_name()
は解釈し終った値にポインタを移動する。
.B name
は
.IB object : \c
.IB type @ \c
.I zone
という形式である。
ここで、
.IR object ,
.BI : type ,
.BI @ zone
はそれぞれ
.BR obj ,
.BR type ,
.B zone
を置き換える。
.I type
の前には
.RB ` : '
がなければいけない。
そして、
.I zone
の前には
.RB ` @ '
がなければいけない。
.SH 例
.BR afpd (8)
の
.B -n
オプションの引き数は、
.B nbp_name()
で解釈される。
.B obj
のデフォルトの値は、
.RB ( gethostbyname (3)
で返される) マシンのホスト名からドメイン部を取ったものである。
.B type
のデフォルトの値は `AFPServer'' であり、
.B zone
のデフォルトの値はデフォルトのゾーン ``*'' である。
.B afpd
をデフォルトのゾーン以外のゾーンに登録させるには、
次のように起動すればよい。
.sp
.RS
.nf
afpd -n @some-other-zone
.fi
.RE
.sp
.B obj
と
.B type
はデフォルトの値が取得される。
.SH バグ
.BR obj ,
.BR type ,
.B zone
は、呼び出しの度に上書きされる静的領域へのポインタを返す。

