.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (C) 2004 Michael Kerrisk
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Japanese Version Copyright (c) 2005 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Jan 30 08:55:16 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH POSIX_OPENPT 3 2010-10-04 "" "Linux Programmer's Manual"
.SH 名前
posix_openpt \- 疑似端末 (pseudoterminal) デバイスをオープンする
.SH 書式
.nf
.B #include <stdlib.h>
.B #include <fcntl.h>
.sp
.BI "int posix_openpt(int " flags ");"
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.ad l
.BR posix_openpt ():
_XOPEN_SOURCE\ >=\ 600
.ad b
.SH 説明
.BR posix_openpt ()
関数は使用されていない疑似端末マスタデバイスをオープンし、
そのデバイスを参照するために使うファイルディスクリプタを返す。
.I flags
引き数は、以下のフラグのうち 0 個以上の OR をとったビットマスクである。
.TP
.B O_RDWR
読み書きのためにデバイスをオープンする。
普通はこのフラグを指定する。
.TP
.B O_NOCTTY
このデバイスをプロセスの制御端末としない。
.SH 返り値
成功した場合、
.BR posix_openpt ()
は負ではないファイルディスクリプタを返す。
これは使用されていないディスクリプタのうち最小の値である。
失敗した場合、\-1 が返されて、エラーを示すために
.I errno
が設定される。
.SH エラー
.BR open (2)
を参照すること。
.SH バージョン
.BR posix_openpt ()
の glibc でのサポートはバージョン 2.2.1 以降で提供されている。
.SH 準拠
.BR posix_openpt ()
は UNIX 98 疑似端末サポート
.RB ( pts (4)
を参照) の一部である。
この関数は POSIX.1-2001 で指定されている。
.SH 注意
この関数は POSIX において最近作られたものである。
System V (別名 UNIX 98) 疑似端末をサポートする UNIX 実装の中には、
この関数を持たないものもあるが、以下のようにして簡単に実装できる:
.in +4n
.nf

int
posix_openpt(int flags)
{
    return open("/dev/ptmx", flags);
}
.fi
.in
.SH 関連項目
.BR open (2),
.BR getpt (3),
.BR grantpt (3),
.BR ptsname (3),
.BR unlockpt (3),
.BR pts (4),
.BR pty (7)
