.\" Copyright (C) 2006 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be
.\" included in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
.\" CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
.\" TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
.\" SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Japanese Version Copyright (c) 2006 Akihiro MOTOKI all rights reserved.
.\" Translated 2006-03-13, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH INVOCATION_NAME 3 2006-04-29 "GNU" "Linux Programmer's Manual"
.SH 名前
program_invocation_name, program_invocation_short_name \- \
プログラムの起動に使われた名前を取得する
.SH 書式
.nf
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.B #include <errno.h>

.BI "extern char *" program_invocation_name ;
.BI "extern char *" program_invocation_short_name ;
.fi
.SH 説明
.I program_invocation_name
は、呼び出し元プログラムの起動に使用された名前を保持する。
内容は
.IR main ()
の
.I argv[0]
の値と同じだが、
.I program_invocation_name
の方はスコープがグローバルである点が異なる。

.I program_invocation_short_name
は、呼び出し元プログラムの起動に使用された名前の basename 部分を
保持する。つまり、この変数の内容は、最後のスラッシュ (/) とそれより前の
部分がある場合、
.I program_invocation_name
からこの部分を削除したものとなる。

これらの変数は glibc のランタイム・スタートアップ・コードで
自動的に初期化される。
.SH 準拠
これらの変数は GNU の拡張であり、
移植性が必要なプログラムでは使用すべきでない。
.SH 備考
Linux 独自のファイル
.I /proc/[number]/cmdline
でも同様の情報を得ることができる。
.SH 関連項目
.BR proc (5)
