.\"   Copyright (C) 1996-1999 Free Software Foundation, Inc.
.\"
.\"   Permission is granted to make and distribute verbatim copies of
.\" this manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\"   Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\"   Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that this permission notice may be stated in a
.\" translation approved by the Foundation.
.\"
.\" Copyright (C) 1996 Xavier Leroy.
.\"
.\" Japanese Version Copyright (C) 2002-2003 Suzuki Takashi
.\"         all rights reserved.
.\" Translated Tue Dec 31 17:51:46 JST 2002
.\"         by Suzuki Takashi.
.\"
.\"WORD:    thread identifier   スレッドID
.\"
.\"
.TH PTHREAD_EQUAL 3 LinuxThreads

.SH 名前
pthread_equal \- 2 つのスレッド ID を比較する

.SH "書式"
.B #include <pthread.h>

.BI "int pthread_equal(pthread_t " thread1 ", pthread_t " thread2 ");"

.SH "説明"
.B "pthread_equal"
は 2 つのスレッド ID が同一のスレッドを指しているかどうかを判定する。

.SH "返り値"
.I "thread1"
と
.I "thread2"
が同一のスレッドを指しているとき、
非 0 の値が返る。
それ以外の場合、 0 が返る。

.SH "著者"
Xavier Leroy <Xavier.Leroy@inria.fr>

.SH "関連項目"
.BR "pthread_self" (3).
