.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:12:45 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Japanese Version Copyright (c) 1997 HIROFUMI Nishizuka
.\"	all rights reserved.
.\" Translated Thu Dec 25 10:54:13 JST 1997
.\"	by HIROFUMI Nishizuka <nishi@rpts.cl.nec.co.jp>
.\"
.TH STRCASECMP 3  2010-09-20 "" "Linux Programmer's Manual"
.SH 名前
strcasecmp, strncasecmp \- 二つの文字列を大文字小文字を区別せず比較する
.SH 書式
.nf
.B #include <strings.h>
.sp
.BI "int strcasecmp(const char *" s1 ", const char *" s2 );
.sp
.BI "int strncasecmp(const char *" s1 ", const char *" s2 ", size_t " n );
.fi
.SH 説明
.BR strcasecmp ()
関数は、二つの文字列　\fIs1\fP と \fIs2\fP を、
大文字小文字を区別せずに比較する。
\fIs1\fP が \fIs2\fP よりも小さいか、同じか、大きいかによってそれぞれ
負の整数、0、正の整数を返す。
.PP
.BR strncasecmp ()
関数も同様であるが、
\fIs1\fP の最初の \fIn\fP 文字だけを比較する点だけが異なる。
.SH 返り値
.BR strcasecmp ()
と
.BR strncasecmp ()
関数は、\fIs1\fP
(または、その最初の \fIn\fP バイト)が \fIs2\fP よりも小さいか、
同じか、大きいかにより、それぞれ負の整数、0、正の整数を返す。
.SH 準拠
4.4BSD, POSIX.1-2001.
.SH 関連項目
.BR bcmp (3),
.BR memcmp (3),
.BR strcmp (3),
.BR strcoll (3),
.BR string (3),
.BR strncmp (3),
.BR wcscasecmp (3),
.BR wcsncasecmp (3)
