.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:08:52 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified 2001-08-31, aeb
.\"
.\" Japanese Version Copyright (c) 1997 YOSHINO Takashi
.\"       all rights reserved.
.\" Translated Mon Jan 20 22:42:02 JST 1997
.\"       by YOSHINO Takashi <yoshino@civil.jcn.nihon-u.ac.jp>
.\" Updated Fri Oct 12 JST 2001 by Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH STRCMP 3  2010-09-20 "" "Linux Programmer's Manual"
.SH 名前
strcmp, strncmp \- 二つの文字列を比べる
.SH 書式
.nf
.B #include <string.h>
.sp
.BI "int strcmp(const char *" s1 ", const char *" s2 );
.sp
.BI "int strncmp(const char *" s1 ", const char *" s2 ", size_t " n );
.fi
.SH 説明
.BR strcmp ()
関数は二つの文字列 \fIs1\fP と \fIs2\fP を較べる。
この関数は、
\fIs1\fP が \fIs2\fP に較べて 1)小さい、2)等しい、3)大きい場合に、
ゼロよりも 1)小さい、2)等しい、3)大きい整数を返す。
.PP
.BR strncmp ()
関数は、\fIs1\fP と \fIs2\fP の最初の
\fIn\fP 文字だけを比較することを除けば、strcmp()と同様である。
.SH 返り値
.BR strcmp ()
関数と
.BR strncmp ()
関数は整数を返す。
この整数は、ゼロよりも、1)小さい、2)等しい、3)大きいのいずれかである。
それぞれは、\fIs1\fP（または、この文字列の最初の \fIn\fP バイト）が
\fIs2\fP よりも、1)小さい、2)等しい、3)大きいに対応している。
.SH 準拠
SVr4, 4.3BSD, C89, C99.
.SH 関連項目
.BR bcmp (3),
.BR memcmp (3),
.BR strcasecmp (3),
.BR strcoll (3),
.BR string (3),
.BR strncasecmp (3),
.BR strverscmp (3),
.BR wcscmp (3),
.BR wcsncmp (3)
