.\" Copyright (c) 2007 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Japanese Version Copyright (c) 2007  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2007-06-02, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" 
.\"WORD:	reliable	信頼性のある
.\"WORD:	unreliable	信頼性に欠ける
.\"WORD:	signal semantics	シグナル処理方式
.\" 
.TH SYSV_SIGNAL 3 2007-05-04 "" "Linux Programmer's Manual"
.SH 名前
sysv_signal \- System V 方式のシグナル処理
.SH 書式
.BR "#define _GNU_SOURCE" "         /* feature_test_macros(7) 参照 */"
.br
.B #include <signal.h>
.sp
.B typedef void (*sighandler_t)(int);
.sp
.BI "sighandler_t sysv_signal(int " signum ", sighandler_t " handler );
.SH 説明
.BR sysv_signal ()
関数は
.BR signal (2)
と同じ引き数をとり、同じ処理を実行する。

しかしながら、
.BR sysv_signal ()
は System V の信頼性に欠けるシグナル処理方式を提供している。
信頼性に欠けるシグナル処理方式は以下の特徴を持つ。
a) ハンドラが起動されると、シグナルの処理方法 (disposition) が
デフォルトにリセットされる、
b) シグナルハンドラの実行中は、それ以降に発生した同じシグナルの配送が
ブロックされない、
c) ハンドラが停止中の (blocking している) システムコールを中断した場合、
自動的に再開されないシステムコールがある。
.SH 返り値
.BR sysv_signal ()
関数はシグナルハンドラの直前の値を返す。
エラーの場合、
.B SIG_ERR
を返す。
.SH エラー
.BR signal (2)
と同じ。
.SH 準拠
この関数は非標準である。
.SH 注意
.BR sysv_signal ()
の使用は避けるべきである。代わりに
.BR sigaction (2)
を使うこと。

以前の Linux システムでは、
.BR sysv_signal ()
と
.BR signal (2)
は等価であった。しかし、新しめのシステムでは、
.BR signal (2)
は信頼性のあるシグナル処理方式を提供している。
詳細は
.BR signal (2)
を参照。

.I sighandler_t
を使っているのは GNU による拡張である。
この型は機能検査マクロ
.B _GNU_SOURCE
を定義した場合にのみ定義される。
.SH 関連項目
.BR sigaction (2),
.BR signal (2),
.BR bsd_signal (3),
.BR signal (7)
