.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:48:42 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Japanese Version Copyright (c) 1997 HIROFUMI Nishizuka
.\"	all rights reserved.
.\" Translated 1997-12-24, HIROFUMI Nishizuka <nishi@rpts.cl.nec.co.jp>
.\" Updated & Modified 2005-02-19, Yuichi SATO <ysato444@yahoo.co.jp>
.\" Updated 2009-04-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v3.20
.\"
.TH TELLDIR 3  2009-03-11 "" "Linux Programmer's Manual"
.SH 名前
telldir \- ディレクトリストリーム中の現在位置を返す
.SH 書式
.nf
.B #include <dirent.h>
.sp
.BI "long telldir(DIR *" dirp );
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR telldir ():
_BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE
.SH 説明
.BR telldir ()
関数は、ディレクトリストリーム \fIdirp\fP に結びつけられた
現在位置を返す。
.SH 返り値
成功した場合、
.BR telldir ()
関数はディレクトリストリーム中の現在位置を返す。
エラーの場合、\-1 が返されて、
.I errno
が適切に設定される。
.SH エラー
.TP
.B EBADF
ディレクトリストリームディスクリプタ \fIdirp\fP が無効である。
.SH 準拠
4.3BSD, POSIX.1-2001.
.SH 注意
バージョン 2.1.1 以前の glibc では、
.BR telldir ()9
の返り値の型は
.I off_t
であった。
POSIX.1-2001 では
.I long
と規定されており、glibc 2.1.2 以降では
.I long
になっている。
.SH 関連項目
.BR closedir (3),
.BR opendir (3),
.BR readdir (3),
.BR rewinddir (3),
.BR scandir (3),
.BR seekdir (3)
