.\" Copyright (c) 2007 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" 2007-07-31, mtk, Created
.\"
.\" Japanese Version Copyright (c) 2007  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2007-10-16, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v2.66
.\" Updated 2009-04-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v3.20
.\" 
.TH TIMERADD 3 2010-02-25 "Linux" "Linux Programmer's Manual"
.SH 名前
timeradd, timersub, timercmp, timerclear, timerisset \- timeval の操作
.SH 書式
.nf
.B #include <sys/time.h>

.BI "void timeradd(struct timeval *" a ", struct timeval *" b ,
.BI "              struct timeval *" res );

.BI "void timersub(struct timeval *" a ", struct timeval *" b ,
.BI "              struct timeval *" res );

.BI "void timerclear(struct timeval *" tvp );

.BI "int timerisset(struct timeval *" tvp );

.BI "int timercmp(struct timeval *" a ", struct timeval *" b ", " CMP );
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
上記の全ての関数:
_BSD_SOURCE
.SH 説明
.I timeval
構造体を操作するためのマクロが提供されている。
.I timeval
構造体は
.I <sys/time.h>
で以下のように定義されている。
.sp
.in +4n
.nf
struct timeval {
    time_t      tv_sec;     /* 秒 */
    suseconds_t tv_usec;    /* マイクロ秒 */
};
.fi
.in
.PP
.BR timeradd ()
は、
.I a
と
.I b
の時刻値を加算し、その合計を
.I res
により参照される
.I timeval
構造体に格納する。結果は、
.I res\->tv_usec
の値が 0 から 999,999 の範囲に入るように正規化される。

.BR timersub ()
は、
.I a
の時刻値から
.I b
の時刻値を減算し、その結果を
.I res
により参照される
.I timeval
構造体に格納する。結果は、
.I res\->tv_usec
の値が 0 から 999,999 の範囲に入るように正規化される。

.BR timerclear ()
は
.I tvp
により参照される
.I timeval
構造体を 0 で埋める。
0 で埋められた
.I timeval
構造体は、時刻紀元 (Epoch; 1970-01-01 00:00:00 +0000 (UTC)) を表す。

.BR timerisset ()
は、
.I tvp
により参照される
.I timeval
構造体のいずれか一方のフィールドに 0 以外の値が入っていれば、
真 (0 以外) を返す。

.BR timercmp ()
は
.I a
と
.I b
の時刻値を比較演算子
.I CMP
を使って比較し、比較結果に基づき、真 (0 以外) か偽 (0) を返す。
(Linux/glibc はそうではないが)
いくつかのシステムでは、
.BRr timercmp ()
の実装がおかしく、
.\" HP-UX, Tru64, Irix では以下のように定義されている。
.\"#define timercmp(tvp, uvp, cmp) \
.\"    ((tvp)->tv_sec cmp (uvp)->tv_sec || \
.\"    (tvp)->tv_sec == (uvp)->tv_sec && (tvp)->tv_usec cmp (uvp)->tv_usec)
.I CMP
に
.IR >= ,
.IR <= ,
.I ==
を指定すると正しく動作しない。
移植性が必要なアプリケーションでは、
代わりに以下を使うこと。

    !timercmp(..., <)
    !timercmp(..., >)
    !timercmp(..., !=)
.SH 返り値
.BR timerisset ()
と
.BR timercmp ()
は、真 (0 以外) か偽 (0) を返す。
.BR
.SH エラー
エラーは定義されていない。
.SH 準拠
POSIX.1-2001 にはない。
ほとんどの BSD 由来のシステムには存在する。
.SH 関連項目
.BR gettimeofday (2),
.BR time (7)
