.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Mon Oct 25 22:24:35 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCPCPY 3  2011-10-01 "GNU" "Linux Programmer's Manual"
.SH 名前
wcpcpy \- ワイド文字文字列をコピーし、その末尾を指すポインタを返す
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcpcpy(wchar_t *" dest ", const wchar_t *" src );
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR wcpcpy ():
.PD 0
.ad l
.RS 4
.TP 4
glibc 2.10 以降:
_XOPEN_SOURCE\ >=\ 700 || _POSIX_C_SOURCE\ >=\ 200809L
.TP
glibc 2.10 より前:
_GNU_SOURCE
.RE
.ad
.PD
.SH 説明
.BR wcpcpy ()
関数は、
.BR stpcpy (3)
関数に対応するワイド文字関数である。
この関数は \fIsrc\fP が指すワイド文字文字列を、
終端の NULL ワイド文字 (L\(aq\\0\(aq) を含めて、
\fIdest\fP が指す配列にコピーする。
.PP
これらの文字列は重なっていてはならない。
.PP
プログラマは、\fIdest\fP が指す領域に少なくともワイド文字
\fIwcslen(src)+1\fP 個分の領域を確保しなければならない。
.SH 返り値
.BR wcpcpy ()
は、ワイド文字文字列 \fIdest\fP の末尾、つまり終端の NULL ワイド文字
を指すポインタを返す。
.SH 準拠
POSIX.1-2008.
.SH 関連項目
.BR strcpy (3),
.BR wcscpy (3)
