.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sun Oct 17 21:56:31 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSCHR 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wcschr \- ワイド文字文字列中のワイド文字を検索する
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcschr(const wchar_t *" wcs ", wchar_t " wc );
.fi
.SH 説明
.BR wcschr ()
関数は、
.BR strchr (3)
関数に対応するワイド文字関数である。
この関数は、\fIwcs\fP が指すワイド文字文字列の中で最初に現われる \fIwc\fP を検索する。
.SH 返り値
.BR wcschr ()
関数は、\fIwcs\fP が指すワイド文字文字列の中で最初に現われた
\fIwc\fP へのポインタを返す。\fIwc\fP が文字列中に現われなかった場合は
NULL を返す。
.SH 準拠
C99.
.SH 関連項目
.BR strchr (3),
.BR wcspbrk (3),
.BR wcsrchr (3),
.BR wcsstr (3),
.BR wmemchr (3)
