.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Mon Oct 18 22:43:56 JST 1999
.\"         by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSLEN 3  2011-09-28 "GNU" "Linux Programmer's Manual"
.SH 名前
wcslen \- ワイド文字文字列の長さを求める
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "size_t wcslen(const wchar_t *" s );
.fi
.SH 説明
.BR wcslen ()
関数は、
.BR strlen (3)
関数に対応するワイド文字関数である。
この関数は、\fIs\fP が指すワイド文字文字列の長さを求める。
終端の NULL ワイド文字 (L\(aq\\0\(aq) はこの長さには含まれない。
.SH 返り値
.BR wcslen ()
関数は、\fIs\fP に含まれるワイド文字の数を返す。
.SH 準拠
C99.
.SH 関連項目
.BR strlen (3)
