.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 15:19:34 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSRCHR 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wcsrchr \- ワイド文字列中のワイド文字を探す
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsrchr(const wchar_t *" wcs ", wchar_t " wc );
.fi
.SH 説明
.BR wcsrchr ()
関数は、
.BR strrchr (3)
関数に対応するワイド文字関数である。
この関数は、\fIwcs\fP が指すワイド文字文字列中に \fIwc\fP が最後に現わ
れる位置を検索する。
.SH 返り値
\fBwcsrchr\fP 関数は、\fIwcs\fP が指すワイド文字文字列中に \fIwc\fP が
最後に現われた位置を返す。この文字列に \fIwc\fP が含まれていなければ
NULL を返す。
.SH 準拠
C99.
.SH 関連項目
.BR strrchr (3),
.BR wcschr (3)
