.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 15:50:55 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSSTR 3  2011-09-28 "GNU" "Linux Programmer's Manual"
.SH 名前
wcsstr \- ワイド文字文字列中の部分文字列の位置を特定する
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsstr(const wchar_t *" haystack ", const wchar_t *" needle );
.fi
.SH 説明
.BR wcsstr ()
関数は、
.BR strstr (3)
関数に対応するワイド文字文字列である。
この関数はワイド文字文字列 \fIneedle\fP (終端の NULL ワイド文字
(L\(aq\\0\(aq) は含まない) が、ワイド文字文字列 \fIhaystack\fP の部分文字列
として最初に現われる位置を探す。
.SH 返り値
.BR wcsstr ()
関数は、\fIhaystack\fP 中に \fIneedle\fP が現われた最初の
位置を返す。\fIneedle\fP が \fIhaystack\fP の部分文字列でなければ
NULL を返す。
.PP
以下の特殊な場合に注意すること: \fIneedle\fP が空のワイド文字文字列な
らば、返り値は常に \fIhaystack\fP 自身となる。
.SH 準拠
C99.
.SH 関連項目
.BR strstr (3),
.BR wcschr (3)
