.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 15:46:13 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSSPN 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wcsspn \- ワイド文字文字列を進み、ワイド文字の集合の文字をスキップする
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "size_t wcsspn(const wchar_t *" wcs ", const wchar_t *" accept );
.fi
.SH 説明
.BR wcsspn ()
関数は、
.BR strspn (3)
関数に対応するワイド文字関数である。
この関数は、\fIwcs\fP の先頭部分を調べ、\fIaccept\fP に列挙されている
ワイド文字だけによって構成される部分を最も長く取った場合の長さを求める。
言い換えると、この関数はワイド文字文字列 \fIwcs\fP の中に、ワイド文字列
\fIaccept\fP に含まれていない文字が現われる最初の位置を探す。
.SH 返り値
.BR wcsspn ()
関数は、\fIwcs\fP の先頭部分を調べ、\fIaccept\fP に列挙さ
れているワイド文字だけによって構成される部分を最も長く取った場合の長さ
を返す。
言い換えると、この関数はワイド文字文字列 \fIwcs\fP の中に、ワイド文字列
\fIaccept\fP に含まれていない文字が現われる最初の位置を返す。
何も現われなかった場合には \fIwcslen(wcs)\fP を返す。
.SH 準拠
C99.
.SH 関連項目
.BR strspn (3),
.BR wcscspn (3)
