.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 18:44:42 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCSWIDTH 3  2010-09-10 "GNU" "Linux Programmer's Manual"
.SH 名前
wcswidth \- 固定サイズのワイド文字文字列の表示に必要なカラム数を求める
.SH 書式
.nf
.BR "#define _XOPEN_SOURCE" "             /* feature_test_macros(7) 参照 */"
.B #include <wchar.h>
.sp
.BI "int wcswidth(const wchar_t *" s ", size_t " n );
.fi
.SH 説明
.BR wcswidth ()
関数は、\fIs\fP が指すワイド文字文字列を表現するために
必要なカラム数を返す。ただし、最大 \fIn\fP 文字しか処理しない。
印刷可能でないワイド文字が文字列に含まれる場合には、 \-1 が返される。
.SH 返り値
.BR wcswidth ()
関数は、ワイド文字文字列 \fIs\fP の表現に必要なカラム数
を返す。ただしワイド文字文字列は最大 \fIn\fP 個に切り詰められる。
.SH 準拠
POSIX.1-2001.
.SH 注意
.BR wcswidth ()
の動作は現在のロケールの
.B LC_CTYPE
カテゴリに依存する。
.SH 関連項目
.BR iswprint (3),
.BR wcwidth (3)
