.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 19:35:47 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCTOB 3 2011-09-22 "GNU" "Linux Programmer's Manual"
.SH 名前
wctob \- ワイド文字のシングルバイト表現を試みる
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "int wctob(wint_t " c );
.fi
.SH 説明
.BR wctob ()
関数は、ワイド文字 \fIc\fP のマルチバイト表現(初期状態で開
始)がシングルバイト文字だけでできているかどうかを調べる。もしそうであ
れば、これを
.I "unsigned char"
型として返す。
.PP
この関数は決して使わないこと。この関数は国際化プログラムを書く上では役
に立たない。国際化されたプログラムでは、シングルバイト文字とマルチバイト
文字を区別してはならない。
.SH 返り値
.BR wctob ()
関数は \fIc\fP のシングルバイト表現が存在すれば、その表現
を返す。存在しなければ \fBEOF\fP を返す。
.SH 準拠
C99.
.SH 注意
.BR wctob ()
の動作は、現在のロケールの
.B LC_CTYPE
カテゴリに依存する。
.PP
この関数は決して使うべきではない。国際化プログラムでは、シングルバイト
文字とマルチバイト文字を区別してはならない。代わりに、
.BR wctomb (3)
か、スレッドセーフな
.BR wcrtomb (3)
を使うこと。
.SH 関連項目
.BR btowc (3),
.BR wcrtomb (3),
.BR wctomb (3)
