.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Sat Oct 23 19:48:40 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WCTRANS 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wctrans \- ワイド文字変換マッピング
.SH 書式
.nf
.B #include <wctype.h>
.sp
.BI "wctrans_t wctrans(const char *" name );
.fi
.SH 説明
\fIwctrans_t\fP 型は、あるワイド文字を他のワイド文字に変換できるマッピ
ングを表現する。本質的には実装依存であるが、特殊な値
\fI(wctrans_t)0\fP は不正なマッピングを示す。0 でない値を持つ
\fIwctrans_t\fP を
.BR towctrans (3)
関数に渡すことによって、実際に
ワイド文字の変換を実行させることができる。
.PP
.BR wctrans ()
は、名前によって与えられるマッピングを返す。有効な名前の
集合は現在のロケールの
.B LC_CTYPE
カテゴリに依存するが、以下の名前は全てのロケールにおいて有効である。
.nf

  "tolower" \- \fBtolower\fP(3) のマッピングを実現する
  "toupper" \- \fBtoupper\fP(3) のマッピングを実現する
.fi
.SH 返り値
.BR wctrans ()
関数は、\fIname\fP が有効ならばマッピング記述子を返す。
有効でなければ \fI(wctrans_t) 0\fP を返す。
.SH 準拠
C99.
.SH 注意
.BR wctrans ()
の動作は、現在のロケールの
.B LC_CTYPE
カテゴリに依存する。
.SH 関連項目
.BR towctrans (3)
