.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Tue Oct 26 00:51:32 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WMEMSET 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wmemset \- ワイド文字の配列を定数のワイド文字で埋める
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemset(wchar_t *" wcs ", wchar_t " wc ", size_t " n );
.fi
.SH 説明
.BR wmemset ()
関数は、
.BR memset (3)
関数に対応するワイド文字関数である。
この関数は、\fBmemset\fP を先頭とする \fIn\fP 個のワイド文字の配列を、
ワイド文字 \fIwc\fP の \fIn\fP 個のコピーで埋める。
.SH 返り値
.BR wmemset ()
は \fIwcs\fP を返す。
.SH 準拠
C99.
.SH 関連項目
.BR memset (3)
