.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Tue Oct 26 00:51:13 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WMEMMOVE 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wmemmove \-ワイド文字の配列をコピーする
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemmove(wchar_t *" dest ", const wchar_t *" src ", size_t " n );
.fi
.SH 説明
.BR wmemmove ()
関数は、
.BR memmove (3)
関数に対応するワイド文字関数であ
る。この関数は \fIsrc\fP を先頭とする配列から \fIdest\fP を先頭とする
配列に \fIn\fP 個のワイド文字をコピーする。2 つの配列は重なっていても
構わない。
.PP
プログラマは、少なくとも \fIn\fP 個のワイド文字が入る領域を \fIdest\fP
に確保しなければならない。
.SH 返り値
.BR wmemmove ()
は \fIdest\fP を返す。
.SH 準拠
C99.
.SH 関連項目
.BR memmove (3),
.BR wmemcpy (3)
