.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Tue Oct 26 00:03:46 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\"
.TH WMEMCHR 3 1999-07-25 "GNU" "Linux Programmer's Manual"
.SH 名前
wmemchr \- ワイド文字の配列からワイド文字を探す
.SH 書式
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemchr(const wchar_t *" s ", wchar_t " c ", size_t " n );
.fi
.SH 説明
.BR wmemchr ()
関数は、
.BR memchr (3)
関数に対応するワイド文字関数である。
この関数は、\fIs\fP を先頭とする \fIn\fP 個のワイド文字の中から、最初
にワイド文字 \fIc\fP が現われる場所を探す。
.SH 返り値
.BR wmemchr ()
関数は、\fIs\fP を先頭とする \fIn\fP 個のワイド文字の中
において最初に \fIc\fP が現われる場所へのポインタを返す。\fIc\fP が現
われなかった場合には NULL を返す。
.SH 準拠
C99.
.SH 関連項目
.BR memchr (3),
.BR wcschr (3)
