#!/bin/sh

func_get_extension ()
{
    path=$1
    basename=${path##*/}
    filename=${basename%.*}
    extension=${basename##*.}
    echo $extension
}

for file in `git diff --name-only HEAD@{1} HEAD` ; do
    file_extension=`func_get_extension $file`
    if [ $file_extension = "el" ]; then
        echo "rm -rf ${file}c"
        rm -rf ${file}c
    fi
done
