.\" Copyright (c) 1997 Free Software Foundation
.\" See COPYING for conditions for redistribution
.\"
.\" Japanese Version Copyright (c) 1997 NAKANO Takeo all rights reserved.
.\" Translated Thu Dec 25 1997 by NAKANO Takeo <nakano@@apm.seikei.ac.jp>
.\"
.\" WORD	executable	実行ファイル
.\"
.TH addr2line 1 "27 March 1997" "Cygnus Solutions" "GNU Development Tools"
.de BP
.sp
.ti \-.2i
\(**
..

.SH 名前
addr2line \- アドレスをファイル名と行番号に変換する

.SH 書式
.hy 0
.na
.TP
.B addr2line
.RB "[\|" "\-b\ "\c
.I bfdname\c
.RB " | " "\-\-target="\c
.I bfdname\c
\&\|]
.RB "[\|" \-C | \-\-demangle "\|]"
.RB "[\|" "\-e\ "\c
.I filename\c
.RB " | " "\-\-exe="\c
.I filename\c
\&\|]
.RB "[\|" \-f | \-\-functions "\|]"
.RB "[\|" \-s | \-\-basenames "\|]"
.RB "[\|" \-H | \-\-help "\|]"
.RB "[\|" \-V | \-\-version "\|]"
.RB "[\|" addr addr ...  "\|]"
.ad b
.hy 1
.SH 説明
.B addr2line
はプログラム内のアドレスをファイル名と行番号に変換する。アドレスと実行
ファイルが与えられると、
.B addr2line
は実行ファイルのデバッグ情報を用いて、アドレスに関連付けられているファ
イル名と行番号を求める。

実行ファイルは
.B \-e
オプションを用いて指定できる。デフォルトは
.B a.out
である。

.B addr2line
には二つの実行モードがある。

最初のモードでは、コマンドラインで 16 進数のアドレスを指定する。
.B addr2line
はそれぞれのアドレスに対してファイル名と行番号を表示する。

二つめのモードでは、
.B addr2line
は 16 進数のアドレスを標準入力から読み込み、それぞれのアドレスに対応す
るファイル名と行番号を標準出力に表示する。このモードでは
.B addr2line
は動的に選択されたアドレスを変換するパイプとして用いることができる。

出力フォーマットは「ファイル名:行番号」である。各アドレスに対
応してこのペアが行ごとに表示される。
.B \-f
オプションが用いられると、「ファイル名:行番号」の行それぞれの前に
「関数名」行が置かれる。これはそのアドレスが所属する関数の名前である。

ファイル名または関数の名前が決定できない場合は、
.B addr2line
は代わりに二つのクエスチョンマークを表示する。行番号が決定できない場合
は、
.B addr2line
は 0 を表示する。

.SH オプション
.TP
.BI "\-b " "bfdname"\c
.TP
.BI "\-\-target=" "bfdname"
オブジェクトファイルのオブジェクトコードフォーマットを
.I bfdname
として取り扱う。

.TP
.B \-C
.TP
.B \-\-demangle
低レベルのシンボル名をユーザーレベルのシンボル名にデコード
(\fIdemangle\fP) する。このときシステムによって前置されたアンダースコ
アも削除される。この操作によって C++ の関数名が可読になる。

.TP
.BI "\-e " "filename"\c
.TP
.BI "\-\-exe=" "filename"
アドレスを変換したい実行ファイルの名前を指定する。デフォルトのファイル
は
.B a.out
である。

.TP
.B \-f
.TP
.B \-\-functions
ファイル名や行番号の情報と共に関数の名前も表示する。

.TP
.B \-s
.TP
.B \-\-basenames
それぞれのファイル名のベースのみを表示する (ディレクトリを表示しない)。

.SH 関連項目
.B info
の `\fB binutils \fP' エントリ、
.IR "The GNU Binary Utilities" ,
Roland H. Pesch (October 1991)、

.\" COPYING はいらないのかなあ？
.SH 著作権
(これは原文にはありませんが、 binutils の他のものを付記しました 
\-\- 訳者)
.PP
Copyright (c) 1993 Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
