.\"
.\" Japanese Version Copyright (c) 2002 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Nov 10 04:11:05 JST 2002
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH APPLE_RM 1 "16 Oct 2001" "Netatalk 1.5"
.SH 名前
apple_rm \- apple ファイルを削除し、リソースフォークも削除する

.SH 書式
.BR /usr/bin/apple_rm
\fIFILE\fR...

.SH 説明
.B apple_rm
は perl スクリプトであり、
FILE とそれに対応する .AppleDouble リソースフォークファイルを削除する。
.B apple_rm
はディレクトリを削除しない。

.SH 例

.BR /usr/bin/apple_rm
test.text 

.BR /usr/bin/apple_rm
test.text testing.text

.SH バグ報告
バグは Netatalk-devel メーリングリスト
<netatalk-devel@lists.sourceforge.net> へ報告してください。

.SH 関連項目
.BR apple_cp (1),
.BR apple_mv (1).
