.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU basename man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.\"WORD:	suffix		拡張子
.TH basename 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
basename \- ファイル名からディレクトリと拡張子を取り去る
.SH 書式
.BI "basename " name " [" suffix ]
.sp
.B basename [\-\-help] [\-\-version]
.SH 説明
.B basename
は
.I name
から、前の方にあるディレクトリの部分をすべて取り去る。
.PP
.I suffix
が指定され、それが
.I name
の末尾と一致すると、
その部分も
.I name
から同時に除去される。
.B basename
は結果の名前を標準出力に表示する。
.SH オプション
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
