.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Sat 23 Oct 1999 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH CLEAR 1 "10 October 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 名前
clear \- 端末スクリーンをクリアする
.SH 書式
.BR clear
.SH 説明
.B clear
は
.BR tput (1)
を
.I clear
引数とともに呼ぶ。すると
.B tput
はスクリーンをクリアしようとする。
そのときのデータは、 GNU または BSD \fBtput\fR では
.I /etc/termcap
から取得され、 \fBncurses\fR の \fBtput\fR では
.I /etc/terminfo
から取得される。
このコマンドは、リダイレクトすれば他の端末のスクリーンを
クリアすることができる。
.SH 関連項目
.BR reset (1),
.BR stty (1),
.BR tput (1)
.SH 著者
Rik Faith (faith@cs.unc.edu)
