.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"	GNU expand man page
.\"	man pages are NOT obsolete!
.\"	<ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Sat Jan 24 12:36:40 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH EXPAND 1 "7 October 2002" "GNU textutils 2.1"
.SH 名前
expand \- タブをスペースに変換する
.SH 書式
.B expand
.RB [ \-i ]
.RB [ \-\fITAB1\fR[\fB,\fITAB2... ]
.RB [ "\-t \fITAB1\fR[\fB,\fITAB2..." ]
.RB [ \-\-initial ]
.RB [ \-\-tabs=\fITAB1\fR[\fB,\fITAB2... ]
.RI [ FILE... ]

.BR expand " [" \-\-help "] [" \-\-version ]
.SH 説明
.B expand
は指定された
.I FILE
の内容を標準出力に書き込む。
その際、タブ文字を適当な数のスペースに置き換える。
.I FILE
が 1 つも与えられないと標準入力から読み込む。また
.I FILE
が
.RB ` \- '
だった場合には、そのファイルには標準入力が用いられる。

デフォルトでは
.B expand
はすべてのタブをスペースに変換する。バックスペース文字は出力に保存され、
タブの計算における桁数を減らす作用をもたらす。デフォルトの動作は `-t 8'
が指定された場合と同じ (タブを 8 桁おきに設定する)。
.SH オプション
.TP
.B \-\fITAB1\fR[\fB,\fITAB2...\fR]\fB, \-t \fITAB1\fR[\fB,\fITAB2...\fR]\fB, \-\-tabs=\fITAB1\fR[\fB,\fITAB2...\fR]
タブストップが 1 つだけ与えられた場合には、
タブを \fITAB1\fP おきに設定する (デフォルトは 8)。
その他の場合は、タブを \fITAB1\fP 桁、
\fITAB2\fP 桁... に設定し (桁数は 0 から数え始める)、
与えられた数以降のタブはスペース文字 1 つに置き換える。タブストップを
.B \-\-tabs
オプションで指定する際には、それぞれの間は空白またはコンマで区切る。
短縮形式 \fB\-\fITAB...\fR は推奨されない。
.TP
.B \-i, \-\-initial
それぞれの行の先頭タブ (initial tabs) のみをスペースに変換する。
「先頭タブ」とは、行先頭から続くタブ文字の集まりのこと。
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-textutils@gnu.org に報告してください。
.br
man ページは Ragnar Hojland Espinosa
<ragnar@ragnar-hojland.com> が作成しました。
