.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU factor man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH factor 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
factor \- 数値を素因数分解して素数の約数を表示する
.SH 書式
.B factor
.RI [ NUMBER... ]
.sp
.BR "factor ["\-\-help "] ["\-\-version ]
.SH 説明
.B factor
は与えられた
.I NUMBER
を分解して、素因数を昇順に並べて表示する。
何も指定しなければ標準入力から数値リストを読み込む。
数値の区切りは改行・タブ・スペースである。

.B factor
は 128 個までの数値にしか分解できない。また
アーキテクチャの最大の unsigned integer
(通常 32 ビットプラットフォームでは 4294967295、
64 ビットプラットフォームでは 18446744073709551615)
または 2^128 の小さいほうまでしか扱えない。
.SH オプション
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
