.\" Copyright (c) 1998 Andries Brouwer
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\" 
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Mon 6 Dec 1999 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH hman 1 "19 January 1998"
.LO 1
.SH 名前
hman \- オンラインマニュアルページをブラウズする
.SH 書式
.B hman
[ -P \fIbrowser\fP ] [ -H \fIhost\fP ] [ \fIsection\fP ] \fIname\fP
.br
.B hman
[ -P \fIbrowser\fP ] [ -H \fIhost\fP ] [ \fIsection\fP ] [ index ]
.SH 説明
.B hman
スクリプトは
.BR man2html (1)
に対するインターフェースで、これを用いると
man ページをコマンドラインから要求し、
好みのブラウザで出力を見ることができるようになる。
振る舞いは
.BR man (1)
と似ているので、
.B hman
を
.B man
の別名にすることも可能だろう。
ブラウザに netscape を用い、既に netscape のプロセスが
起動していた場合には、
.B hman
は要求を既に存在しているブラウザに渡す。

.SH オプション
.TP
.B \-\^P " browser"
どのブラウザを用いるかを指定する (lynx, xmosaic, arena, chimera,
netscape, amaya, ... など)。
このオプションは環境変数
.B MANHTMLPAGER
より優先される。
デフォルトは
.B lynx
の non-httpd バージョンである。
.TP
.B \-\^H " host"
どのホストから man ページを取得するかを設定する。
このオプションは環境変数
.B MANHTMLHOST
より優先される。
デフォルトは
.BR localhost 。

.SH 環境変数
.TP
MANHTMLPAGER
この環境変数を使うとデフォルトで用いるブラウザを選択できる。
.TP
MANHTMLHOST
この環境変数を使うとデフォルトで用いるホストを選択できる。
.SH 関連項目
.BR man (1),
.BR man2html (1),
.BR arena (1),
.BR lynx (1),
.BR netscape (1),
.BR xmosaic (1),
.BR glimpse (1)

http://www.mcom.com/newsref/std/x-remote.html
