.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU hostid man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2003 Yuichi SATO
.\"         all rights reserved.
.\" Translated Mon Mar 24 02:44:40 JST 2003
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH hostid 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
hostid \- ホストの識別値を表示する
.SH 書式
.B hostid [\-\-help] [\-\-version]
.SH 説明
.B hostid
はホストの識別値を表示する。
.SH オプション
.B "\-\-help"
使用法のメッセージを標準出力に表示し、正常に終了する。
.TP
.B "\-\-version"
バージョン情報を標準出力に表示し、正常に終了する。
.SH 注意
バグは bug-sh-utils@gnu.org へ報告してください。
このページは Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が更新した。
