.\" This page is originally in the SysVinit package.
.\" Translated Fri 14 Feb 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Tue  2 May 2000 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Thu 26 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.\"{{{}}}
.\"{{{  Title
.TH MESG 1 "Feb 26, 2001" "" "Linux User's Manual"
.\"}}}
.\"{{{  Name
.SH 名前
mesg \- 使用中の端末への書き込み許可属性を制御する
.\"}}}
.\"{{{  Synopsis
.SH 書式
.B mesg
.RB [ y | n ]
.\"}}}
.\"{{{  Description
.SH 説明
.B mesg
は現在使用している端末への他の人からのアクセスを制御する。
通常は自分の使っている端末への他のユーザからの書き込みを
許可・禁止するために用いられる (\fBwrite\fP(1) 参照)。
.\"}}}
.\"{{{  Options
.SH オプション
.IP \fBy\fP
端末への書き込みアクセスを許可する。
.IP \fBn\fP
端末への書き込みアクセスを禁止する。
.PP
オプションが与えられなかった場合は、現在のアクセス許可状態を表示する。
.SH 注意
.B mesg
は標準入力が端末に接続されていると仮定している。
これを利用して、複数回ログインしている場合に、
リダイレクションを用いて他の端末の
mesg の状態を取得・設定することもできる。
例えば "mesg n < /dev/pts/46" とすればよい。
.SH 著者
Miquel van Smoorenburg (miquels@cistron.nl)
.\"}}}
.\"{{{  See also
.SH 関連項目
.BR talk (1),
.BR write (1),
.BR wall (1)
.\"}}}
