.\" Copyright (c) 2003 Theodore Ts'o
.\"
.\" Japanese Version Copyright (c) 2004 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Mar  7 00:39:45 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH MK_CMDS 1 "2003" E2FSPROGS
.SH 名前
mk_cmds \- エラーテーブルコンパイラ
.SH 書式
.B mk_cmds
file
.SH 説明
.B mk_cmds
は、コマンド名とそれに関連するヘルプメッセージを列挙したテーブルを、
.IR ss (3)
ライブラリと共に使用するのに適した、C のソースファイルに変換する。

ソースファイルの名前はサフィックス ``.ct'' で終っていなければならない。
ファイルはコマンドラインテーブルの名前を与える宣言で構成される。

.B command_table
.I name

の後に

[
.B request
|
.B unimplemented
] 
.I name,
"
.I string
"[, abbrev]...;

という形式のエントリが続き、テーブルの終りを示す

.B end

で終る。

C のソースファイルが生成されるので、コンパイルして、
ss ライブラリを使うオブジェクトファイルとリンクする。

ソースファイル中の ``#'' はコメント文字として扱われ、
ソースファイルの行末までの残りの文字列は無視される。

.SH バグ

オリジナルの
.B mk_cmds
は
.IR yacc (1)
に基づくとても簡単なパーサを使っており、
現在のバージョンの
.B mk_cmds
は awk と sed を組み合わせたスクリプトを使っているので、
エラーからの回復についてはまだ十分とは言えない。

.SH 関連項目
ss (3)
