.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Mar 10 00:31:08 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH NBP 1 "17 Dec 1991" "netatalk 1.2"
.SH 名前
nbplkup, nbprgstr, nbpunrgstr \- NBP データベースへアクセスする
.SH 書式
.B nbplkup
[
.B -r
.I nresp
]
[
.I nbpname
]
.sp
.B nbprgstr
[
.B -p
.I port
]
.I nbpname
.sp
.B nbpunrgstr
.I nbpname
.SH 説明
.B nbprgstr
は指定された
.IR port
の
.BR atalkd (8)
に
.I nbpname
を登録する。
.B nbpunrgstr
は
.B atalkd
に対して、
.I nbpname
をそれ以降広報しないように通知する。
.LP
.B nbplkup
は AppleTalk インターネットに登録されている最大
.I nresp
個 (デフォルトは 1000 個) のエントリを表示する。
.I nbpname
は
.BR nbp_name (3)
によって解釈される。
.I object
や
.I type
の指定で使われる
.RB ` = '
は全てにマッチする。
.I zone
の指定で使われる
.RB ` * '
はローカルゾーンを意味する。
デフォルトの値は環境変数
.B NBPLKUP
から取得され、
.IR nbpname
として解釈される。
.SH 例
ローカルゾーン内の type が
.B LaserWriter
である全てのデバイスを探す。
.sp
.RS
.nf
example% nbplkup :LaserWriter
               Petoskey:LaserWriter        7942.129:218
             Gloucester:LaserWriter        8200.188:186
                 Rahway:LaserWriter        7942.2:138
             517 Center:LaserWriter        7942.2:132
                  ionia:LaserWriter        7942.2:136
     Evil DEC from Hell:LaserWriter        7942.2:130
              Hamtramck:LaserWriter        7942.2:134
         Iron Mountain :LaserWriter        7942.128:250
example%
.fi
.RE
.SH 関連項目
.BR nbp_name (3),
.\" .BR nbp (4),
.\" .BR zip (4),
.BR atalkd (8).
