'\" t
.\" (The preceding line is a note to broken versions of man to tell
.\" them to pre-process this man page with tbl)
.\" Man page for pmap.
.\" Licensed under version 2 of the GNU General Public License.
.\" Written by Albert Cahalan.
.\"
.\" Japanese Version Copyright (c) 2005 Yuichi SATO
.\"         all rights reserved.
.\" Translated Thu Nov  3 06:57:02 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.\"WORD:	quiet	寡黙な
.\"
.TH PMAP 1 "October 26, 2002" "Linux" "Linux User's Manual"
.SH 名前
pmap \- プロセスのメモリマップを表示する

.SH 書式
.nf
pmap [ -x | -d ] [ -q ] pids...
pmap -V
.fi

.SH 説明
pmap コマンドはプロセス (群) のメモリマップを表示する。

.SH 一般のオプション
.TS
l l l.
-x	拡張モード	拡張フォーマットで表示する。
-d	デバイスモード	デバイスフォーマットで表示する。
-q	寡黙モード	ヘッダ・フッタ行を表示しない。
-V	バージョン表示	プログラムのバージョンを表示する。
.TE

.SH 関連項目
ps(1) pgrep(1)

.SH 準拠
対応する標準はないが、SunOS の pmap コマンドに非常に似ている。

.SH 著者
Albert Cahalan <albert@users.sf.net> が 2002 年に pmap を書き、
procps コレクションの現在のメンテナである。
バグ報告は <procps-feedback@lists.sf.net> まで送って欲しい。
