.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU printenv man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.TH printenv 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
printenv \- 環境の全部あるいは一部を表示する
.SH 書式
.B printenv
.BI [ variable... ]
.sp
.B printenv [\-\-help] [\-\-version]
.SH 説明
もし引き数
.I variable
がひとつも与えられなかった場合には、
.B printenv
はすべての環境変数を表示する。
ひとつ以上の変数名が与えられた場合には、
それぞれの変数について、設定されていればその設定値を表示する。
設定されていなければ何も表示しない。
.PP
終了ステータスは以下の通り:
.nf
0 指定した変数すべてが見付かった
1 指定した変数のうち、少なくとも一つが見付からなかった
2 書き込みエラーが起こった
.fi
.SH オプション
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
