.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Mon Mar  5 22:52:56 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH PSORDER 1 "17 Dec 1991" "netatalk 1.2"
.SH 名前
psorder \- PostScript のページ順を変更するフィルタ
.SH 書式
.B psorder
[
.B -duf
]
.I sourcefile
.SH 説明
.B psorder
は PostScript 文書のページを並べ変えるフィルタである。
結果は標準出力に書き出される。
デフォルトでは、文書は昇順に処理される
(番号の小さいページが先に印刷される)。
PostScript 文書の中には、
ページの順番を変更できないように指定してあるものが存在する;
.B psorder
のデフォルトの動作は、この仕様に従う。
.LP
変換元ファイルが指定されない場合、または
.I sourcefile
が
.RB ` - '
である場合、
.B psorder
は標準入力ファイルを読み込む。
.br
.SH オプション
.TP
.B \-d
文書のページを下方順もしくは降順に並べ変える。
このオプションは、Apple LaserWriter や LaserWriter Plus のように
表を上にして重ねるプリンタで文書を印刷する場合に、
文書のページを並べ変えるためによく使われる。
.TP
.B \-u
昇順を指定する。これがデフォルトである。
表を下にして重ねるプリンタで文書を印刷する場合に、
正しい順番になっているように並べ直し、それを保証するために使われる。
.TP
.B \-f
文書がページの順番を厳密に扱わなくてはならないと警告を出す場合でも、
.B psorder
に強制的にページを並べ変えさせる。
文書が正しく印刷されなくなるかもしれないので、
このオプションは実験的にのみ使うべきである。
.SH 関連項目
.BR psf (8),
.BR lpr (1).
