.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU pwd man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.TH pwd 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
pwd \- 現在のディレクトリ (ワーキングディレクトリ) の名前を表示する
.SH 書式
.B pwd
.sp
.B pwd [\-\-help] [\-\-version]
.SH 説明
.B pwd
はカレントディレクトリの名前を完全に展開してから表示する。
つまり表示された名前における各部分はすべて実際のディレクトリ名であり、
シンボリックリンクではない。
.PP
Unix のほとんどのシェルには同名の組み込みコマンドがあるので、
単に `pwd' として実行すると、
ここで記述されたものとは異なった機能のものが実行されるだろう。
.SH オプション
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
