.\" Japanese Version Copyright (c) 1997 FURUSAWA,Kazuhisa
.\"         all rights reserved.
.\" Translated Tue Jan 21 19:01:39 JST 1997
.\"         by FURUSAWA,Kazuhisa <furusawa@com.cs.osakafu-u.ac.jp>
.\" Updated Sat Feb  2 06:17:06 JST 2000
.\"         by Kentaro Shirakata <argrath@yo.rim.or.jp>
.TH RDATE 1 3/24/85
.CM 1
.SH 名前
rdate \- ネットワーク経由で日付と時刻を得る
.SH 書式
.B rdate
[\-p] [\-s] [\-u] [host...]
.SH 説明
.B rdate
は RFC 868 に記述されているプロトコルを用い、TCP か UDP を使って他のマシンの
現在の時刻を得る。それぞれのシステムの時刻は ctime(3) 形式で表示する。
以下に例を示す:
.nf
.IP ""
% rdate uci mc
[uci]   Sun Mar 24 20:35:41 1985
[mc]    Sun Mar 24 20:36:19 1985
.fi
.SS オプション
.TP
.I \-p
リモートマシンから得た時刻を表示する。これがデフォルトのモードである。
.TP
.I \-s
ローカルシステムの時刻をリモートマシンから得たものに合わせる。
当然ながら、root が用いた場合のみ効果がある。
.TP
.I \-u
時刻を得るのに TCP の代わりに UDP を用いる。
5 秒以内に応答がなかった場合は時間切れとして扱う。
.SH ファイル
.nf
/etc/services	サービス名をソケット番号に対応付ける
/etc/hosts	ホスト名をインターネットアドレスに対応付ける
.fi
.SH 履歴
.TP
24-Mar-85  Rochester 大学の Lee Moore
作成。
.TP
10-Oct-94  Andy Tefft <teffta@crypt.erie.ge.com>
Linux 1.1.52 用にアップグレード。root が実行した時はシステムの
時刻を設定する様に変更。
.TP
23-Sep-96  Richard Henderson <rth@tamu.edu>
32 bit と仮定していたのを修正し、モードオプションを追加。
.TP
04-May-99  Ken Yap <ken.yap@acm.org>
UDP を使うコードを追加。
.SH バグ
UDP での時間切れの処理は 2 つめ以降のサーバーには動作しない。
signal(2) の動作に何か関係があるのかも知れないが、
筆者は理解していない。
