.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Sat 23 Oct 1999 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH RESET 1 "10 October 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 名前
reset \- 端末をリセットする
.SH 書式
.BR reset
.SH 説明
.B reset
は
.BR tput (1)
を
.IR clear , rmacs , rmm , rmul , rs1 , rs2 , rs3
引数を付けて呼ぶ。すると
.B tput
は、現在の端末に適合したリセット文字列を送る。
文字列の情報は、 GNU または BSD \fBtput\fR では
.I /etc/termcap
から取得され、 \fBncurses\fR の \fBtput\fR では
.I /etc/terminfo
から取得される。
この文字列シーケンスで、
「妙な」文字を表示しはじめた
Linux 仮想コンソールをリセットするには充分なようである。
端末を cooked モード (加工モード) に戻そうとする試みにおいては、
うまくいっているかどうかを確認するため、
.BR stty (1)
が引数
.I sane
とともに呼び出される。
.SH 関連項目
.BR clear (1),
.BR stty (1),
.BR tput (1)
.SH 著者
Rik Faith (faith@cs.unc.edu)
