.\" Copyright (c) 1983, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)rwall.1	6.7 (Berkeley) 4/23/91
.\"	$Id: rwall.1,v 1.11 2000/07/30 23:57:05 dholland Exp $
.\"
.\" Japanese Version Copyright (c) 2000 Yuichi SATO
.\"         all rights reserved.
.\" Translated Tue Jan 11 JST 1994
.\"         by NetBSD jman proj. <jman@spa.is.uec.ac.jp> 
.\" Updated and Modified Thu Nov  2 18:23:49 JST 2000
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.Dd August 15, 1999
.Dt RWALL 1
.Os "Linux NetKit (0.17)"
.Sh 名前
.Nm rwall
.Nd ホストにログインしているユーザーにメッセージを送る
.Sh 書式
.Nm rwall
.Ar host
.Op Ar file
.Sh 説明
.Nm rwall
は、指定したホストにログインしているユーザーにメッセージを送信する。
送信するメッセージは、端末から入力されて EOF で終了しているか、
.Ar file
に記録されているものである。
.Sh 返り値
.Bl -tag -width indent
.It rwall: RPC: Program not registered
.Xr rpc.rwalld 8
デーモンがリモートホスト上で起動していない。
.It rwall: RPC: Timed out
通信エラーが発生した。ネットワークが非常に混雑している。もしくは、
.Xr rpc.rwall 8
デーモンがリモートホスト上で終了させられた。
.It rwall: RPC: Port mapper failure - RPC: Timed out
リモートホストが portmapper 
.Ns ( Xr portmap 8
を参照) を実行しておらず、RPC を用いたサービスを提供していない。
ホストがダウンしている可能性がある。
.El
.Sh 関連項目
.Xr wall 1 ,
.Xr portmap 8 ,
.Xr rpc.rwalld 8
.Sh 履歴
.Nm rwall
コマンドは
.Tn SunOS
で登場した。
