.\" Copyright (c) 1991 Free Software Foundation
.\" See section COPYING for conditions for redistribution
.\"
.\" Japanese Version Copyright (c) 1997 NAKANO Takeo all rights reserved.
.\" Translated Sat Dec 20 1997 by NAKANO Takeo <nakano@@apm.seikei.ac.jp>
.\"
.TH size 1 "5 November 1991" "cygnus support" "GNU Development Tools"
.de BP
.sp
.ti \-.2i
\(**
..

.SH 名前
size \- セクションの大きさとその合計をリストする

.SH 書式
.hy 0
.na
.TP
.B size
.RB "[\|" \-A \||\| \-B \||\| \c
.BI "\-\-format=" compatibility\c
\&\|]
.RB "[\|" \-\-help "\|]"
.RB "[\|" \-d \||\| \-o \||\| \-x\c
\||\|\c
.BI "\-\-radix=" number\c
\&\|]
.RB "[\|" \c
.BI "\-\-target=" bfdname\c
\&\|]
.RB "[\|" \-V \||\| \-\-version "\|]"
.I objfile\c
\&.\|.\|.
.ad b
.hy 1
.SH 説明
GNU
.B size
ユーティリティは
.I objfile
引数に与えられたオブジェクトファイルそれぞれに対して、セクションのサイ
ズとその合計をリストする。デフォルトではオブジェクトファイルひとつ（書
庫が指定された場合はそれぞれのメンバー) について一行の出力を生成する。

.SH オプション
.TP
.B \-A
.TP
.B \-B
.TP
.BI "\-\-format " "compatibility"
これらのうちのどれかのオプションを指定すると、 GNU
.B size
の出力形式を選択することができる。 System V 形式にするには
\fB\-A\fP または \fB\-\-format=sysv\fP、 Berkeley 形式にするには
\fB\-B\fP または \fB\-\-format=berkeley\fP を指定する。
デフォルトは Berkeley 形式に似た一行出力である。
 
.TP
.B \-\-help
指定可能な引数とオプションの要約を表示する。

.TP
.B \-d
.TP
.B \-o
.TP
.B \-x
.TP
.BI "\-\-radix " "number"
これらのオプションのどれかを指定すると、各セクションのサイズを表す数値
の基数を変更できる。
10 進数なら \fB\-d\fP または \fB\-\-radix 10\fP、
8 進数なら \fB\-o\fP または \fB\-\-radix 8\fP、
16 進数なら \fB\-x\fP または \fB\-\-radix 16\fP である。
.B \-\-radix
.I number
形式で指定できるのは、以上の数値 (8, 10, 16) に限られる。
サイズの合計は常に 2 種類の基数で表示される。
\fB\-d\fP か \fB\-x\fP を指定した場合は 10 進と 16 進、
\fB\-o\fP を指定した場合は 8 進と 16 進となる。

.TP
.BI "\-\-target " "bfdname"
.I objfile
のオブジェクトフォーマットを
.I bfdname
として指定できる。このオプションはおそらく不要である。
.B size
は多数のフォーマットを自動的に認識する。指定可能なフォーマットを知るた
めの方法に関しては
.BR objdump ( 1 )
を見よ。

.TP
.B \-V
.TP
.B \-\-version
.B size
自身のバージョン番号に関する情報を表示する。

.SH 関連項目
.B info
の `\fB binutils \fP' エントリ、
.IR "The GNU Binary Utilities" ,
Roland H. Pesch (October 1991)、
.BR ar "(" 1 ")、"
.BR objdump "(" 1 ")"

.SH 著作権
Copyright (c) 1991 Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
