'\" t
.\" (The preceding line is a note to broken versions of man to tell
.\" them to pre-process this man page with tbl)
.\" Man page for skill and snice.
.\" Licensed under version 2 of the GNU General Public License.
.\" Written by Albert Cahalan, converted to a man page by
.\" Michael K. Johnson
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Tue Nov 14 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Fri Jul 15 02:16:51 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH SKILL 1 "March 12, 1999" "Linux" "Linux User's Manual"
.SH 名前
skill, snice \- プロセスにシグナルを送る / プロセスの優先度を変更する

.SH 書式
.nf
skill [signal to send] [options] process selection criteria
snice [new priority] [options] process selection criteria
.fi

.SH 説明
skill のデフォルトのシグナルは TERM である。
-l や -L を用いると、指定できるシグナルをリストできる。
特に便利なシグナルには HUP, INT, KILL, STOP, CONT, 0 などがある。
デフォルト以外のシグナルの指定方法は 3 つある。 -9 -SIGKILL -KILL。

snice のデフォルトの優先度は +4 である (snice +4 ...)。
優先度の番号は +20 (最も遅い) から -20 (最も速い) までである。
負の優先度の数値は管理権限のあるメンバーしか指定できない。

.SH 一般のオプション
.TS
l l l.
-f	高速モード	今のところあまり効果がない
-i	対話モード	T{
各アクションの前に確認を求める
T}
-v	詳細表示モード	T{
選択されたプロセスに関する情報を表示する
T}
-w	警告を有効にする	今のところあまり効果がない
-n	非実行モード	プロセス ID の表示だけを行う
-V	バージョン表示	プログラムのバージョンを表示する
.TE

.SH プロセス選択オプション
プロセス選択基準 (process selection criteria) は、
端末・ユーザー名・プロセスID・コマンド名のいずれかである。
以下のオプションを指定すると、解釈方法を明示できる。
このおもしろいインタフェースについては Albert を責めないで欲しい。
.TS
l l.
-t	次の引数は端末である (tty または pty)
-u	次の引数はユーザー名である
-p	次の引数はプロセス ID 番号である
-c	次の引数はコマンド名である
.TE

.SH シグナル
以下に skill で使える可能性のあるシグナルのリストを示す。
わかるものについては番号とデフォルトの動作も示す。
.TS
lB rB lB lB
lfCW r l l.
名前	番号	アクション	説明
.TH
0	0	n/a	シグナルを送った場合の終了コードを取得する
ALRM	14	exit
HUP	1	exit
INT	2	exit
KILL	9	exit	このシグナルはブロックされない
PIPE	13	exit
POLL		exit
PROF		exit
TERM	15	exit
USR1		exit
USR2		exit
VTALRM		exit
STKFLT		exit	実装されていないかもしれない
PWR		ignore	T{
システムによっては終了 (exit) するかもしれない
T}
WINCH		ignore
CHLD		ignore
URG		ignore
TSTP		stop	シェルと相互作用するかもしれない
TTIN		stop	シェルと相互作用するかもしれない
TTOU		stop	シェルと相互作用するかもしれない
STOP		stop	このシグナルはブロックされない
CONT		restart	停止 (stop) 状態なら再開、その他なら無視
ABRT	6	core
FPE	8	core
ILL	4	core
QUIT	3	core
SEGV	11	core
TRAP	5	core
SYS		core	実装されていないかもしれない
EMT		core	実装されていないかもしれない
BUS		core	コアダンプは失敗するかもしれない
XCPU		core	コアダンプは失敗するかもしれない
XFSZ		core	コアダンプは失敗するかもしれない
.TE

.SH 例
.TS
lB lB
lfCW l.
コマンド	説明
.TC
snice seti crack +7	seti と crack の速度を落とす
skill -KILL -v /dev/pts/*	T{
新スタイルの PTY デバイスのユーザーを kill する
T}
skill -STOP viro lm davem	3 人のユーザーを stop する
snice -17 root bash	root のシェルを優先する
.TE

.SH 関連項目
.BR killall (1),
.BR pkill (1),
.BR kill (1),
.BR renice (1),
.BR nice (1),
.BR signal (7),
.BR kill (2)

.SH 準拠
対応する標準はない。

.SH 著者
Albert Cahalan <albert@users.sf.net> が 1999 年に
non-free 版の代わりとして skill と snice を書き、
procps コレクションの現在のメンテナである。
バグ報告は <procps-feedback@lists.sf.net> まで送って欲しい。
