.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU sleep man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Sat Jan 24 17:50:05 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\" 
.TH sleep 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
sleep \- 指定した時間だけ遅延する
.SH 書式
.BI "sleep [" number [smhd] ... ]
.sp
.B sleep [\-\-help] [\-\-version]
.SH 説明
.B sleep
はコマンドラインで指定した引数の値を足した時間の分だけ停止して待つ。
引数は数値で、あとに単位を続けることもできる。デフォルトは秒。
単位は以下の通り:
.IP \fBs\fP
秒
.IP \fBm\fP
分
.IP \fBh\fP
時間
.IP \fBd\fP
日
.PP
.B sleep
はサスペンド中もカウントを続け、
フォアグラウンドに来たときに時間が残っている場合は、再び停止して待つ。

.SH オプション
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa
<ragnar@ragnar-hojland.com> が行っています。
