.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Thu Mar 15 17:05:39 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH SNMPDF 1 "02 Feb 2000"
.UC 4
.SH 名前
snmpdf - SNMP を経由してリモートマシンのディスク使用量の一覧を取得する
.SH 書式
snmpdf [ common arguments ] [-Cu] hostname
.SH 説明
snmpdf は典型的な df コマンドの単純なネットワーク化バージョンである。
このコマンドは、
HOST-RESOURCES-MIB の hrStorageTable または UCD-SNMP-MIB の dskTable を
調べて、リモートマシンのディスク使用量をチェックする。
デフォルトでは、一般により多くの情報が含まれる
hrStorageTable が優先的に選ばれる。
しかし、-Cu 引き数を snmpdf に渡して、
強制的に dskTable を使わせることもできる。
.PP
snmpd.conf ファイルで
.I disk
ディレクティブを使って dskTable を設定するには、
man ページ
.I snmpd.conf(5)
を参照すること。
.SH 関連項目
snmpd.conf(5), snmp.conf(5)
