.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU uname man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.TH uname 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
uname \- システムの情報を表示する
.SH 書式
.B uname
.B [\-snrvma] [\-\-sysname] [\-\-nodename] [\-\-release]
.B [\-\-machine] [\-\-all]
.sp
.B uname [\-\-help] [\-\-version]
.SH 説明
.B uname
は起動されたマシンと OS に関する情報を出力する。
オプションが指定されなかった場合には、
.B uname
は
.I \-s
オプションが指定されたかのように動作する。
複数のオプションが指定されたり、
.I \-a
オプションが指定された場合には、
選択された情報は `snrvm' の順に空白で区切られて出力される。
.SH オプション
.TP
.B "\-m, \-\-machine"
マシン (ハードウェア) のタイプを表示する。
.TP
.B "\-n, \-\-nodename"
マシンのネットワークノードのホスト名を表示する。
.TP
.B "\-r, \-\-release"
OS のリリースを表示する。
.TP
.B "\-s, \-\-sysname"
OS の名称を表示する。
.TP
.B "\-v"
OS のバージョンを表示する。
.TP
.B "\-a, \-\-all"
以上の情報すべてを表示する。
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
