.\" This page is originally in the SysVinit package.
.\" Translated Fri 14 Feb 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Fri 27 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.TH WALL 1 "12 September 2000" "" "Linux User's Manual"
.SH 名前
wall \- 全員の端末にメッセージを送る。
.SH 書式
.B wall
.RB [ " message " ]
.SH 説明
.B wall
は \fImesg\fP(1) 許可属性を \fByes\fP に設定している
ログインユーザ全員にメッセージを送る。
メッセージは \fIwall\fP 起動時の引数として与えることも、
また \fIwall\fP の標準入力に送ることもできる。
端末から標準入力にメッセージを入力する場合は、
\fBEOF\fP キー (通常 Control-D)
によってメッセージを終了させなくてはならない。
.PP
メッセージの長さは 20 行までに制限されている。
.SH 注意
文書化されていない (し今後書く予定もない...) オプション
"-n" があり、これは
.B wall
が表示するバナーを抑制する。
これは
.BR walld (8)
から利用するためのものである。
.B wall
が sgid でインストールされていて、実行したのが root 以外だった場合は、
このフラグは利用できない。
.PP
.B wall
は、実行されるごとに syslog に通知を行う。
facility には LOG_USER が、レベルには LOG_INFO がそれぞれ用いられる。
.SH 環境変数
.B wall
は
.B TZ
環境変数を無視する。
バナーに表示する時刻はシステムのローカル時刻に基づいて決まる。
.SH 関連項目
mesg(1),
rpc.rwalld(8)
.SH 著者
Miquel van Smoorenburg, miquels@cistron.nl
