.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"     Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Sat Jul 24 17:06:03 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Japanese Version Copyright (c) 1997 Ueyama Rui
.\"         all rights reserved.
.\" Translated 1997-08-30, Ueyama Rui <rui@campus.or.jp>
.\" Modified 2005-02-20, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH GROUP 5 2009-10-17 "Linux" "Linux Programmer's Manual"
.SH 名前
group \- ユーザーグループのファイル
.SH 説明
\fI/etc/group\fP は、そのシステムのグループを定義するテキストファイルである。
1 行に 1 エントリで、各行の形式は以下のとおりである。
.sp
.RS
group_name:password:GID:user_list
.RE
.sp
フィールドの説明:
.IP group_name
グループの名前。
.IP password
(暗号化された) パスワード。このフィールドが空ならパスワードは必要ない。
.IP GID
グループIDの数値。
.IP user_list
このグループのメンバーのユーザー名のリスト。
ユーザー名はコンマで区切られる。
.SH ファイル
/etc/group
.SH バグ
4.2BSD の
.BR initgroups (3)
には次のように書かれている:
誰も
.I /etc/group
を最新の状態に保ってはいないようである。
.SH 関連項目
.BR login (1),
.BR newgrp (1),
.BR getgrent (3),
.BR getgrnam (3),
.BR passwd (5)
