.\" This page is originally in the SysVinit package.
.\"
.\" Translated Sat 22 Feb 1997 by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Tue  2 May 2000 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH INITSCRIPT 5 "December 24, 1999" "" "Linux System Administrator's Manual"
.SH 名前
initscript \- inittabファイル中のコマンドを実行するスクリプト
.SH 書式
/bin/sh /etc/initscript id runlevels action process
.SH 概要
\fBinit\fPは、
シェルスクリプト\fI/etc/initscript\fPが存在する場合は、
それを用いて\fIinittab\fPの中のコマンドを実行する。
このスクリプトを用いて全プロセスに対する\fBulimit\fPや
\fBumask\fPのデフォルト値等を設定することが出来る。
.SH 例
以下は initscript の例である。あなたのシステムに
\fI/etc/initscript.sample\fPとしてインストールされている可能性もある。
.RS
.sp
.nf
.ne 7

#
# initscript   init(8) が生み出す全てのプログラムに対して
#              以下のように実行される :
#
#              /bin/sh /etc/initscript <id> <level> <action> <process>
#

  # umaskを安全なレベルに設定し、コアダンプ可能にする。
  umask 022
  ulimit -c 2097151
  PATH=/bin:/sbin:/usr/bin:/usr/sbin
  export PATH

  # 全てのプロセスに対するファイルディスクプリタの hard limit を
  # 8192 に設定する。soft limit は 1024 のままだが、何の権限も
  # 持たないプロセスでも "ulimit -Sn xxx" とすることで soft limit を
  # hard limit まで増やすことができる。(2.2.13 以降の Linux kernel が
  # 必要)
  ulimit -Hn 8192

  # プログラム本体を実行する。
  eval exec "$4"

.sp
.RE
.SH ファイル
/etc/inittab,
/etc/initscript.
.SH 著者
Miquel van Smoorenburg ,<miquels@drinkel.ow.org>
.SH 関連項目
.BR init (8),
.BR inittab (5)

