.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"     Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Sat Jul 24 17:06:52 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Jan 14 00:34:09 1996 by Andries Brouwer (aeb@cwi.nl)
.\"
.\" Japanese Version Copyright (c) 1998 NAKANO Takeo all rights reserved.
.\" Translated Tue 13 Oct 1998 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH INTRO 5 2007-10-23 "Linux" "Linux Programmer's Manual"
.SH 名前
intro \- ファイルフォーマットの紹介
.SH 説明
マニュアルの 5 章は、各種のファイルフォーマット、プロトコル、
(もしあれば) 対応する C の構造体について記載している。
.SH 備考
.SS 著者と著作権
著作者と権利条件に関しては、マニュアルページのソースのヘッダを見よ。
これらはページごとに異なる場合があるので注意すること。
.SH 関連項目
.BR standards (7)
