.\" Copyright (c) 1994 Peter Tobias <tobias@server.et-inf.fho-emden.de>
.\" This file may be distributed under the GNU General Public License.
.\" 
.\" Changed to -mdoc by David A. Holland <dholland@ftp.uk.linux.org>
.\" in order to work better with some NetKit maintenance scripts.
.\"
.\" Japanese Version Copyright (c) 2000 Yuichi SATO
.\"         all rights reserved.
.\" Translated Thu Dec 14 18:22:51 JST 2000
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.\"WORD:	identification	識別
.\"
.Dd May 22, 1994
.Dt ISSUE.NET 5 
.Os "Linux NetKit (0.17)"
.Sh 名前
.Nm issue.net 
.Nd telnet セッションのための識別ファイル
.Sh 説明
ファイル
.Pa /etc/issue.net
は、telnet セッションのログインプロンプトの前に表示される、
メッセージとシステム識別情報が含まれたテキストファイルである。
このファイルには、様々な `%-char' というシーケンスを書くことができる。
.Ic telnetd
では、以下のシーケンスがサポートされている:
.Bl -tag -offset indent -compact -width "abcde"
.It %t
- 現在の tty (端末名) を表示する
.It %h
- システムのノード名 (FQDN) を表示する
.It %D
- NIS ドメイン名を表示する
.It %d
- 現在の時刻と日付を表示する
.It %s
- オペレーティングシステムの名前を表示する
.It %m
- マシン (ハードウェア) タイプを表示する
.It %r
- オペレーティングシステムのリリースを表示する
.It %v
- オペレーティングシステムのバージョンを表示する
.It %%
- 1 個の '%' 文字を表示する
.El
.Sh ファイル
.Pa /etc/issue.net
.Sh 関連項目
.Xr telnetd 8
