.\" Hey Emacs, this is -*- nroff -*-
.\"
.\" This file is part of locale(1) which displays the settings of the
.\" current locale.
.\" Copyright (C) 1994  Jochen Hein (Hein@Student.TU-Clausthal.de)
.\" Copyright (C) 2008  Petr Baudis (pasky@suse.cz)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" 2008-06-17 Petr Baudis <pasky@suse.cz>
.\"     LC_TIME: Describe first_weekday and first_workday
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated 1998-02-11, HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Updated & Modified 2001-10-18, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2008-08-11, Akihiro MOTOKI, LDP v3.05
.\"
.TH LOCALE 5 2008-06-17 "Linux" "Linux User Manual"
.SH 名前
locale \- ロケール定義ファイル
.SH 説明
.B "ロケール (locale)"
定義ファイルは
.BR localedef (1)
コマンドがバイナリのロケール・データベースに変換するのに
必要な全ての情報を含んでいる。

定義ファイルは、いくつかのセクションから構成されており、各セクション
にはロケールのカテゴリが詳細に記述される。

.SS 文法
ロケール定義ファイルは以下のキーワードから構成されるヘッダーで始まる:
.TP
.I <escape_char>
ファイルの残りの部分でエスケープ・キャラクターとして使用する文字を
指定する。これは特殊な意味に解釈される文字をエスケープするのに使用する。
デフォルトはバックスラッシュ (\\) である。
.TP
.I <comment_char>
ファイルの残りの部分でコメント・キャラクターとして使用する文字
を指定する。デフォルトではシャープ (#) である。
.PP
ロケールの定義はロケールのカテゴリ毎の定義を行う部分から構成される。
各部分は、定義済みの他のロケールのコピーを元に定義することもできるし、
最初から定義することもできる。カテゴリをコピーする場合、定義の中に
.B copy
というキーワードに続けてコピーするロケールの名前を書く。
.\" FIXME glibc 2.2.2 added new nonstandard locale categories:
.\" LC_ADDRESS, LC_IDENTIFICATION, LC_MEASUREMENT, LC_NAME,
.\" LC_PAPER, LC_TELEPHONE.
.SS LC_CTYPE
.B LC_CTYPE
カテゴリの定義は最初のカラムに
.I LC_CTYPE
という文字列を置くことで始める。

ここでは以下のキーワードが使用できる:
.TP
.I upper
大文字 (uppercase letter) のリストを指定する。
.B A
から
.B Z
までの文字は自動的に含まれる。
.BR cntrl ,
.BR digit ,
.BR punct ,
.B space
に指定された文字を指定することはできない。
.TP
.I lower
小文字 (lowercase letter) のリストを指定する。
.B a
から
.B z
までの文字は自動的に含まれる。
.BR cntrl ,
.BR digit ,
.BR punct ,
.B space
に指定された文字を指定することはできない。
.TP
.I alpha
アルファベットの文字を指定する。
.B upper
と
.B lower
を指定した全ての文字は自動的に含まれる。
.BR cntrl ,
.BR digit ,
.BR punct ,
.B space
に指定された文字を指定することはできない。
.TP
.I digit
数字として使用される文字を指定する。数字としては
.B 0
から
.B 9
のみが使用できる。これらはデフォルトで含まれている。
.TP
.I space
空白として使用する文字のリストを指定する。
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR graph ,
.B xdigit
に指定された文字を指定することはできない。
.BR <space> ,
.BR <form-feed> ,
.BR <newline> ,
.BR <carriage-return> ,
.BR <tab> ,
.B <vertical-tab>
は自動的に含まれる。
.TP
.I cntrl
コントロール・キャラクターのリストを指定する。
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR punct ,
.BR graph ,
.BR print ,
.B xdigit
に指定された文字を指定することはできない。
.TP
.I punct
句読点文字のリストを指定する。
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR cntrl ,
.BR xdigit ,
.B <space>
に指定された文字を指定することはできない。
.TP
.I graph
表示可能文字のリストを指定するが、
.B <space>
文字は含まない。
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR xdigit ,
.B punct
を指定した文字は自動的に含まれる。
.B cntrl
に指定された文字を指定することはできない。
.TP
.I print
.B <space>
文字を含めた表示可能文字のリストを指定する。
.BR upper ,
.BR lower ,
.BR alpha ,
.BR digit ,
.BR xdigit ,
.BR punct ,
.B <space>
に指定した文字は自動的に含まれる。
.B cntrl
に指定された文字を指定することはできない。
.TP
.I xdigit
16 進数として使用する文字のリストを指定する。10 進の数字に加えて、
6 文字を昇順で続ける。デフォルトでは以下の文字が含まれている:
.B 0
から
.BR 9 、
.B a
から
.BR f 、
.B A
から
.BR F 。
.TP
.I blank
.B "無地 (blank)"
に分類される文字のリストを指定する。
.B <space>
と
.B <tab>
は自動的に含まれる。
.TP
.I toupper
小文字から大文字への対応リストを指定する。各対応は小文字と大文字のペアを
.B ,
で区切って括弧で括って指定する。
リストの各メンバーはセミコロンで区切る。
.TP
.I tolower
大文字から小文字への対応リストを指定する。tolower という
キーワードが無い場合には toupper を逆にしたものが使用される。
.PP
.B LC_CTYPE
の定義は
.I "END LC_CYTPE"
という文字列で終了する。
.SS LC_COLLATE
.B LC_COLLATE
カテゴリは整列順序を定義している。libc による制限のため
POSIX オプションの全てが実装されているわけではない。

このカテゴリの定義は最初のカラムに
.B LC_COLLATE
を置くことで始める。

ここでは以下のキーワードが使用できる:
.TP
.I collating-element
.TP
.I collating-symbol
.PP
順序の定義は以下の行で始める:
.TP
.I order_start
.PP
これに
.BR forward ,
.BR backward ,
.B position
のいずれかのキーワードが続く。
順序を記述する行が続き、以下のキーワードで終る:
.TP
.I order_end
.PP
より詳しくは
.I /usr/lib/nls/src
にあるソース・ファイルを参照のこと。特に
.B POSIX
の例、
.B Example
と
.B Example2
を見るとよい。
.PP
.B LC_COLLATE
定義は
.I "END LC_COLLATE"
という文字列で終了する。
.SS LC_MONETARY
.B LC_MONETARY
の定義は最初のカラムに
.B LC_MONETARY
を置くことで始める。

ここでは以下のキーワードを使うことができる:
.TP
.I int_curr_symbol
国際通貨記号を指定する。これは ISO 4217 規格に定義された国際通貨
記号 (3 文字) に区切り文字を続けた 4 文字である必要がある。
.TP
.I currency_symbol
地域的な通貨記号を指定する。
.TP
.I mon_decimal_point
金額をフォーマットする際の小数点に使用する文字列を指定する。
.TP
.I mon_thousands_sep
金額をフォーマットする際に桁の区切りに使用する文字列を指定する。
.TP
.I mon_grouping
数字をフォーマットをする際に何桁ごとに区切るかを指定する。
.TP
.I positive_sign
数値において正の符号に使用する文字列を指定する。
.TP
.I negative_sign
数値において負の符号に使用する文字列を指定する。
.TP
.I int_frac_digits
.B int_curr_symbol
でフォーマットする時に使用すべき端数の桁数を指定する。
.TP
.I frac_digits
.B currency_symbol
でフォーマットする際に使用すべき端数の桁数を指定する。
.TP
.I p_cs_precedes
.I currency_symbol
または
.I int_curr_symbol
をフォーマットした金額の前に付ける場合には
.B 1
を、後ろに付ける場合には
.B 0
を指定する。
.TP
.I p_sep_by_space
以下の整数のいずれかを指定する。
.RS
.TP
.B 0
記号と数値の間に空白を入れない。
.TP
.B 1
記号と数値の間に空白を入れる。
.TP
.B 2
記号と数値が隣接していれば間に空白を入れる。
.RE
.TP
.I n_cs_precedes
.RS
.TP
.B 0
- 記号は数値の後におく。
.TP
.B 1
- 記号は数値の前におく。
.RE
.TP
.I n_sep_by_space
以下の整数のいずれかを指定する。
.RS
.TP
.B 0
.I currency_symbol
または
.I int_curr_symbol
と負の金額との間に空白を入れない。
.TP
.B 1
負の数値と記号の間に空白を入れる。
.TP
.B 2
隣接していた場合にのみ空白を入れる。
.RE
.TP
.I p_sign_posn
.RS
.TP
.B 0
値と
.I currency_symbol
または
.I int_curr_symbol
を括弧で括る。
.TP
.B 1
符号を値と
.I currency_symbol
または
.I int_curr_symbol
の前に置く。
.TP
.B 2
符号を値と
.I currency_symbol
または
.I int_curr_symbol
の後に置く。
.TP
.B 3
符号を
.I currency_symbol
または
.I int_curr_symbol
の前に置く。
.TP
.B 4
符号を
.I currency_symbol
または
.I int_curr_symbol
の後に置く。
.RE
.TP
.I n_sign_posn
.RS
.TP
.B 0
値と
.I currency_symbol
または
.I int_curr_symbol
を括弧で括る。
.TP
.B 1
符号を値と
.I currency_symbol
または
.I int_curr_symbol
の前に置く。
.TP
.B 2
符号を値と
.I currency_symbol
または
.I int_curr_symbol
の後に置く。
.TP
.B 3
符号を
.I currency_symbol
または
.I int_curr_symbol
の前に置く。
.TP
.B 4
符号を
.I currency_symbol
または
.I int_curr_symbol
の後に置く。
.RE
.PP
.B LC_MONETARY
の定義は
.I "END LC_MONETARY"
という文字列で終了する。
.SS LC_NUMERIC
このカテゴリの定義は最初のカラムに
.B LC_NUMERIC
という文字列を置くことで始める。

ここでは以下のキーワードを使用できる:
.TP
.I decimal_point
数値をフォーマットする際に小数点に使用する文字列を指定する。
.TP
.I thousands_sep
数値をフォーマットする際に桁の区切りに使用する文字列を指定する。
.TP
.I grouping
数値をフォーマットする際に何桁ごとに区切るかを文字列で指定する。
.PP
The
.B LC_NUMERIC
の定義は
.I "END LC_NUMERIC"
という文字列で終了する。
.SS LC_TIME
このカテゴリの定義は最初のカラムに
.B LC_TIME
という文字列を置くことで始める。

ここでは以下のキーワードが使用できる:
.TP
.I abday
曜日の名前の省略形のリストを指定する。
リストは
.I week
で指定された週の開始曜日 (デフォルトでは日曜日) から始める。
.TP
.I day
曜日の名前のリストを指定する。
リストは
.I week
で指定された週の開始曜日 (デフォルトでは日曜日) から始める。
.TP
.I abmon
月の名前の省略形のリストを指定する。
.TP
.I mon
月の名前のリストを指定する。
.TP
.I am_pm
それぞれ
.B "午前 (am)"
と
.B "午後 (pm)"
に対応する文字列を指定する。
.TP
.I d_t_fmt
適切な日付け (date) と時刻 (time) のフォーマットを指定する。
.TP
.I d_fmt
適切な日付け (date) のフォーマットを指定する。
.TP
.I t_fmt
適切な時刻 (time) のフォーマットを指定する。
.TP
.I t_fmt_ampm
12 時間方式を使用した時刻のフォーマットを指定する。
.TP
.I week
3 つの値からなるリストを指定する。
リストは、一週間の日数 (デフォルトでは 7)、
週の開始曜日 (デフォルトでは日曜に対応)、
一年の最初の週の最小の長さ (デフォルトでは 4) から構成される。
週の開始曜日については、週の開始日が日曜日の場合には
.B 19971130
を、月曜日の場合には
.B 19971201
を使用する。したがって、
.I day
リストの最初の日として、
.B 19971130
を使う国ではその地域の日曜日の名前を、
.B 19971201
を使う国ではその地域の月曜日の名前を設定すべきである。
.TP
.IR first_weekday " (glibc 2.2 以降)"
カレンダーアプリケーションで最初に表示する曜日の
.I day
リストにおける番号。
デフォルト値の 1 は日曜日か月曜日に対応する。
どちらに対応するかは
.I week
リストの二番目の項目の値で決まる。
.TP
.IR first_workday " (glibc 2.2 以降)"
最初の就業日を示す
.I day
リストにおける曜日の番号。
.PP
.B LC_TIME
の定義は
.I "END LC_TIME"
という文字列で終了する。
.SS LC_MESSAGES
このカテゴリの定義は最初のカラムに
.B LC_MESSAGES
という文字列を置くことで始める。

ここでは以下のキーワードが使用できる:
.TP
.I yesexpr
「はい (yes)」を意味する正規表現を指定する。
.TP
.I noexpr
「いいえ (no)」を意味する正規表現を指定する。
.PP
.B LC_MESSAGES
の定義は
.I "END LC_MESSAGES"
という文字列で終了する。

より詳しくは POSIX.2 規格を参照のこと。
.SH ファイル
/usr/lib/locale/
\(em 現在のロケール設定のデータベース
.br
/usr/lib/nls/charmap/* \(em 文字定義ファイル
.SH 準拠
POSIX.2, ISO/IEC 14652.
.SH バグ
このマニュアルは完全ではない。
.\" .SH 著者
.\" Jochen Hein (Hein@Student.TU-Clausthal.de)
.SH 関連項目
.BR locale (1),
.BR localedef (1)
.BR localeconv (3),
.BR setlocale (3),
.BR charmap (5),
