.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)printcap.5	6.6 (Berkeley) 5/10/91
.\"
.\" Japanese Version Copyright (c) 2000 Hirohisa AMAN,
.\"     <aman@soft.comp.kyutech.ac.jp> all right reserved.
.\"
.Dd May 10, 1991
.Dt PRINTCAP 5
.Os BSD 4.2
.Sh 名前
.Nm printcap
.Nd プリンタ ケイパビリティ データベース
.Sh 書式
.Nm printcap
.Sh 説明
.Nm printcap 
は
.Xr termcap 5
データベースを簡単にしたものであり、ラインプリンタを記述するのに使われる。
スプーリングシステムは、使用されるたびに
.Nm printcap
ファイルにアクセスし、プリンタの動的な追加と削除を可能にしている。
データベースにおける各エントリは、1 つのプリンタを記述するのに使われる。
このデータベースは書き込み可能にしておいてはならない(
.Xr termcap
データベースは普通書き込み可能になっている)。
なぜなら、それによってアカウンティング(accounting)をすり抜けることが
可能になってしまうからである。
.Pp
通常、デフォルトプリンタは
.Em lp
である。ただし、環境変数
.Ev PRINTER
が設定されていれば、そちらが優先される。
各スプーリングユーティリティは、目的のプリンタを明示的に指定できるよう、
オプション
.Fl P Ar printer
をサポートしている。
.Pp
ある特定のプリンタに対するこのデータベースの設定の詳細は
.%T "4.3 BSD Line Printer Spooler Manual"
を参照せよ。
.Sh ケイパビリティ
ファイルレイアウトの説明については
.Xr termcap 5
を参照せよ。
.Bl -column Namexxx Typexx "/var/spool/lpdxxxxx"
.Sy Name	Type	Description
.It "af	str" Ta Dv NULL Ta No "アカウントファイル名"
.It "br	num	none	lp が tty の場合, そのボーレートを設定する"
.Pf ( Xr ioctl 2
コール)
.It "cf	str" Ta Dv NULL Ta No "cifplot データ用フィルタ"
.It "df	str" Ta Dv NULL Ta No "tex データ"
.Pf ( Tn DVI
フォーマット)
用フィルタ
.It "fc	num	0	lp が tty の場合, フラグビットをクリアーする"
.Pq Pa sgtty.h
.It "ff	str" Ta So Li \ef Sc Ta No "改ページ(form feed) のために送信する文字列"
.It "fo	bool	false	デバイスオープン時に改ページ(form feed)を印刷する"
.It "fs	num	0	`fc' と同様だが、こちらはビットをセットする"
.It "gf	str" Ta Dv NULL Ta No "グラフデータ用フィルタ"
.Pf ( Xr plot 3
フォーマット )
.It "hl	bool	false	最後にバーストヘッダーページを印刷する"
.It "ic	bool	false	ドライバはインデント付き印刷のために (非標準の) ioctl をサポートする"
.It "if	str" Ta Dv NULL Ta No "アカウントのためのテキストフィルタ名"
.It "lf	str" Ta Pa /dev/console Ta No "エラーログファイル名"
.It "lo	str" Ta Pa lock Ta No "ロックファイル名"
.It "lp	str" Ta Pa /dev/lp Ta No "出力に対してオープンするデバイス名"
.It "mx	num	1000	最大ファイルサイズ ("
.Dv BUFSIZ
ブロックの数で指定), 0 = 制限なし
.It "nd	str" Ta Dv NULL Ta No "キューリストのための次のディレクトリ (未実装)"
.It "nf	str" Ta Dv NULL Ta No "ditroff データ(デバイス非依存 troff)用フィルタ "
.It "of	str" Ta Dv NULL Ta No "出力フィルタプログラム名"
.It "pc	num	200	1 フィートもしくは 1 ページあたりの価格(1/100 セント単位)"
.It "pl	num	66	ページ長 (行数)"
.It "pw	num	132	ページ幅 (文字数)"
.It "px	num	0	ピクセル単位でのページ幅 (水平方向)"
.It "py	num	0	ピクセル単位でのページ長 (垂直方向)"
.It "rf	str" Ta Dv NULL Ta No ""
.Tn FORTRAN
スタイルのテキストファイルを印刷するためのフィルタ
.It "rg	str" Ta Dv NULL Ta No "制限グループ。このグループのメンバーのみアクセスが許される"
.It "rm	str" Ta Dv NULL Ta No "リモートプリンタのためのマシン名"
.It "rp	str	``lp''	リモートプリンタ名引数"
.It "rs	bool	false	ローカルにアカウントをもったリモートユーザに限定する"
.It "rw	bool	false	読み書きのためにプリンタデバイスをオープンする"
.It "sb	bool	false	ショートバナー(short banner) (1 行のみ)"
.It "sc	bool	false	複数コピーを抑制する"
.It "sd	str" Ta Pa /var/spool/lpd Ta No "スプールディレクトリ"
.It "sf	bool	false	改ページ(form feed)を抑制する"
.It "sh	bool	false	バーストページヘッダーの印刷を抑制する"
.It "st	str" Ta Pa status Ta No "ステータスファイル名"
.It "tf	str" Ta Dv NULL Ta No "troff データ(cat 写植)用フィルタ "
.It "tr	str" Ta Dv NULL Ta No "キューが空の場合に印刷するための後書き文字列(trailer string)"
.It "vf	str" Ta Dv NULL Ta No "ラスタイメージ(raster image)用フィルタ"
.El
.Pp
ローカルのラインプリンタドライバが字下げをサポートしているならば、
デーモンはその方法を理解できなければならない。
.Sh フィルタ
.Xr lpd 8
デーモンは、さまざまなプリンタのタイプに応じてファイルを処理するために、
.Em filters
(フィルタ)
のパイプラインを構築している。
選択されるフィルタは、
.Xr lpr 1 
へ渡されるフラグに依存している。
パイプラインの構築は、次のようになる :
.Bd -literal -offset indent
p	pr | if	通常テキスト + pr(1)
none	if	通常テキスト
c	cf	cifplot
d	df	DVI (tex)
g	gf	plot(3)
n	nf	ditroff
f	rf	Fortran
t	tf	troff
v	vf	ラスタイメージ(raster image)
.Ed
.Pp
.Sy if
フィルタは、次の引数とともに呼び出される:
.Bd -filled -offset indent
.Cm if
.Op Fl c
.Fl w Ns Ar width
.Fl l Ns Ar length
.Fl i Ns Ar indent
.Fl n Ar login
.Fl h Ar host acct-file
.Ed
.Pp
.Fl c
フラグは、
.Xr lpr
に
.Fl l
フラグ(制御文字を文字としてそのまま通す)が指定してある時に限って渡される。
.Ar width
と
.Ar length
は、ページの幅と長さ(それぞれ
.Cm pw
と
.Cm pl
から得られる)を文字数で指定する。
.Fl n
と
.Fl h
はそれぞれ、ジョブ所有者のログイン名とホスト名を指定する。
.Ar acct-file
は、
.Nm printcap
の
.Cm af
エントリから渡される。
.Pp
.Cm if
が指定されていない場合は、
代わりに
.Cm of
が使用される。これらの間には、
.Cm if
がそれぞれのジョブに対して毎回オープンされるのに対し、
.Cm of
は 1 回しかオープンされないという違いがある。
したがって、アカウンティング(accounting)を行なうには
.Cm if
の方が適している。
.Cm of
には、
.Ar width
と
.Ar length
の 2 つのフラグが与えられるだけである。
.Pp
他のすべてのフィルタは、次のようにして呼び出される:
.Bd -filled -offset indent
.Nm filter
.Fl x Ns Ar width
.Fl y Ns Ar length
.Fl n Ar login
.Fl h Ar host acct-file
.Ed
.Pp
ただし、
.Ar width
と
.Ar length
はピクセル単位で表され、それぞれ
.Cm px
エントリと
.Cm py
エントリによって指定される。
.Pp
すべてのフィルタは、そのファイルとして
.Em stdin 
(標準入力)を、プリンタとして
.Em stdout 
(標準出力)をとる。そのログは、
.Em stderr 
(標準エラー出力)に対して、もしくは
.Xr syslog 3
を使ってとられる。また、
.Dv SIGINT
を無視することは許されない。
.Sh ロギング(LOGGING)
ラインプリンタプログラム自身
(つまり、
.Xr lp Ns *
プログラム)
によって生成されたエラーメッセージは、
.Dv LPR
を使うことで
.Xr syslog 3
によって記録される。
フィルタのうちの 1 つの
.Em stderr
(標準エラー出力)
上に印刷されたメッセージは、それに対応する
.Cm lf
ファイルへと送られる。
もちろん、フィルタはそれ自身で
.Xr syslog
を使ってもかまわない。
.Pp
コンソールへ送られるエラーメッセージには、改行(LF)だけではなく、
復帰(CR)と改行(LF)が追加される。
.Sh 関連項目
.Xr termcap 5 ,
.Xr lpc 8 ,
.Xr lpd 8 ,
.Xr pac 8 ,
.Xr lpr 1 ,
.Xr lpq 1 ,
.Xr lprm 1
.Rs
.%T "4.3 BSD ラインプリンタスプーラーマニュアル"
.Re
.Sh 履歴
.Nm
ファイルフォーマットは、
.Bx 4.2 
で登場した。


