.\" Copyright (c) 1995 Martin Schulze <joey@infodrom.north.de>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" 1995-10-18  Martin Schulze  <joey@infodrom.north.de>
.\"	* first released
.\" 2002-09-22  Seth W. Klein  <sk@sethwklein.net>
.\"     * protocol numbers are now assigned by the IANA
.\"
.\" Japanese Version Copyright (c) 1998 Hiroaki Nagoya all rights reserved.
.\" Translated Wed Feb 4 1998 by Hiroaki Nagoya <nagoya@is.titech.ac.jp>
.\" Updated Tue Oct 16 2001 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH PROTOCOLS 5 2008-09-23 "Linux" "Linux Programmer's Manual"
.SH 名前
protocols \- プロトコル定義ファイル
.SH 説明
このファイルは ASCII ファイルで、TCP/IP サブシステムから利用できる
いろいろな DARPA インターネットプロトコルを記述している。
ARPA 関連のインクルードファイル内の数値を使うべきではないし、
単に推測した値を使うのはさらに良くない。
代わりにこのファイルに問い合わせるべきである。
これらの数値は IP ヘッダのプロトコルフィールドに現れる。

このファイルは変更しないこと。変更すると IP パッケージが不正になる。
プロトコル番号とプロトコル名は
IANA (Internet Assigned Numbers Authority) によって指定される。
.\" DDN Network Information Center によって指定される。

それぞれの行は次のフォーマットである。

.RS
.I protocol number aliases ...
.RE

各フィールドは空白かタブで区切られていて、空行は無視される。
行にハッシュ記号(#)が含まれる場合、
ハッシュ記号を含むその行の残りは無視される。

フィールドの説明は以下のとおり。
.TP
.I protocol
プロトコルの固有名。たとえば
.IR ip ,
.IR tcp ,
.IR udp
など。
.TP
.I number
プロトコルの公式番号、IP ヘッダに現れる。
.TP
.I aliases
プロトコルの別名、オプション。
.LP
このファイルは Yellow Pages/NIS や BIND/Hesoid などのネットワーク上の
名前付けサービスによってネットワーク上で配布されているかもしれない。
.SH ファイル
.TP
.I /etc/protocols
プロトコル定義ファイル。
.SH 関連項目
.BR getprotoent (3)

http://www.iana.org/assignments/protocol-numbers
