.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"     Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified formatting Sat Jul 24 17:13:38 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified (extensions and corrections)
.\"   Sun May  1 14:21:25 MET DST 1994 Michael Haardt
.\"   If mistakes in the capabilities are found, please send a bug report to:
.\"   michael@moria.de
.\" Modified Mon Oct 21 17:47:19 EDT 1996 by Eric S. Raymond (esr@thyrsus.com)
.\"
.\" Japanese Version Copyright (c) 1999 NOKUBI Takatsugu
.\" 	all rights reserved.
.\" Translated Fri Jan 29 13:09:56 JST 1999
.\"	by NOKUBI Takatsugu <knok@daionet.gr.jp>
.\" Proofed & Modified Thu 12 Oct 2000
.\"     by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.\"WORD capability	機能
.\"WORD formfeed	頁送り
.\"WORD	standout	強調
.\"WORD carriage return	復帰
.\"WORD new line	改行
.\"WORD block graphic character(s)	図形文字(集合)
.\"WORD alternate character set		代替文字集合
.\"
.TH TERMCAP 5 1996-10-21 "Linux" "Linux Programmer's Manual"
.SH 名前
termcap \- 端末機能のデータベース
.SH 説明
termcap データベースは、
文字単位で動作する端末やプリンタの機能を記述するための旧式の機構である。
この機構は古いプログラムを動作させるためだけに保持されているので、
新しいプログラムは
.BR terminfo (5)
データベースとそれに関連したライブラリを用いるべきである。
.LP
.I /etc/termcap
は、多くの異なる種類の端末に関する機能を列記したアスキーファイル
(データベースマスター) である。
プログラムは termcap を読み込んで、
実際に使用している端末に個別のエスケープコード群を取得する。
これを用いると、その端末の視覚的な性質を制御することができる
(端末の他の性質は
.BR stty (1)
で制御する)。
termcap データベースは、環境変数
.B TERM
の値で引かれる。
.LP
termcap のエントリは、単一の論理行でなければならない。
ただし、行末に \(aq\\\(aq を用いればそこでの改行を抑制することができる。
フィールドは \(aq:\(aq で分割される。
各エントリの最初のフィールドは左側先頭から始まり、
内容はその端末の名前のリストである。名前の区切りには \(aq|\(aq が用いられる。
.LP
最初のサブフィールドは
(4.3 以前のバージョンのBSD termcap エントリでは)
2 文字からなる短い名前となっている。この短い名前は
大文字もしくは小文字で構成される。4.4BSD の termcap エントリでは、
このフィールドは省略される。
.LP
2 番目 (最新の 4.4BSD フォーマットでは 1 番目) のサブフィールドには、
環境変数
.B TERM
で用いられる名称が入る。
このフィールドには小文字しか使えない。
選択可能なハードウェア機能は、ハイフンと接尾語 (suffix)
を名称の後に追加することによって示す必要がある。以下の例を見よ。
慣習的な接尾語には、w (80 文字以上の幅がある)、
am (automatic margins: 自動的な行の折り返し)、
nam (non automatic margins: 自動的でない行の折り返し)、
rv (reverse video display: 反転ビデオ表示)
などがある。
3番目のサブフィールドには、
このtermcapエントリーに対する長い説明的な名称が入る。
.LP
この後に続くフィールドには、端末の機能を記述する。
機能を記述する行が継続する場合は、
左端から1つのタブをおいてインデントしなければならない。
.LP
順序については定義されていないが、
大文字小文字は区別せずにアルファベット順にならべ、
始めはブール値の、次は数値の、最後は文字列の機能を書くことが推奨されている。
同じような働きをする機能は 1 行にまとめて書くと良い。
.LP
.nf
例:
.sp
Head line: vt|vt101|DEC VT 101 terminal in 80 character mode:\e
Head line: Vt|vt101-w|DEC VT 101 terminal in (wide) 132 character mode:\e
Boolean: :bs:\e
Numeric: :co#80:\e
String: :sr=\eE[H:\e
.fi
.SS "ブール値で指定する機能"
.nf
5i	プリンタはスクリーンにエコーしない
am	自動マージン。自動的に行を折り返す
bs	コントロール H (キーコード 8) をバックスペースとして扱う
bw	左端でのバックスペースを、上の行の右端に折り返す
da	画面の上端から外れていた行を表示する (通常はマルチページ端末で)
db	画面の下端から外れていた行を表示する (通常はマルチページ端末で)
eo	空白文字はカーソル位置の全ての文字を消す
es	ステータス行上のエスケープシーケンスや特殊文字は有効に働く
gn	一般的なデバイスである
hc	ハードコピー端末である
HC	最下行にないカーソルは見づらい
hs	ステータス行がある
hz	チルダ文字が表示できない端末である (Hazeltine 端末のバグ)
in	ホワイトスペースを埋めるのに、スペースではなく NULL バイトを挿入する端末である
km	端末にはメタキーがある
mi	挿入モードでもカーソル移動ができる
ms	強調/下線モードでもカーソル移動ができる
NP	パディング文字がない
NR	ti は te を反転しない
nx	パディングではなく、XON/XOFF を使わなければならない
os	重ね打ちが可能な端末である
ul	重ね打ちはできないが、下線表示のできる端末である
xb	f1 はエスケープを送信し、f2 は \fB^C\fP を送信する (Beehive 端末の不具合)
xn	改行/折り返しに不具合がある
xo	端末は xon/xoff プロトコルを用いる
xs	強調文字の上に出力された文字は強調文字として表示される
xt	破壊的なタブと中途半端な強調モード (Teleray 端末の不具合)
.fi
.SS "数値で指定する機能"
.nf
co	端末の行数
dB	ハードコピー端末において、バックスペースに必要な遅延時間 (ミリ秒単位)
dC	ハードコピー端末において、復帰に必要な遅延時間 (ミリ秒単位)
dF	ハードコピー端末において、頁送りに必要な遅延時間 (ミリ秒単位)
dN	ハードコピー端末において、改行に必要な遅延時間 (ミリ秒単位)
dT	ハードコピー端末において、タブストップに必要な遅延時間 (ミリ秒単位)
dV	ハードコピー端末において、垂直タブに必要な遅延時間 (ミリ秒単位)
it	タブ位置間の文字数
lh	ソフトラベルの高さ
lm	画面メモリに収容できる行数
lw	ソフトラベルの幅
li	行数
Nl	ソフトラベルの数
pb	パディングが必要となる最低のボーレート
sg	強調表示の不具合 (強調表示に切替えたときに表示されるスペースの数)
ug	下線表示の不具合 (強調表示に切替えたときに表示されるスペースの数)
vt	仮想端末番号
ws	ステータス行の幅 (画面幅と異なる場合)
.fi
.SS	"文字列で指定する機能"
.nf
!1	シフト状態の save キー
!2	シフト状態の suspend キー
!3	シフト状態の undo キー
#1	シフト状態の help キー
#2	シフト状態の home キー
#3	シフト状態の input キー
#4	シフト状態の左カーソルキー
%0	redo キー
%1	help キー
%2	markキー
%3	message キー
%4	move キー
%5	next-object キー
%6	open キー
%7	options キー
%8	previous-object キー
%9	print キー
%a	シフト状態の message キー
%b	シフト状態の move キー
%c	シフト状態の next キー
%d	シフト状態の options キー
%e	シフト状態の previous キー
%f	シフト状態の print キー
%g	シフト状態の redo キー
%h	シフト状態の replace キー
%i	シフト状態の右カーソルキー
%j	シフト状態の resume キー
&0	シフト状態の cancel キー
&1	reference キー
&2	refresh キー
&3	replace キー
&4	restart キー
&5	resume キー
&6	save キー
&7	suspend キー
&8	undo キー
&9	シフト状態の begin キー
*0	シフト状態の find キー
*1	シフト状態の command キー
*2	シフト状態の copy キー
*3	シフト状態の create キー
*4	シフト状態の delete キー
*5	シフト状態の delete line キー
*6	select キー
*7	シフト状態の end キー
*8	シフト状態の clear line キー
*9	シフト状態の exit キー
@0	find キー
@1	begin キー
@2	cancel キー
@3	close キー
@4	command キー
@5	copy キー
@6	create キー
@7	end キー
@8	enter/send キー
@9	exit キー
al	1 行挿入する
AL	%1 行挿入する
ac	図形文字のペアの集合。代替文字セットにマップするためのもの
ae	代替文字セットの終り
as	図形文字集合に対する、代替文字セットの開始
bc	\fB^H\fP がバックスペースでない場合のバックスペース
bl	(音声の) ベルを鳴らす
bt	前のタブストップへ移動
cb	行頭からカーソル位置までのクリア
cc	ダミーコマンド文字
cd	画面の最後までをクリア
ce	行の最後までをクリア
ch	カーソルを水平方向にだけ移動し、 %1 桁の位置にする
cl	画面を消去し、カーソルをホームポジションへ
cm	画面上の %1 行、 %2 桁へカーソルを移動
CM	メモリ上の %1 行、 %2 桁へカーソルを移動
cr	復帰
cs	%1 行目から %2 行目までの範囲をスクロールする
ct	タブの消去
cv	カーソルを垂直方向にだけ移動し、 %1 行の位置にする
dc	一文字削除する
DC	%1 文字削除する
dl	一行削除する
DL	%1 行削除する
dm	delete モード開始
do	カーソルを一行下げる
DO	カーソルを #1 行下げる
ds	ステータス行を無効にする
eA	代替文字集合を有効にする
ec	カーソル位置から %1 文字消去する
ed	delete モード終了
ei	intert モード終了
ff	ハードコピー端末での頁送り文字
fs	ステータス行に移動する前の位置へ復帰する文字
F1	ファンクションキー f11 が送出する文字列
F2	ファンクションキー f12 が送出する文字列
F3	ファンクションキー f13 が送出する文字列
\&...	\&...
F9	ファンクションキー f19 が送出する文字列
FA	ファンクションキー f20 が送出する文字列
FB	ファンクションキー f21 が送出する文字列
\&...	\&...
FZ	ファンクションキー f45 が送出する文字列
Fa	ファンクションキー f46 が送出する文字列
Fb	ファンクションキー f47 が送出する文字列
\&...	\&...
Fr	ファンクションキー f63 が送出する文字列
hd	カーソルを一行の半分だけ下に移動
ho	カーソルをホームポジションに移動
hu	カーソルを一行の半分だけ上に移動
i1	ログイン時の初期化文字列 1
i3	ログイン時の初期化文字列 3
is	ログイン時の初期化文字列 2
ic	一文字挿入
IC	%1 文字挿入
if	初期化ファイル
im	insert モード開始
ip	挿入後のパディングに必要な時間と特殊文字
iP	初期化プログラム
K1	キーパッドの左上キー
K2	キーパッドの中央キー
K3	キーパッドの右上キー
K4	キーパッドの左下キー
K5	キーパッドの右下キー
k0	ファンクションキー 0
k1	ファンクションキー 1
k2	ファンクションキー 2
k3	ファンクションキー 3
k4	ファンクションキー 4
k5	ファンクションキー 5
k6	ファンクションキー 6
k7	ファンクションキー 7
k8	ファンクションキー 8
k9	ファンクションキー 9
k;	ファンクションキー 10
ka	clea all tabs キー
kA	insert line キー
kb	バックスペースキー
kB	back tab キー
kC	clear screen キー
kd	下カーソルキー
kD	カーソル位置の文字を消すキー
ke	キーパッドをオフにする
kE	行末までをクリアするキー
kF	前方向/下方向へスクロールするキー
kh	home キー
kH	cursor hown down キー
kI	文字挿入キー/insert モードキー
kl	左カーソルキー
kL	行を削除するキー
kM	insert モードを終了するキー
kN	次のページへ移動するキー
kP	前のページへ移動するキー
kr	右カーソルキー
kR	後ろ方向/上方向にスクロールするキー
ke	キーパッドをオンにする
kS	画面最後までをクリアするキー
kt	タブクリアキー
kT	タブストップ設定キー
ku	上カーソルキー
l0	0 番目のファンクションキーのラベル (f0 でない場合)
l1	1 番目のファンクションキーのラベル (f1 でない場合)
l2	2 番目のファンクションキーのラベル (f2 でない場合)
\&...	\&...
la	10 番目のファンクションキーのラベル (f10 でない場合)
le	カーソルを左へ一文字分移動する
ll	カーソルを左下隅に移動する
LE	カーソルを左 %1 文字分移動する
LF	ソフトラベルをオフにする
LO	ソフトラベルをオンにする
mb	点滅開始
MC	ソフトマージンをクリア
md	bold モード開始
me	so, us, mb, md, mr などのモード全てを終了する
mh	半輝度モード開始
mk	ダークモード (文字は見えなくなる)
ML	左側のソフトマージンを設定
mm	端末をメタモードに設定する
mo	端末をメタモードでなくする
mp	属性保護モードをオンにする
mr	反転モード開始
MR	右端のソフトマージンを設定
nd	カーソルを右に一文字分移動
nw	復帰コマンド
pc	パディング文字
pf	プリンタをオフにする
pk	ユーザが入力したときに文字列 %2 を送出するプログラムキー %1
pl	ローカルモードで文字列 %2 を実行するプログラムキー %1
pn	文字列 %2 を表示するためのプログラムソフトラベル %1
po	プリンタをオンにする
pO	%1 (<256) バイトの間プリンタをオンにする
ps	画面上の内容をプリンタに印刷する
px	文字列 %2 をコンピュータに送出するプログラムキー %1
r1	端末を正常なモードに設定するリセット文字列 1
r2	端末を正常なモードに設定するリセット文字列 2
r3	端末を正常なモードに設定するリセット文字列 3
RA	自動折り返しを無効にする
rc	保存しておいたカーソル位置に復帰する
rf	リセット文字列の入ったファイル名
RF	端末からの入力要求
RI	カーソルを右へ %1 文字分移動する
rp	文字 %1 を %2 回分繰り返す
rP	置換モードにおいて、文字を送出した後に行うパディング
rs	リセット文字列
RX	XON/XOFF フロー制御をオフにする
sa	属性 %1 %2 %3 %4 %5 %6 %7 %8 %9 を設定
SA	自動折り返しを有効にする
sc	カーソル位置を保存する
se	強調モード終了
sf	順方向の 1 行スクロール
SF	順方向の %1 行スクロール
so	強調モード開始
sr	逆スクロール
SR	%1 行分逆スクロールする
st	全ての行において、現在の桁位置をタブストップに設定する
SX	XON/XOFF フロー制御をオンにする
ta	次のハードウェアタブ位置へ移動
tc	他のエントリから端末の説明を読む込む
te	カーソル移動を用いるプログラムの終了
ti	カーソル移動を用いるプログラムの開始
ts	ステータス行のカーソルを %1 桁へ移動
uc	カーソル位置の文字に下線をつけ、右にカーソルを移動
ue	下線モード終了
up	カーソルを 1 行分上に移動
UP	カーソルを %1 行分上に移動
us	下線モード開始
vb	ビジュアルベル
ve	カーソルを通常の明るさにする
vi	カーソルを見えなくする
vs	強調カーソル
wi	ウィンドウ領域を %1〜%2 行、%3〜%4 桁に設定
XF	XOFF 制御文字 (\fB^S\fP でない場合)
.fi
.LP
文字列機能の制御コードを定義するには、いくつかの方法がある。
.LP
\&\(aq^\(aq, \(aq\e\(aq, \(aq%\(aq を除く全ての通常の文字は、それ自身を表す。
.LP
\fB^x\fP は Control-x を意味する。 Control-A は 10 進数の 1 に等しい。
.\"NAKANO: 1 decimal?
.LP
\&\ex は特殊コードとして扱われる。x には以下の文字のどれかが入る。
.RS
E エスケープ (27)
.br
n ラインフィード (10)
.br
r 復帰 (13)
.br
t タブ (9)
.br
b バックスペース (8)
.br
f 頁送り (12)
.br
0 ヌルキャラクタ。'\exxx' は 8 進数 xxx の文字を表す。
.RE
.IP i
パラメータを 1 増加させる。
.IP r
一つのパラメータをとる機能
.IP +
次の文字の値をパラメータに追加し、バイナリで出力する
.IP 2
パラメータを 2 桁の数字として ASCII 出力する (printf の %2d と同じ意味)
.IP d
パラメータを数字として ASCII 出力する (printf の %d と同じ意味)
.IP %
\(aq%\(aq を表示する
.LP
バイナリ出力を行う場合、
文字列が終端されないようにヌル文字 (\(aq\\0\(aq) を避けねばならない。
タブ文字をパラメータのバイナリ出力とする場合は、
タブ文字の展開をリセットしなければならない。
.IP 注意:
上記のような、パラメータとしてのメタ文字は正しくないかもしれない。
このことは、Minixの termcap と
Linux の termcap との間に互換性がないことに繋がっている。
.\"NAKANO: あやしい。
.LP
図形文字は 3 つの文字列機能で指定できる。
.IP as
代替文字セットの開始
.IP ae
代替文字セットの終了
.IP ac
文字列のペアの集合を指定する。
最初の文字は図形文字の名称で、
2 番目の文字はその定義である。
.LP
名称には以下のものがある。
.sp
.nf
+	右矢印 (>)
,	左矢印 (<)
\&.	下矢印 (v)
0	なかを塗りつぶした四角 (#)
I	ランタン記号 (#)
(訳注 原文は latern だったが、これは lantern の typo と思われる)
-	上矢印 (^)
\&'	菱形 (+)
a	チェス板 (:)
f	角度 (')
g	プラスマイナス (#)
h	四角 (#)
j	右下隅 (+)
k	右上隅 (+)
l	左上隅 (+)
m	左下隅 (+)
n	十字 (+)
o	上水平線 (-)
q	中水平線 (-)
s	下水平線 (_)
t	左 T 字 (+)
u	右 T 字 (+)
v	下 T 字 (+)
w	正 T 字 (+)
x	垂直線 (|)
~	段落 (???)
.fi
.sp
括弧内の値は、
指定した機能が存在しない場合に用いられるデフォルトの値である。
.SH 関連項目
.BR ncurses (3),
.BR termcap (3),
.BR terminfo (5)
.SH 校正者記
訳出にあたっては "\fBtermcap & terminfo\fP"
(Strang, Mui, O'reilly 共著, 鈴木麗 監訳, アスキー出版局 1992)
を参考にした。
ただし本日本語マニュアルにおける誤りは校正者の責任である。
