'.\" Copyright (c) 1989, 1991 The Regents of the University of California.
'.\" All rights reserved.
'.\"
'.\" Redistribution and use in source and binary forms, with or without
'.\" modification, are permitted provided that the following conditions
'.\" are met:
'.\" 1. Redistributions of source code must retain the above copyright
'.\"    notice, this list of conditions and the following disclaimer.
'.\" 2. Redistributions in binary form must reproduce the above copyright
'.\"    notice, this list of conditions and the following disclaimer in the
'.\"    documentation and/or other materials provided with the distribution.
'.\" 3. All advertising materials mentioning features or use of this software
'.\"    must display the following acknowledgement:
'.\"	This product includes software developed by the University of
'.\"	California, Berkeley and its contributors.
'.\" 4. Neither the name of the University nor the names of its contributors
'.\"    may be used to endorse or promote products derived from this software
'.\"    without specific prior written permission.
'.\"
'.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
'.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
'.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
'.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
'.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
'.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
'.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
'.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
'.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
'.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
'.\" SUCH DAMAGE.
'.\"
'.\"     @(#)uuencode.format.5	6.4 (Berkeley) 5/10/91
'.\"
.\" Japanese Version Copyright (c) 2000 Yuichi SATO
.\"         all rights reserved.   
.\" Translated Tue Jun 20 21:37:49 JST 2000
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.\"WORD:        encode          エンコード
.\"WORD:        decode          デコード
.\"WORD:	header		ヘッダー
.\"WORD:	tailer		フッター
.\"
.TH UUENCODE 5
.SH 名前
uuencode \- エンコードされた uuencode ファイルの形式
.SH 説明
uuencode(1) のファイル出力は、
1 行のヘッダー行・複数行のボディー行・
1 行のフッター行から構成される。
uudecode(1) コマンドは、ヘッダーより前やフッターより後の
すべての行を無視する。
もちろん、ヘッダーより前の行は、ヘッダーのように見えてはならない。
.PP
ヘッダー行は、最初の 6 文字が
.I begin\ \&
であることで識別される。
単語
.I begin
の後には、アクセス権 (8 進数表記) とリモートファイルの名前になる文字列が続く。
ヘッダー行中の 3 つのアイテムはスペースで区切られる。
.PP
ボディーは複数行で、各行は (最後の改行を含めて)
最大 62 文字の長さである。
各行は、文字カウント、続いてエンコードされた文字列、
続いて改行文字、というように構成されている。
文字カウントは、1 個の表示可能文字で整数値を表している。
この整数値は、行の残りの文字列が表現しているバイト数を表している。
この整数値は常に 0 から 63 の範囲で、
その文字カウント (を整数にしたもの) から
スペース文字 (8 進数で 40) を引けば求められる。
.PP
3 バイトからなるグループが 4 文字で表現される。
つまり、1 文字あたり 6 ビットを表現する。
文字を表示可能にするために、
すべてのビットがスペース文字でオフセットされる。
ボディーの最終行は、通常の 45 バイトより短くなる場合もある。
(エンコードされるファイルの) サイズが 3 バイトの倍数でない場合、
ボディー最終行の文字カウントの値をみると、3 バイトの倍数でないことがわかる。
文字カウントを 4 の倍数にするため、余分なゴミが追加される場合がある。
ボディーは、文字カウントが 0 の行で終了する。
この行は、1 個のアスキーのスペース文字からなる。
.PP
フッター行は、
.I end
という行だけからなる。
.SH 関連項目
uuencode(1), uudecode(1), uusend(1), uucp(1), mail(1)
.SH 履歴
.I uuencode
ファイル形式は、BSD 4.0 で登場した。


