.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Sep 29 01:13:26 JST 2001
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\"
.\"WORD:	
.\"
.\" $Id: adsl-start.8,v 1.3 2002/04/09 17:28:38 dfs Exp $ 
.\" LIC: GPL
.TH ADSL-START 8 "21 February 2000"
.UC 4
.SH 名前
adsl-start \- PPPoE 接続を開くシェルスクリプト
.SH 書式
.B adsl-start \fR[\fIconfig_file\fR]
.P
.B adsl-start \fR\fIinterface user\fR [\fIconfig_file\fR]

.SH 説明
\fBadsl-start\fR は Roaring Penguin ユーザー空間 PPPoE クライアントを
起動するシェルスクリプトである。
\fIconfig_file\fR を省略した場合、
デフォルトの設定ファイル \fB/etc/ppp/pppoe.conf\fR が使われる。
\fIinterface\fR と \fIuser\fR を指定した場合、
設定ファイルにあるイーサーネットインターフェースと
ユーザー名の設定を上書きする。

.SH 著者
\fBadsl-start\fR は David F. Skoll <dfs@roaringpenguin.com> によって
作成された。

\fBpppoe\fR のホームページは
\fIhttp://www.roaringpenguin.com/pppoe/\fR である。

.SH 関連項目
pppoe(8), adsl-stop(8), adsl-connect(8), pppd(8), pppoe.conf(5),
adsl-setup(8), adsl-status(8), pppoe-sniff(8), pppoe-relay(8),
pppoe-server(8)
