'\" te
.\" To print, first run through tbl
.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Nov 25 18:34:39 JST 2001
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\"
.TH APPLE_DRIVER 8 "18 May 1998" "Version 1.0"
.SH 名前
apple_driver \- Macintosh パーティションのラベル・マップ・ブートドライバを取り出す
.SH 書式
.B apple_driver
CDROM_device > HFS_driver_file
.SH 説明
.I apple_driver
は
.IR mkhybrid (1)
の
.I \-hfs-boot-file 
オプションに必要な情報を Apple (またはその互換) の CD-ROM から取り出す。
.PP
.I CDROM_device
は
CD-ROM に使われているデバイス名である (例えば /dev/cdrom)。
.PP
HFS ドライバファイルのフォーマットは、以下の通りである:
.PP
.TS
l l .
HFS CD ラベルブロック	512 バイト
ドライバパーティションマップ (2048 バイトブロック用)	512 バイト
ドライバパーティションマップ (512 バイトブロック用)	512 バイト
空き領域	512 バイト
ドライバパーティション	N x 2048 バイト
HFS パーティションブートブロック	1024 バイト
.TE
.PP
Perl スクリプト
.I hdisk.pl
を使えば、Mac の CD の内容をリストできる。
hdisk.pl は hfsutils に含まれている。
.SH 注意
Apple CD に含まれるドライバを使って
Apple のソフトウェアを CD にコピーする場合は、
アップルコンピュータのソフトウェア使用許諾契約に従わなくてはならない。

.SH 関連項目
.IR mkhybrid (1)
.SH プログラマ
James Pearson (j.pearson@ge.ucl.ac.uk) 18/5/98
.PP
(ドライバの抽出とパーティションなどの作成を行う) ドライバのコードは、
Andy Polyakov <appro@fy.chalmers.se> の
.I mkisofs 1.05 PLUS
のコードに基づいている
(http://fy.chalmers.se/~appro/mkisofs_plus.html を参照)。
