.\" -*- nroff -*-
.\" Copyright 1998 Andries E. Brouwer (aeb@cwi.nl)
.\"
.\" May be distributed under the GNU General Public License
.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Feb 17 04:25:09 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.\"WORD:	readahead	先読み
.\"
.TH BLOCKDEV 8 "May 2000" ""
.SH 名前
blockdev \- コマンドラインからブロックデバイスの ioctl を呼び出す
.SH 書式
.B blockdev
.RI [ options ]
.I commands devices
.SH 説明
.B blockdev
ユーティリティは、
コマンドラインからブロックデバイスの ioctl を呼び出すことを可能にする。
.SH オプション
.TP
.B \-V
バージョンを表示して終了する。
.TP
.B \-q
静かにする (訳注: 余分な表示をしない)。
.TP
.B \-v
詳細に表示する。
.SH コマンド
.TP
.B \--setro
読み込みだけを許可するように設定する。
.TP
.B \--setrw
読み書きを許可するように設定する。
.TP
.B \--getro
読み込みだけが許可されているかの情報を取得する。
デバイスが読み込みだけの許可である場合は、1 を表示する。
それ以外の場合は、0 を表示する。
.TP
.B \--getss
セクタサイズをバイト単位で表示する - 通常は 512 バイトである。
.TP
.B \--getsize
デバイスの容量を (512 バイトセクタ単位で) 表示する。
.TP
.BI \--setra " N"
先読み (readahead) の大きさを 512 バイトセクタ単位で
.I N
セクタに設定する。
.TP
.B \--getra
先読みの大きさを (512 バイトセクタ単位で) 表示する。
.TP
.B \--flushbufs
バッファをフラッシュする。
.TP
.B \--rereadpt
パーティションテーブルの再読み込みを行う。
