.\"
.\" Japanese Version Copyright (c) 2004 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat May 15 18:06:37 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.\"WORD:
.\"
.TH CONVERTQUOTA 8 "Fri Aug 20 1999"
.UC 4
.SH 名前
convertquota \- quota を古いフォーマットから新しいフォーマットに変換する
.SH 書式
.B convertquota
[
.B -ug
] [
.B -e
|
.B -f
]
.I filesystem
.SH 説明
.B convertquota
は、
.I filesystem
にある古い quota ファイル
.B quota.user
と
.B quota.group
を、2.4.0-ac? 以降や SuSE または Red Hat Linux の
カーネル 2.4 で現在使われている新しいフォーマットのファイル
.BR aquota.user
と
.BR aquota.group
に変換する。
.PP
新しいファイルフォーマットでは、
32 ビットのユーザー ID・グループ ID の使用、root に対する quota 設定、
バイト単位での使用容量の集計 (さらに ReiserFS での quota の使用) が可能であり、
アーキテクチャに依存しない。
このフォーマットでは、quota ファイルに Radix ツリー
(簡単な形式のツリー構造) が導入された。
.SH オプション
.TP
.B -u
ユーザー quota ファイルを変換する。
これがデフォルトである。
.TP
.B -g
グループ quota ファイルを変換する。
.TP
.B -f
古いファイルフォーマットから新しいファイルフォーマットへ変換する。
これがデフォルトである。
.TP
.B -e
新しいファイルフォーマットを
ビッグエンディアンからリトルエンディアンに変換する。
.TP
.B -V
バージョン情報を表示する。
.SH ファイル
.TP 20
.B aquota.user
新しいユーザー quota ファイル。
.TP
.B aquota.group
新しいグループ quota ファイル。
.SH 関連項目
.BR quota (1),
.BR setquota (8),
.BR edquota (8),
.BR quotacheck (8),
.BR quotaon (8),
.BR repquota (8)
.SH 著者
Jan Kara \<jack@suse.cz\>
