.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH CTRLALTDEL 8 "25 October 1993" "Linux 1.2" "Linux Programmer's Manual"
.SH 名前
ctrlaltdel \- Ctrl-Alt-Del 機能の設定
.SH 書式
.BR "ctrlaltdel hard" " | " soft
.SH 説明
以下の記述は、
.I linux/kernel/sys.c
のコードを調べた結果に基づくものである。Ctrl-Alt-Del シーケンスで呼び出
せる機能には、次の2 つがある。

.I hard 
リセット。
.B sync (2)
および、その他の準備を行なわずに即座にコンピュータをリブートさせる。

.I soft
リセット。
.B init
プロセス(このプロセス ID は常に 1 である)に対して SIGINT (割り込み)シ
グナルを送信する。このオプションを使用するためには、
.B init
が、この機能をサポートしていなくてはならない。 現在の Linux 界では、
いくつかの
.I init
プログラムが存在するので、現在使っているバージョンのドキュメントを良く
確認すること。

.B ctrlaltdel
は、通常
.I /etc/rc.local
ファイル中で使用される。
.SH ファイル
.I /etc/rc.local
.SH 関連項目
.BR simpleinit (8),
.BR init (8)
.SH 著者
Peter Orbaek (poe@daimi.aau.dk)
.SH 翻訳
福場\ 浩壮 <koso@ga2.so-net.or.jp>
.\" Translate ctrlaltdel.8, 25 October 1993, most recently updated 
.\" by Rickard E. Faith (faith@cs.unc.edu), taken from 
.\" util-linux-2.5.tar.gz
.\"
.\" Japanese Version Copyright (c) 1997 Koso Fukuba
.\"         all rights reserved.
.\" Translated Mon Jan 27 12:00:00 JST 1997
.\"         by Koso Fukuba <koso@ga2.so-net.or.jp>


