.\"	dhcrelay.8
.\"
.\" Copyright (c) 1997 The Internet Software Consortium.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of The Internet Software Consortium nor the names
.\"    of its contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE INTERNET SOFTWARE CONSORTIUM AND
.\" CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE INTERNET SOFTWARE CONSORTIUM OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" This software has been written for the Internet Software Consortium
.\" by Ted Lemon <mellon@fugue.com> in cooperation with Vixie
.\" Enterprises.  To learn more about the Internet Software Consortium,
.\" see ``http://www.isc.org/isc''.  To learn more about Vixie
.\" Enterprises, see ``http://www.vix.com''.
.\"
.\" Japanese Version Copyright (c) 2001 NAKANO Takeo all rights reserved.
.\" Translated Thu Dec 27 2001 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH dhcrelay 8
.SH 名前
dhcrelay \- Dynamic Host Configuration Protocol (動的ホスト設定プロトコル) 中継エージェント
.SH 書式
.B dhcrelay
[
.B -p
.I port
]
[
.B -d
]
[
.B -q
]
[
.B -i
.I if0
[
.B ...
.B -i
.I ifN
]
]
.I server0
[
.I ...serverN
]
.SH 説明
Internet Software Consortium DHCP 中継エージェント dhcrelay は、
DHCP サーバが直接には接続されていないサブネットからの
DHCP 要求や BOOTP 要求を、他のサブネットにある 1 つまたは複数の
DHCP サーバに中継する手段を提供します。
.SH 動作
.PP
この DHCP 中継エージェントは、
.I -i
フラグで 1 つまたは複数のインターフェースが指定された場合を除き、
ホストに接続されたすべてのインターフェースで DHCP 要求を待ち受けます。
.PP
要求を受信すると、dhcrelay はその要求を、
コマンドラインで指定された DHCP サーバのリストへ転送します。
そこから返答を受けとると、
その返答はもともとの要求が来たネットワークに
ブロードキャストまたはユニキャストされます。
.PP
dhcrelay が待機する (1 つまたは複数の)
インターフェースを指定することもできます。
これを用いれば、dhcrelay の接続先のネットワークが、
あるインターフェース経由では DHCP サーバのいないもの、
また別のインターフェース経由では DHCP サーバがいるもの、
のようになっている場合に、
サーバがいる側のネットワークからの要求を
そのサーバに転送するようなことはしないようにできます。
これは完全な解決法ではありませんが。
.SH コマンドライン
.PP
dhcrelay が待機するよう設定したいネットワークインターフェースの名前は、
コマンドラインの
.B -i
オプションを用いて指定できます。
コマンドラインでひとつもインターフェース名が指定されないと、
dhcrelay はすべてのネットワークインターフェースを用います。
ただしブロードキャストできないインターフェースは可能な場合は除き、
それから各インターフェースを設定します。
.PP
dhcrelay を標準のポート (ポート 67) 以外で待機させたい場合は
.B -p
フラグで指定できます。この後には dhcrelay を待機させる
udp のポート番号を書きます。これはデバッグの用途に特に便利です。
.B -p
フラグが指定されると、この中継エージェントは指定した番号よりも
1 つ大きなポート番号を用いてクライアントに返事を送ります。
つまり
.BR -p " 67"
を指定した場合は、dhcrelay はポート 67 を聴き、
ポート 67 に返事を送ります。サーバへの中継は、
.B -p
フラグで指定したのと同じポート番号に送信されます。
.PP
dhcrelay は通常インターフェースを設定するまではフォアグラウンドで動作し、
これが終了するとバックグラウンドに移動します。
dhcrelay を常にフォアグラウンドで動作させるには、
.B -d
フラグを指定します。これは dhcrelay をデバッガの下で動作させたり、
System V システムの inittab 以外から動作させる場合に便利です。
.PP
dhcrelay は、起動時にネットワーク設定を表示します。
これはシステムの起動スクリプトなどでは邪魔かもしれません。
この動作を無効にするには
.B -q
フラグを指定します。
.PP
DHCP 要求や BOOTP 要求の転送先となる DHCP サーバの名前は、
少なくとも 1 つ以上コマンドラインで指定しなければなりません。
.PP
.SH 関連項目
dhclient(8), dhcpd(8), RFC2132, RFC2131.
.SH 著者
.BR dhcpd (8)
は Ted Lemon <mellon@vix.com>
が Vixie Enterprises と協力のもと
Internet Software Consortium のために書きました。
Internet Software Consortium の情報は
.B http://www.isc.org/isc
にあります。
Vixie Enterprises の情報は
.B http://www.vix.com
にあります。
