.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" ifuser.8 1.6 2000/06/12 21:24:48
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun May 14 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated Tue Oct 24 20:08:41 JST 2000
.\"	by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH IFUSER 8 "2000/06/12 21:24:48" "pcmcia-cs"
.SH 名前
ifuser \- ネットワークインターフェースから指定先への経路があるかどうかを調べる
.\"nakano: 「指定した」が続くとあれなので、particular は無視。
.SH 書式
.B ifuser
.RB [ -v ]
.I interface
.RI [ "target\ ..." ]
.SH 書式
このユーティリティは、
指定したインターフェースから
リストしたホストアドレスやネットワークアドレスへの経路が
存在するかどうかをチェックする。
到達先は IP アドレスでも名前でも指定できる。
.PP
終了コードは、リストしたネットワークやホストのいずれかに到達する経路が、
このインターフェースを通っていれば 0、
このインターフェースを使わなければ 1 である。
.RB ( fuser
と似ている)。
.SH オプション
.TP
.B \-v
詳細表示モード: 有効だと、このインターフェースから経路があった行き先があれば、
その名前を標準出力にレポートする。
.SH 著者
David Hinds \- dahinds@users.sourceforge.net
.br
Regis "HPReg" Duchesne \- regis@via.ecp.fr
