.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH IPCS 8 "9 October 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 名前
ipcs \- IPC リソース情報の表示
.SH 書式
.B ipcs [ \-asmq ] [ \-tclup ]
.br
.BI "ipcs [ \-smq ] \-i " id
.br
.B ipcs \-h
.SH 説明
.B ipcs
は、IPC リソース機能に関する情報を出力する。

.B \-i
を指定すると、後続の
.I id
で指定されたリソースの情報だけが出力される。

リソースの指定は次のようになる:
.TP
.B \-m
シェアードメモリセグメントを指定する。
.TP
.B \-q
メッセージキューを指定する。
.TP
.B \-s
セマフォを指定する。
.TP
.B \-a
すべてのリソースの情報が出力される(これは、省略時の動作である)。
.PP
出力フォーマットの指定は、次のようになる:
.TP
.B \-t
リソースが最後に変更された時間を出力する。
.TP
.B \-p
リソースの所有、作成、最終変更を示すプロセスIDを出力する。
.TP
.B \-c
リソースの作成ユーザーおよびグループの情報を出力する。
.TP
.B \-l
各リソースの上限値を出力する。
.TP
.B \-u
各リソースの使用状況を示すサマリが出力される.
.SH 関連項目
.BR ipcrm (8)
.SH 著者
krishna balasubramanian (balasub@cis.ohio-state.edu)
.SH 翻訳
福場\ 浩壮 <koso@ga2.so-net.or.jp>
.\" Translate ipcs.8, 9 Oct. 1993 most recently update by 
.\" Rickard E. Faith (faith@cs.unc.edu), taken from util-linux-2.5.tar.gz
.\"
.\" Japanese Version Copyright (c) 1997 Koso Fukuba
.\"         all rights reserved.
.\" Translated Mon Jan 27 12:00:00 JST 1997
.\"         by Koso Fukuba <koso@ga2.so-net.or.jp>
