.\" Copyright (C) 1999 David A. Hinds -- dahinds@users.sourceforge.net
.\" lspnp.8 1.4 2000/06/12 21:24:49
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun May 14 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated Tue Oct 24 20:08:41 JST 2000
.\"	by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.TH LSPNP 8 "2000/06/12 21:24:49" "pcmcia-cs"
.SH 名前
lspnp \- Plug & Play BIOS のデバイスノードとリソースをリストする
.SH 書式
.B lspnp
.RB [ -b ]
.RB [ -v [ v ]]
.RI [ "device ..." ]
.SH 説明
このユーティリティは
.I /proc/bus/pnp
ツリーの内容を解釈し、整形して表示する。
デフォルトの出力は Plug & Play デバイスのノード番号・
プロダクト識別子・記述、である。
詳細出力モード
.RB ( \-v )
を指定すると、各デバイスに割り当てられているリソース
(I/O ポート・メモリ・割り込み・DMA チャネル) も表示される。
さらに詳細な出力モード
.RB ( \-vv )
を指定すると、割り当て可能なリソース・様々な設定フラグ・
互換デバイスのプロダクト識別子なども表示される。
.PP
出力対象とするデバイスノードを限ることもできる。
これには 2 桁 16 進のノード番号をコマンドラインから指定する。
デフォルトでは現在の (動的な) デバイス設定情報が表示される。
.B \-b
オプションを指定すると、ブート時の (静的な) 設定が表示される。
.SH オプション
.TP
.B \-b
ブートモード: デバイスのリソース情報を読み込む。
これが次回のブートで (現在のリソース情報の代わりに) 使われることになる。
.TP
.B \-v
より詳細な出力を行う。複数指定することもできる。
.SH ファイル
.TP
/usr/share/pnp.ids
既知の Plug & Play デバイス ID のデータベース
.TP
/proc/bus/pnp/...
Plug & Play BIOS デバイスサービスのカーネルインターフェース
.SH 著者
David Hinds \- dahinds@users.sourceforge.net
.SH 関連項目
.BR setpnp (8)

