.\"
.\" nfsstat(8)
.\" 
.\" Copyright (C) 1996 Olaf Kirch <okir@monad.swb.de>
.\"
.\" Japanese Version Copyright (c) 2002 NAKANO Takeo all rights reserved.
.\" Translated Sun 29 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH nfsstat 8 "05 Oct 2001"
.SH 名前
nfsstat \- NFS の統計情報を表示する
.SH 書式
.BI "/usr/sbin/nfsstat [-anrcsz] [-o " "facility" "] ...
.SH 説明
.B nfsstat
は NFS クライアントとサーバの動作に関して保存されている統計を表示する。
.SH オプション
.TP
.B -s
サーバ側の統計のみを表示する。
デフォルトではサーバとクライアント両者の統計を表示する。
.TP
.B -c
クライアント側の統計のみを表示する。
.TP
.B -n
NFS の統計のみを表示する。
デフォルトでは NFS と RPC 両者の情報を表示する。
.TP
.B -r
RPC の統計のみを表示する。
.TP
.BI -o " facility
指定した
.I facility
の統計のみを表示する。以下のうちのひとつを指定できる。
.RS
.TP
.B nfs
RPC コールを除く、NFS プロトコルの情報。
.TP
.B rpc
一般的な RPC 情報
.TP
.B net
ネットワーク層の統計。
例えば受信パケットの数、TCP 接続回数など。
.TP
.B fh
サーバのファイルハンドルキャッシュの利用情報。
ルックアップの回数、ヒットとミスの回数を含む。
.TP
.B rc
サーバのリクエスト返信用キャッシュの利用情報。
ルックアップの回数、ヒットとミスの回数を含む。
.RE
.\" --------------------- FILES ----------------------------------
.SH ファイル
.TP
.B /proc/net/rpc/nfsd
\fBprocfs\fP ベースの kernel NFS サーバ統計へのインターフェース。
.TP
.B /proc/net/rpc/nfs
\fBprocfs\fP ベースの kernel NFS クライアント統計へのインターフェース。
.\" -------------------- SEE ALSO --------------------------------
.SH 関連項目
.BR rpc.nfsd (8)
.\" -------------------- AUTHOR ----------------------------------
.SH 著者
Olaf Kirch, <okir@monad.swb.de>
