.\"
.\" Japanese Version Copyright (c) 2005 Yuichi SATO
.\"         all rights reserved.
.\" Translated Fri Dec 30 11:30:07 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH NHFSNUMS 8 "26 Feb 2000"
.SH 名前
nhfsnums \- 
.B nhfsrun
の出力を
.BR plot (5)
用に変換する
.SH 書式
.B nhfsnums <numsfiles>
.SH 説明
nhfsstone が出力した生の数値を
.BR plot (5)
フォーマットに変換する。
.B <numsfiles>
は
.B run.xxx
という名前にすべきである。
ここで
.B xxx
は数値を集計するときに関係する名前である。
各ファイルはラベルの付いた 1 行を生成する。
このラベルはファイルのサフィックス (ドットの後ろの部分) である。
.SH 関連項目
.BR nhfsstone (8),
.BR nhfsrun (8),
.BR nhfsgraph (8)
