.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Mon Mar 12 18:41:53 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.\"WORD:
.\"
.TH PAPSTATUS 8 "17 Dec 1991"
.SH 名前
papstatus \- AppleTalk で接続されたプリンタの状態を取得する
.SH 書式
.B /usr/sbin/papstatus
[
.BI -d
] [
.B -p
.I printer
] [
.I retrytime
]
.SH 説明
.B papstatus
は AppleTalk で接続されたプリンタから
現在の状態メッセージを取得するのに使われる。
状態情報の取得には
プリンタアクセスプロトコル (Printer Access Protocol, PAP) が使われる。
.LP
コマンドラインでプリンタが指定されてない場合、
.B papstatus
はカレントディレクトリの中の
.B .paprc
という名前のファイルを探し、
このファイルを読んでプリンタ名を取得する。
.B .paprc
には
.IB object : \c
.IB type @ \c
.I zone
という形式の単一の行がなければいけない。
ここで、
.IR object ,
.BI : type ,
.BI @ zone
はオプションである。
.I type
と
.I zone
の前には、それぞれ
.RB ` : '
と
.RB ` @ '
がなければいけない。
空行と
.RB ` # '
で始まる行は無視される。
.I type
と
.I zone
のデフォルトは、それぞれ
.B LaserWriter
とローカルホストのゾーンである。
.SH オプション
.TP
.B -d
デバッグモードを有効にする。追加情報が標準エラーに表示される。
.HP
.B -p
.I printer
.br
.I printer
から状態を取得する
(プリンタ名を見付けるために
.B .paprc
ファイルを参照しない)。
.I printer
の書式は、上の
.B .paprc
ファイルで述べたものと同じである。
.TP
.I retrytime
通常、
.B papstatus
はプリンタから 1 度しか状態を取得しない。
.I retrytime
が指定されると、プリンタへの問い合わせの間に
.I retrytime
秒間スリープして、繰り返し状態を取得する。
.SH ファイル
.TP 20
.B .paprc
プリンタ名が書かれたファイル
.SH 関連項目
.BR nbp (1),
.BR pap (8)
