.\" This page is originally in the SysVinit package.
.\"
.\" Translated Fri 14 Feb 1997 by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Sat  6 May 2000 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH PIDOF 8 "01 Sep 1998" "" "Linux System Administrator's Manual"
.SH 名前
pidof \- 実行中のプログラムのプロセスIDを調べる。
.SH 書式
.B pidof
.RB [ \-s ]
.RB [ \-x ]
.RB [ \-o
.IR omitpid ]
.RB [ \-o
.IR omitpid.. ]
.B program
.RB [ program.. ]
.SH 説明
.B pidof
は指定されたプログラムのプロセス ID(PID)を調べ、結果を標準出力に書き出す。
このプログラムはランレベルを変更するスクリプトの中で用いられる
ことがある。特に\fISystem-V\fP 形式の \fIrc\fP 構造を採用している
システムでよく用いられる。
そのような場合、これらのスクリプトは、/etc/rc.?d に置かれている
(?はランレベルを表す)。
システムに
.B start-stop-daemon
(8) プログラムがある場合は代わりにそちらを用いるべきである。
.SH オプション
.IP -s
単発動作 - (同名のプロセスが複数あっても)PID を一つだけ返す。
.IP -x
スクリプトも - 指定したスクリプトを実行しているシェルのプロセスID も返す。
.IP "-o \fIomitpid\fP"
指定したpidを持つプロセスは表示しない。
\fIpidof\fPの親プロセス、言い換えればpidofを呼び出した
シェル又はシェルスクリプトのpidとして、
\fB%PPID\fPという特別なpidを用いることもできる。
.SH 注意
\fIpidof\fPは\fIkillall5\fPプログラムへの単なる(シンボリック)リンク
にすぎない。
\fIkillall5\fPも\fI/sbin\fPに置かれているはずである。
.PP
PID を調べたいプログラムのフルパスを指定して \fIpidof\fP を起動した場合は
まず安全である。そうでない場合、
調べたいプログラムとたまたま名前が同じだが実際には違うプログラムの PID を
返してしまう可能性がある。
.SH 関連項目
.BR shutdown (8),
.BR init (8),
.BR halt (8),
.BR reboot (8)
.SH 著者
Miquel van Smoorenburg, miquels@cistron.nl

