.\"
.\" Japanese Version Copyright (c) 2004 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat May 15 19:52:27 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH QUOT 8
.SH 名前
quot \- ファイルシステムの所有者を要約する
.SH 書式
.nf
\f3quot\f1 [ \f3\-acfguvi\f1 ] [ filesystem... ]
.fi
.SH 説明
.I quot
は指定された
.I filesystem
で各ユーザーとグループに現在所有されている
(ファイルの) キロバイト数を表示する。
このユーティリティは現在のところ XFS でしか動作しない点に注意すること。
.SH オプション
.TP
.B \-a
マウントされた全てのファイルシステムについて、
各ユーザーとグループが使用している
キロバイト数を表示するレポートを生成する。
.TP
.B \-c
キロバイト単位のファイルサイズ、
そのサイズのファイル数、
そのサイズまたはそれ以下のサイズのファイルの合計のキロバイト数、
という 3 つの列を表示する。
最後の行は、溢れたものを入れるバケツとして使われ、
500 キロバイト以上の全ファイルの合計を表示する。
.TP
.B \-f
各ユーザーまたはグループに所有されるファイルの
キロバイト数とファイル数を表示する。
.TP
.B \-g
グループについて報告する。
.TP
.B \-u
ユーザーについて報告する (これがデフォルトである)。
.TP
.B \-v
最近 30, 60, 90 日の間にアクセスされていないファイルの
キロバイト数を含む 3 つの列を表示する。
.TP
.B \-i
automount でマウントされたマウントポイントを無視する。
.TP
.B \-T
8 文字以上のユーザー名を切り詰めない。
.TP
.B \-q
出力をソートしない。
.SH ファイル
.PD 0
.TP 20
/etc/mtab
マウントされたファイルシステムのテーブル。
.TP
/etc/passwd
デフォルトのユーザーのセット。
.TP
/etc/group
デフォルトのグループのセット。
.PD
.SH 関連項目
du(1),
ls(1).
.SH バグ
現在のところ XFS ファイルシステムタイプのみがサポートされている。
