.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)renice.8	8.1 (Berkeley) 6/9/93
.\"
.\" Japanese Version Copyright (c) 1998 Kanda Mitsuru
.\"         all rights reserved.
.\" Translated Nov 6 JST 1998
.\"         by Kanda Mitsuru <kanda@@nn.iij4u.or.jp>
.Dd June 9, 1993
.Dt RENICE 8
.Os BSD 4
.Sh 名前
.Nm renice
.Nd 実行しているプロセスの優先順位を変更する
.Sh 書式
.Nm renice
.Ar priority
.Oo
.Op Fl p
.Ar pid ...
.Oc
.Oo
.Op Fl g
.Ar pgrp ...
.Oc
.Oo
.Op Fl u
.Ar user ...
.Oc
.Sh 説明
.Nm renice
は動作中のプロセスのスケジューリング優先順位を変更する
(複数のプロセスを同時に変更することもできる)。
以下の
.Ar who
パラメータは、プロセス ID、プロセスグループ ID、もしくはユーザ名と
して解釈される。
プロセスグループを
.Nm renice 
すると、
そのグループに属する全てのプロセスのスケジューリング優先順位が変更される。
ユーザ名に対する
.Nm renice
を行うと、
そのユーザが所有している全てのプロセスのスケジューリング優先順位が
変更される。
デフォルトでは、プロセス ID によって指定されたプロセスが処理対象となる。
.Pp
.Nm renice 
のサポートするオプションは以下の通り:
.Bl -tag -width Ds
.It Fl g
強制的に
.Ar who
パラメータをプロセスグループの ID として解釈する。
.It Fl u
強制的に
.Ar who
パラメータをユーザ名として解釈する。
.It Fl p
.Ar who
がプロセス ID として解釈されるようにリセットする
(これはデフォルトの解釈である)。
.El
.Pp
例えば
.Bd -literal -offset
renice +1 987 -u daemon root -p 32
.Ed
.Pp
プロセス ID 987 と 32 の優先度と、ユーザ daemon と root によって
所有されている全てのプロセスの優先度を変更する。
.Pp
スーパーユーザでないユーザは、
自分が所有しているプロセスの優先度しか変更できない。
また ``nice 値'' を増やすことしかできない。
増やせる値は 0 から
.Dv PRIO_MAX
(20)
までの範囲である。
(これは最重要なシステム管理命令を妨げないためである)
スーパーユーザはあらゆるプロセスの優先度を変更でき、
.Dv PRIO_MIN
(\-20)
から
.Dv PRIO_MAX
の範囲で優先度の値を変更できる。
便利な優先度は:
20 (影響されたプロセスは、システムに実行するものがない場合だけ実行される)
0 (``基本'' のスケジューリング優先度)、
負の値 (とても早く実行される)
.Sh ファイル
.Bl -tag -width /etc/passwd -compact
.It Pa /etc/passwd
ユーザ名とユーザIDの対応を取る。
.El
.Sh 関連項目
.Xr getpriority 2 ,
.Xr setpriority 2
.Sh バグ
スーパユーザでないユーザは、一度スケジューリング優先度を
減らされたプロセスに関しても、これを増やすことはできない。
.br
linux カーネル (現在 2.0.0) と linux libc (現在 5.2.18) とでは、
nice 値を設定するシステムコールのインターフェースが完全に同じでない。
したがって renice は 変更前の nice 値として正しい値を返さないことがある。
.Sh 履歴
.Nm renice
は
.Bx 4.0
から登場した。
