.\" Copyright (c) 1983, 1989, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)rshd.8	6.11 (Berkeley) 4/20/91
.\"	$Id: rshd.8,v 1.1.1.1 2000/10/19 08:22:16 ysato Exp $
.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Jan 14 21:16:31 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.Dd April 20, 1991
.Dt RSHD 8
.Os "Linux NetKit (0.17)"
.Sh 名前
.Nm rshd
.Nd リモートシェルのサーバ
.Sh 書式
.Nm rshd
.Op Fl ahlnL
.Sh 説明
.Nm rshd
サーバは、
.Xr rcmd 3
ルーチンのためのサーバであり、
結果として
.Xr rsh 1
プログラムを実行するためのサーバである。
このサーバは、信頼できるホストからの特権ポート番号に基づいた認証を使い、
リモート実行機能を提供する。
.Pp
.Nm rshd
サーバは、``cmd'' サービスの仕様で指定されているポートで、
サービス要求を待つ。
.Xr services 5
を参照すること。
サービス要求を受信すると、以下の手順を開始する:
.Bl -enum
.It
サーバは、クライアントの要求元ポートをチェックする。
要求元ポートが 512 〜 1023 の範囲にない場合、
サーバは接続を中止する。
.It
サーバは、ソケットからヌルバイト (`\e0') を検出するまで文字を読み込む。
読み込んだ文字列は、
.Tn ASCII
文字からなる 10 進数の数字として解釈される。
.It
ステップ 2 で受信した数値が 0 でない場合、
.Em 標準エラー
で使う 2 番目のストリームのポートとして解釈される。
そして、2 番目の接続が指定されたポートでクライアントマシン上に生成される。
この 2 番目の接続の要求元ポートも 512 〜 1023 の範囲である。
.It
サーバは、クライアントの要求元アドレスをチェックし、
対応するホスト名を要求する
.Ns ( Xr gethostbyaddr 3 ,
.Xr hosts 5 ,
.Xr named 8 
を参照すること)。
ホスト名が特定できない場合、
ドット表記法によるホストアドレスが使われる。
ホスト名がサーバと同じドメイン名のものである場合
(ドメイン名の後ろから 2 つが同じ場合)、
または
.Fl a
オプションが指定されている場合、
ホスト名に対応するアドレスが要求され、
ホスト名とアドレスが対応しているかを確認する。
アドレス確認が失敗した場合、
``Host address mismatch.'' というメッセージを出して、接続を中止する。
.It
ヌル文字で終端された最大 16 文字のユーザー名を、
最初のソケットから取得する。
ユーザー名は、
.Em クライアント
マシン上でユーザーを識別するために解釈される。
.It
ヌル文字で終端された最大 16 文字のユーザー名を、
最初のソケットから取得する。
ユーザー名は、
.Em サーバ
マシン上でユーザーを識別するために解釈される。
.It
ヌル文字で終端されたシェルに渡されるコマンドを、
最初のソケットから取得する。
コマンドの長さは、システムの引き数リストの上限に制限される。
.It
.Nm rshd
は
.Xr ruserok 3
を使ってユーザーを確認する。
このプログラムは
.Pa /etc/hosts.equiv 
ファイルと、ユーザーのホームディレクトリにある
.Pa .rhosts
ファイルを使う。
.Fl l
オプションは、
.Xr ruserok 3
に、ユーザー ``.rhosts'' ファイルに基づいた確認を行わせない
(ユーザーがスーパーユーザーである場合と、
.Fl h 
オプションが使われた場合を除く)。
.Fl h
オプションが指定されない場合、
スーパーユーザーアカウントは、このサービスでは全く使われない。
.Pp
.Fl l
オプションは、
システムにインストールされている特定のバージョンの libc で
動作するかを確認せずに信用すべきではない
(また、libc を更新した後もテストすべきである)。
なぜなら、libc のいくつかのバージョンでは
.Nm rshd
が使うフラグが信用できない。
.Pp
また、
.Pa .rhosts
システムの設計は、慎重にファイアウォールで囲まれた
プライベートネットワーク以外では、
「全くもって安全でない」ことに注意すること。
それ以外の環境では
.Nm rshd
を完全に無効にすべきである。
.Pp
.It
ヌル文字のバイトが最初のソケットから返され、
コマンド行がユーザーの通常のログインシェルに渡される。
このシェルは
.Nm rshd
によって確立されたネットワーク接続を拒否する。
.El
.Pp
トランスポートレベルのキープアライブメッセージは、
.Fl n
オプションが指定されない限り、有効である。
キープアライブメッセージを使うと、
クライアントがクラッシュしたり到達不能になった場合に、
セッションをタイムアウトすることができる。
.Pp
.Fl L
オプションを使うことで、
全ての正常なアクセスを
.Xr syslogd 8
を経由して
.Li auth.info
メッセージとしてログに記録できる。
また、全ての失敗したアクセスを
.Li auth.notice
としてログに記録できる。
.Sh 返り値
以下にリストしたもののうち最後のものを除き、
全ての診断メッセージを最初のソケットを使って返した後、
全てのネットワーク接続を閉じる。
エラーは、先頭に値 1 のバイトをつけることで示される
(ログインシェル実行前の全てのステップが正常に完了した場合、
上記のステップ 9 で 0 が返される)。
.Bl -tag -width indent
.It Sy Locuser too long.
クライアントマシン上のユーザー名が、16 文字を超えている。
.It Sy Ruser too long.
リモートマシン上のユーザー名が、16 文字を超えている。
.It Sy Command too long  .
渡されたコマンドラインの長さが、(システムで設定された)
引き数リストのサイズを超えている。
.It Sy Remote directory.
ホームディレクトリへの
.Xr chdir
コマンドが失敗した。
.It Sy Permission denied.
上で説明した認証手続きが失敗した。
または、要求されたユーザー要求が存在しなかった
(これらの条件は、故意に組み合わせた)。
.It Sy Can't make pipe.
.Em 標準エラー
に必要なパイプが作成できなかった。
.It Sy Can't fork; try again. 
サーバによる
.Xr fork
が失敗した。
.It Sy <shellname>: ...
ユーザーのログインシェルを起動できなかった。
このメッセージは、
.Em 標準エラー
に関係づけられた接続を経由して返されるので、
フラグバイトが前に付かない。
.El
.Sh 関連項目
.Xr rsh 1 ,
.Xr rcmd 3 ,
.Xr ruserok 3
.Sh バグ
ここで使われているユーザー認証手続きは、
クライアントマシンと接続媒体が完全であることを仮定している。
これは安全ではないが、「オープンな」環境では便利である。
.Pp
通信する全てのデータを暗号化する機能が提供されるべきである。
.Pp
(Telnet のような) もっと拡張性のあるプロトコルが用いられるべきである。
.Sh 翻訳者謝辞
この man ページの翻訳にあたり、
FreeBSD jpman project <http://www.jp.freebsd.org/man-jp/>
による翻訳を参考にさせていただいた。
