.\" This page is originally in the SysVinit package.
.\"
.\" Translated Fri 14 Feb 1997 by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Wed  3 May 2000 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH RUNLEVEL 8 "May 27, 1997" "" "Linux System Administrator's Manual"
.SH 名前
runlevel \- 現在及び一つ前のランレベルを調べる。
.SH 書式
.B runlevel 
.RI [ utmp ]
.SH 説明
.B runlevel
はランレベルレコードを調べるためにシステム
.I utmp
ファイル(一般には
.IR /var/run/utmp )
を読み込み、
現在及びその一つ前のシステムのランレベルを、標準出力
に一文字分のスペースを空けて表示する。
一つ前のランレベルが存在しない場合は、代わりに\fBN\fPという文字を表示する。
.PP
.I utmp
ファイルがない場合、またはランレベルレコードが見つからない場合、
\fBunknown\fP の文字を出力して、異常終了する。
.PP
.B runlevel
は、\fIrc\fPスクリプトの中でSystem-Vの\fPwho -r\fPコマンドの代わりに
使うことが出来る。
しかし、新しい版の\fBinit\fP(8)を使用している場合は
\fBRUNLEVEL\fP及び\fBPREVLEVEL\fPという環境変数から
これらの情報を得ることも出来る。
.SH オプション
.\"{{{ utmp
.IP \fIutmp\fP 
読み込む\fIutmp\fPファイルの名前。
.\"}}}
.SH 関連項目
.BR init (8),
.BR utmp (5)
.SH 著者
Miquel van Smoorenburg, miquels@cistron.nl

