.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Path modifications by faith@cs.unc.edu
.TH SETSID 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 名前
setsid \- 新しいセッションでのプログラムの実行
.SH 書式
.BI setsid " program" " [ " "arg ..." " ]"
.SH 説明
.B setsid
は、新しいセッションでプログラムを実行する。
.SH 関連項目
.BR setsid (2)
.SH 著者
Rick Sladkey <jrs@world.std.com>
.SH 翻訳
福場\ 浩壮 <koso@ga2.so-net.or.jp>

.\" Japanese Version Copyright (c) 1997 Koso Fukuba
.\"         all rights reserved.
.\" Translated Mon Jan 27 12:00:00 JST 1997
.\"         by Koso Fukuba <koso@ga2.so-net.or.jp>
