.\" Copyright (c) 2000 David A. Holland.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by David A. Holland.
.\" 4. Neither the name of the Author nor the names of any contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND ANY CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR ANY CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: telnetlogin.8,v 1.1.1.1 2000/10/19 08:22:16 ysato Exp $
.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Jan 14 21:16:31 JST 2001
.\"         by Yuichi SATO <sato@complex.eng.hokudai.ac.jp>
.\"
.\"WORD:	wrapper		ラッパー
.\"
.Dd April 12, 2000
.Dt TELNETLOGIN 8
.Os "Linux NetKit (0.17)"
.Sh 名前
.Nm telnetlogin
.Nd telnetd のための login のラッパー
.Sh 書式
.Nm telnetlogin
.Op Fl h Ar host
.Op Fl p
.Sh 説明
.Nm telnetlogin
は、
.Xr login 1
を実行する setuid ラッパーである。
このプログラムは、
.Xr telnetd 8
から起動されることになっている。
この考えにより、telnetd を root として実行する必要性がなくなる。
.Pp
.Nm telnetlogin
はモード 4750, ユーザー root, グループ telnetd で
インストールされているべきである。
そうすれば、telnetd は
.Pa /etc/inetd.conf
から、ユーザー ``nobody'', グループ ``telnetd'' で、オプション
.Fl L Ar path-to-telnetlogin
をつけて実行できる。
.Pp
.Nm telnetlogin
は、上に示したような
.Xr login 1
のオプションの一部のみを、その順番で受け付ける。
これは、
.Xr telnetd 8
が通常このプログラムに与えるオプションの順番である。
さらに
.Nm telnetlogin
は、環境変数
.Ev TERM , 
.Ev DISPLAY , 
.Ev POSIXLY_CORRECT ,
.Ev REMOTEHOST
のみしか受け付けない。
標準入力・標準出力・標準エラーのストリームは、
端末上に開いていなければならない。
また、このプログラムは、フォアグラウンドプロセスの
プロセスグループリーダーでなければならない。
これら全ての条件をチェックした後、
上記の環境変数の値が正当な値であるかをチェックし、
シグナルハンドラをリセットするなどして、
login を実行する。
.Sh 関連項目
.Xr login 1 ,
.Xr inetd.conf 5 ,
.Xr inetd 8 ,
.Xr telnetd 8
.Sh 制限
.Nm telnetlogin
は login に対して
.Fl f
オプションの使用を許可しておらず、ユーザー名を渡すことも許されていない。
そのため、Kerberos や SSL を使って認証を行う
telnetd と一緒には使えない。
.Pp
このプログラムは、現在のところ実験的なコードである。
注意して使うこと。
.Sh 履歴
.Nm telnetlogin
は、NetKit 0.17 の開発のなかで書かれた。
