.\" This page is in the public domain
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Sat Aug 14 1999
.\"       by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated Wed Apr 4 2001
.\"       by Yuichi SATO <ysato@h4.dion.ne.jp>
.\" Updated & Modified Sun Dec 23 08:41:42 JST 2001 by Yuichi SATO
.\"
.\"WORD:	country code	国別コード
.\"
.TH TZSELECT 8 2007-05-18 "" "Linux System Administration"
.SH 名前
tzselect \- タイムゾーンを選択する
.SH 書式
.B tzselect
.SH 説明
.B tzselect
プログラムは、ユーザーが現在いる場所の情報を尋ねて、
その結果得られたタイムゾーンの表記を標準出力に表示する。
この出力は
.B TZ
環境変数の値にすると良い。
.PP
ユーザとの対話は、全て標準入力と標準エラー出力とで行われる。
.SH 返り値
ユーザからの入力によってタイムゾーンが正しく取得できた場合は 0 を
返す。それ以外の場合は 0 以外を返す。
.SH 環境
.TP
\fBAWK\fP
Posix 互換の
.I awk
プログラム (デフォルトは
.BR awk )。
.TP
\fBTZDIR\fP
タイムゾーンデータファイルが置かれているディレクトリの名前 (デフォルトは
.IR /usr/share/zoneinfo )。
.\" 古いシステムでは /usr/local/etc/zoneinfo だろう
.SH ファイル
.TP
\fBTZDIR\fP\fI/iso3166.tab\fP
2 文字の国別コード (countory code) と国の名前からなる ISO 3166 の表。
.TP
\fBTZDIR\fP\fI/zone.tab\fP
国別コード、経度・緯度、TZ の値、説明文からなる表。
.TP
\fBTZDIR\fP\fI/\fP\fITZ\fP
タイムゾーン \fITZ\fP に対するタイムゾーンデータのファイル。
.SH 関連項目
.BR tzfile (5),
.BR zdump (8),
.BR zic (8)
.\" @(#)tzselect.8	1.3
