.\" -*- nroff -*-
.\"
.\" Japanese Version Copyright (c) 2002 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Jan 26 17:15:15 JST 2002
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\"
.TH YPHELPER 8 "August 2001" "YP Server" "Reference Manual"
.SH 名前
yphelper \- 内部で使用するヘルパーアプリケーション
.SH 説明
.B yphelper
は ypserv 用の内部で使用するヘルパーアプリケーションである。
これは一般のユーザーやシステム管理者が使用すべきでない。
.SH 著者
.B yphelper
は Thorsten Kukuk <kukuk@suse.de> によって書かれた。
