.\" -*- nroff -*-
.\" Copyright (C) 1998, 1999, 2001 Thorsten Kukuk
.\" This file is part of the yp-tools.
.\" Author: Thorsten Kukuk <kukuk@suse.de>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 2 as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation,
.\" Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Tue Jul 27 1999 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH yppoll 8 "May 1998" "YP Tools 2.8"
.SH 名前
yppoll \- NIS マップのバージョンとマスターサーバーを返す。
.SH 書式
.B yppoll
[
.BI \-h " host"
]
[
.BI \-d " domain"
]
.I mapname
.LP
.SH 説明
.B yppoll
は以下に示すオプションに従って動作する。

.SH オプション
.TP
.BI \-h " host"
.I host
で走っている NIS サーバープロセスに問い合わせを行い、
.I mapname
に対する情報を取得する。
.I host
が指定されなかった場合は、
.BR ypwhich (1)
によって返されるデフォルトのサーバーに問い合わせを行う。
.TP
.BI \-d " domain"
.BR domainname (1)
が返すデフォルトのドメイン以外を指定する。
.SH 関連項目
.BR domainname (8),
.BR ypbind (8),
.BR ypcat (8),
.BR ypmatch (1),
.BR ypserv (8),
.BR yset (8),
.BR ypwhich (1)
.LP
.SH 著者
.B yppoll
は
.B yp-tools
パッケージの一部である。
.B yp-tools
パッケージは Thorsten Kukuk <kukuk@suse.de>
によって書かれた。
