.\" This page is in the public domain
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Tue Sep 14 1999
.\"       by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH ZDUMP 8 2007-05-18 "" "Linux System Administration"
.SH 名前
zdump \- タイムゾーンをダンプする
.SH 書式
.B zdump
[
.B \-v
] [
.B \-c
cutoffyear ] [ zonename ... ]
.SH 説明
.I zdump
は
コマンドラインで指定した
.I zonename
それぞれにおける現在時刻を表示する。
.PP
以下のオプションを指定できる:
.TP
.B \-v
コマンドラインで与えられた
.I zonename
それぞれに対して、指定可能な最低位の時刻値 (time value)、
最低位の時刻値の一日後の時刻、
見付かった時間不連続の一秒前と丁度その時刻、
最高位時刻値の一日前の時刻、
指定可能な最高位の時刻値、を表示する。
それぞれの行の末尾には、
与えられている時刻がサマータイム (Daylight Saving Time) なら
.B isdst=1
が、そうでなければ
.B isdst=0
が付加される。
.TP
.BI "\-c " cutoffyear
与えられた年の最初の頃における余計な出力を切り捨てる。
.SH 関連項目
.BR tzfile (5),
.BR zic (8)
.\" @(#)zdump.8	7.3
