.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 2006, Michael Kerrisk
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Japanese Version Copyright (c) 2006 Yuichi SATO
.\"         all rights reserved.
.\" Translated 2006-10-13 by Yuichi SATO <ysato444@yahoo.co.jp>, LDP v2.39
.\"
.TH FSTATAT 2 2009-12-13 "Linux" "Linux Programmer's Manual"
.SH 名前
fstatat \- ディレクトリファイルディスクリプタから相対的な位置にあるファイルの状態を取得する
.SH 書式
.nf
.B #include <fcntl.h>           /* AT_* 定数の定義 */
.B #include <sys/stat.h>
.sp
.BI "int fstatat(int " dirfd ", const char *" pathname ", struct stat *" \
buf ,
.BI "            int " flags );
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR fstatat ():
.PD 0
.ad l
.RS 4
.TP 4
glibc 2.10 以降:
_XOPEN_SOURCE\ >=\ 700 || _POSIX_C_SOURCE\ >=\ 200809L
.TP
glibc 2.10 より前:
_ATFILE_SOURCE
.RE
.ad
.PD
.SH 説明
.BR fstatat ()
システムコールは、この man ページで説明している違いがある以外は、
.BR stat (2)
と全く同じように動作する。

.I pathname
で指定されるパス名が相対パスである場合、
ファイルディスクリプタ
.I dirfd
で参照されるディレクトリからの相対パス名として解釈される
.RB ( stat (2)
では、相対パスは呼び出し元プロセスのカレントワーキングディレクトリからの
相対パスとなる)。

.I pathname
が相対パスであり、かつ
.I dirfd
が特別な値
.B AT_FDCWD
である場合、
.I pathname
は
.RB ( stat (2)
と同じように) 呼び出し元プロセスの
カレントワーキングディレクトリからの相対パス名として解釈される。

.I pathname
が絶対パスである場合、
.I dirfd
は無視される。

.I flags
は 0 または以下のフラグである。
.TP
.B AT_SYMLINK_NOFOLLOW
.I pathname
がシンボリックリンクの場合は、それを辿るのではなく、
.BR lstat (2)
と同様にリンク自身についての情報を返す
(デフォルトでは、
.BR fstatat ()
は
.BR stat (2)
と同様にシンボリックリンクを辿る)。
.SH 返り値
成功した場合、
.BR fstatat ()
は 0 を返す。
エラーの場合、\-1 が返されて、
.I errno
にはエラーを示す値が設定される。
.SH エラー
.BR stat (2)
と同じエラーが
.BR fstatat ()
でも起こる。
.BR fstatat ()
では、その他に以下のエラーが起こる:
.TP
.B EBADF
.I dirfd
が有効なファイルディスクリプタでない。
.TP
.B EINVAL
.I flags
に不正なフラグ値が指定された。
.TP
.B ENOTDIR
.I pathname
が相対パスで、かつ
.I dirfd
がディレクトリ以外のファイルを参照するファイルディスクリプタである。
.SH バージョン
.BR fstatat ()
は Linux カーネル 2.6.16 で追加された。
.SH 準拠
POSIX.1-2008.
Solaris には、これと同じようなシステムコールが存在する。
.SH 注意
.BR fstatat ()
が必要な理由については、
.BR openat (2)
を参照すること。
.SH 関連項目
.BR openat (2),
.BR stat (2),
.BR path_resolution (7),
.BR symlink (7),
