'\" t
.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (C) 2006 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Japanese Version Copyright (c) 2006 Akihiro MOTOKI all rights reserved.
.\" Translated 2006-07-16, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH MQ_GETSETATTR 2 2010-08-29 "Linux" "Linux Programmer's Manual"
.SH 名前
mq_getsetattr \- メッセージキューの属性を設定/取得する
.SH 書式
.nf
.B #include <sys/types.h>
.B #include <mqueue.h>
.sp
.BI "int mq_getsetattr(mqd_t " mqdes ", struct mq_attr *" newattr ","
.BI "                 struct mq_attr *" oldattr );
.fi
.SH 説明
このシステムコールを使用しないこと。

.BR mq_getattr (3)
と
.BR mq_setattr (3)
の実装に使用される低レベルのシステムコールである。
このシステムコールがどのように動作するかは
.BR mq_setattr (3)
の説明を参照のこと。
.SH 準拠
このインタフェースは非標準である。使用を避けること。
.SH 注意
glibc はこのシステムコールに対するラッパー関数を提供していない。
.BR syscall (2)
を使って呼び出すこと。
(実のところ、C ライブラリを書いているのでない限り、
決してこのシステムコールを呼び出さないこと!)
.SH 関連項目
.BR mq_getattr (3),
.BR mq_overview (7)
