.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Original text is in the public domain.
.\"
.\" FIXME The description of nfsservctl() on this page
.\" is woefully thin.
.\"
.\" Japanese Version is copyrighted. but can freely distribute.
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Sat Aug 30 14:47:25 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\"
.TH NFSSERVCTL 2 1997-07-16 "Linux" "Linux Programmer's Manual"
.SH 名前
nfsservctl \- カーネル nfs デーモンのためのインターフェース
.SH 書式
.nf
.B #include <linux/nfsd/syscall.h>
.sp
.BI "long nfsservctl(int " cmd ", struct nfsctl_arg *" argp ,
.BI "                union nfsctl_res *" resp );
.fi
.SH 説明
.nf
/*
 * nfsctl() によって理解されるコマンド
 */
#define NFSCTL_SVC          0    /* サーバープロセス */
#define NFSCTL_ADDCLIENT    1    /* NFS クライアントを追加 */
#define NFSCTL_DELCLIENT    2    /* NFS クライアンドを削除 */
#define NFSCTL_EXPORT       3    /* ファイルシステムのエクスポート */
#define NFSCTL_UNEXPORT     4    /* ファイルシステムのアンエクスポート */
#define NFSCTL_UGIDUPDATE   5    /* UID/GID マップの更新 */
#define NFSCTL_GETFH        6    /* (mountd で使用される) fh の取得 */

struct nfsctl_arg {
    int                       ca_version;     /* safeguard */
    union {
        struct nfsctl_svc     u_svc;
        struct nfsctl_client  u_client;
        struct nfsctl_export  u_export;
        struct nfsctl_uidmap  u_umap;
        struct nfsctl_fhparm  u_getfh;
        unsigned int          u_debug;
    } u;
}

union nfsctl_res {
        struct knfs_fh          cr_getfh;
        unsigned int            cr_debug;
};
.fi
.SH 返り値
成功した場合はゼロが返される。エラーの場合は \-1 が返され、
.I errno
が適切に設定される。
.SH 準拠
このコールは Linux 特有である。
