.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1992 Drew Eckhardt <drew@cs.colorado.edu>, March 28, 1992
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified by Michael Haardt <michael@moria.de>
.\" Modified 1993-07-24 by Rik Faith <faith@cs.unc.edu>
.\" Modified 1996-11-04 by Eric S. Raymond <esr@thyrsus.com>
.\" Modified 2001-06-04 by aeb
.\" Modified 2004-05-27 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Japanese Version Copyright (c) 1997 SUTO, Mitsuaki
.\"         all rights reserved.
.\" Translated 1997-06-26, SUTO, Mitsuaki <suto@av.crl.sony.co.jp>
.\" Updated 2001-06-25, Kentaro Shirakata <argrath@ub32.org>
.\" Updated 2005-09-03, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-10-07, Akihiro MOTOKI
.\"
.TH NICE 2 2007-07-26 "Linux" "Linux Programmer's Manual"
.SH 名前
nice \- プロセスの優先度を変更する
.SH 書式
.B #include <unistd.h>
.sp
.BI "int nice(int " inc );
.sp
.in -4n
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR nice ():
_BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE
.SH 説明
.BR nice ()
は
.I inc
の値を
.B nice
を呼んだプロセスの nice 値に加える
(nice 値が大きい数値ほど低い優先度を表す)。
負の数を指定する、つまり、以前よりも優先度を上げるという指定ができるのは
スーパーユーザーだけである。
nice 値の範囲については
.BR getpriority (2)
で説明されている。
.SH 返り値
成功した場合、新しい nice 値が返る (但し、下記の「注意」を参照)。
失敗した場合 \-1 が返り、
.I errno
がエラーの内容に従って設定される。
.SH エラー
.TP
.B EPERM
スーパーユーザー以外が
.I inc
に負の数値を指定して優先度を上げようとした。
呼び出し元のプロセスが
.I inc
に負の数値を指定して優先度を上げようとしたが、
十分な権限を持っていなかった。
Linux では
.B CAP_SYS_NICE
ケーパビリティが必要である。
.RB ( setrlimit (2)
のリソース上限
.B RLIMIT_NICE
に関する議論も参照のこと)。
.SH 準拠
SVr4, 4.3BSD, POSIX.1-2001.
しかし、Linux と (2.2.4より古い) (g)libc では返り値は標準と異なる。
詳細は以下を参照のこと。
SVr4 には他に
.B EINVAL
エラーコードについての記述がある。
.SH 注意
SUSv2 と POSIX 1003.1-2003 では、
.BR nice ()
は新しい nice 値を返すと規定されている。
一方、Linux システムコールと (2.2.4 より古い) (g)libc ライブラリ関数は
成功時に 0 を返す。新しい nice 値は
.BR getpriority (2)
を使って取得できる。

glibc 2.2.4 以降では、
.BR nice ()
は
.BR getpriority (2)
を呼び出すライブラリ関数として実装されており、
呼び出し元に返す新しい nice 値を
.BR getpriority (2)
を呼び出して取得するようになっている。
この実装では、正常な動作でも \-1 が返される可能性がある。
確実にエラーを検出するためには、
呼び出しの前に
.I errno
に 0 を設定し、
.BR nice ()
が \-1 を返したときに errno をチェックすると良い。
.SH 関連項目
.BR nice (1),
.BR renice (1),
.BR fork (2),
.BR getpriority (2),
.BR setpriority (2),
.BR capabilities (7)
