.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 2004, Michael Kerrisk
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" 2004-05-40 Created by Michael Kerrisk <mtk.manpages@gmail.com>
.\" 2004-10-05 aeb, minor correction
.\"
.\" Japanese Version Copyright (c) 2005 Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2005-02-26, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	page cache	ページ・キャッシュ
.\"WORD:	file descriptor	ファイル記述子
.\"
.TH READAHEAD 2 2010-09-10 "Linux" "Linux Programmer's Manual"
.SH 名前
readahead \- 前もってファイルをページ・キャッシュに読み込む
.SH 書式
.nf
.BR "#define _GNU_SOURCE" "             /* feature_test_macros(7) 参照 */"
.B #include <fcntl.h>
.sp
.BI "ssize_t readahead(int " fd ", off64_t " offset ", size_t " count );
.fi
.SH 説明
.BR readahead ()
は、この後の同じファイルからのデータ読み込み時にディスク I/O で
動作が停止 (block) しないように、前もってファイルの内容を
ページ・キャッシュに読み込む。
.I fd
引き数は読み込みを行うファイルを識別するファイル・ディスクリプタである。
.I offset
引き数はデータの読み込み開始位置を指定し、
.I count
は読み込むデータのバイト数を指定する。
ディスク I/O はページ単位で実行されるので、
実際には
.I offset
はページ境界に切り下げられ、読み込みバイト数は
.I "(offset+count)"
より小さくない次のページ境界まで切り上げられる。
.BR readahead ()
はファイルの末尾を越えた範囲まで読み出しを行うことはない。また、
.BR readahead ()
は指定したデータの読み込みが終わるまで停止 (block) する。
.I fd
で参照されたオープン済のファイルのファイルオフセットの現在値は
変更されない。
.SH 返り値
.BR readahead ()
は成功すると 0 を返す。失敗した場合 \-1 を返し、
.I errno
にエラーの原因を示す値を設定する。
.SH エラー
.TP
.B EBADF
.I fd
が有効なファイル・ディスクリプタでない、または
読み込み用にオープンされていない。
.TP
.B EINVAL
.I fd
が参照しているファイルが、
.BR readahead ()
を行うことができないタイプのファイルであった。
.SH バージョン
.BR readahead ()
システムコールは Linux 2.4.13 で登場した。
glibc でのサポートは glibc バージョン 2.3 以降で行われている。
.SH 準拠
.BR readahead ()
システムコールは Linux 固有であり、移植を考慮したプログラムでは
使用を避けるべきである。
.SH 関連項目
.BR lseek (2),
.BR madvise (2),
.BR mmap (2),
.BR posix_fadvise (2),
.BR read (2)
