.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1995 Michael Chastain (mec@shell.portal.com), 15 April 1995.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Tue Oct 22 22:11:53 1996 by Eric S. Raymond <esr@thyrsus.com>
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Mon Mar  3 23:45:10 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\"
.\"WORD:	socket			ソケット
.\"WORD:	kernel			カーネル
.\"WORD:	entry			エントリ
.\"WORD:	hacker			ハッカー
.\"WORD:	library			ライブラリ
.\"
.TH SOCKETCALL 2 2007-06-28 "Linux" "Linux Programmer's Manual"
.SH 名前
socketcall \- ソケット・システムコール
.SH 書式
.BI "int socketcall(int " call ", unsigned long *" args );
.SH 説明
.BR socketcall ()
はソケット・システムコールのための共通のカーネル・エントリ・
ポイント(kernel entry point)である。
.I call
はどのソケット関数を呼び出すかを指定する。
.I args
は適切なコールに渡すための実際の引き数を含んでいるブロックを指す。
.PP
ユーザー・プログラムは通常の名前を使用して適切な関数を呼び出すべきである。
標準ライブラリの実装者やカーネル・ハッカーのみが
.BR socketcall ()
について知る必要がある。
.SH 準拠
このコールは Linux 特有であり、移植を意図したプログラムで
使用してはいけない。
.SH 注意
ia64 などのいくつかのアーキテクチャでは、システムコール
.BR socketcall ()
が存在しない。実際には、その代わりに
.BR socket (2),
.BR accept (2),
.BR bind (2)
などが独立したシステムコールとして実装されている。
.SH 関連項目
.BR accept (2),
.BR bind (2),
.BR connect (2),
.BR getpeername (2),
.BR getsockname (2),
.BR getsockopt (2),
.BR listen (2),
.BR recv (2),
.BR recvfrom (2),
.BR recvmsg (2),
.BR send (2),
.BR sendmsg (2),
.BR sendto (2),
.BR setsockopt (2),
.BR shutdown (2),
.BR socket (2),
.BR socketpair (2)
