.\" -*- nroff -*-
.\" This man-page is Copyright (C) 1997 John S. Kallal
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and author(s) of this work.
.\"
.\" If the you wish to distribute versions of this work under other
.\" conditions than the above, please contact the author(s) at the following
.\" for permission:
.\"
.\"  John S. Kallal -
.\"	email: <kallal@voicenet.com>
.\"	mail: 518 Kerfoot Farm RD, Wilmington, DE 19803-2444, USA
.\"	phone: (302)654-5478
.\"
.\" $Id: initrd.4,v 1.1.1.1 1999/07/19 01:49:27 cvs Exp $
.\"
.\" Japanese Version Copyright (c) 1997,1998
.\"           ISHIKAWA Mutsumi, all rights reserved.
.\" Translated 1997-12-15, ISHIKAWA Mutsumi <ishikawa@linux.or.jp>
.\" Modified 1998-02-09, ISHIKAWA Mutsumi <ishikawa@linux.or.jp>
.\" Updated & Modified 2005-10-08, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH INITRD 4 2010-09-04 "Linux" "Linux Programmer's Manual"
.SH еђЌе‰Ќ
initrd \- гѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгЃхЂЏ®‚€гЃпЅѓЃхЂ€љ€ќжњџеЊ–гЃ•г‚ЊгЃџ RAM гѓ‡г‚пЅѓ‚йґ»‚Ї
.SH иЌђхЂ’¬®љ
.I /dev/initrd
гЃхЂ•¦ЂЃгѓпјњ‚еђѕѓпЅѓѓдё»•хЂЋ’Џ· 1гЂЃгѓћг‚г‚ѓѓЉгѓдё»•хЂЋ’Џ· 250 гЃЊе‰иљЉ‚Љз¶µ“гЃхЂ€‚‰г‚ЊгЃџ
иЊЇхЂ’ЄЃзІ‹ж­гЃж°ґ°‚з”хЂ‹”ЃхЂ”€ѓ–гѓхЂ’Єѓѓг‚хЂ•¦ѓ‡гѓђг‚г‚ѓ‚йґ»ЃСЃЃ‚г‚‹гЂ‚
ж™хЂ”ЋЂљгЂЃ
.I /dev/initrd
гЃхЂ”‹‰Ђжњ‰иЂ…гЃЇ
.I root.disk
гЃСЃЃ‚г‚ЉгЂЃгѓв‰Єѓи‹Ґѓ‰гЃЇ 400 (root гЃхЂ”€ЃеёҐЃЊиЊЇхЂ’ЄЃж°ґ‡е†ґЃ—ех€•«ѓЅ) гЃСЃЃ‚г‚‹гЂ‚
г‚‚гЃ—гЂЃLinux г‚жїЂ‚йґ»ѓ†гѓ гЃхЂЏЇЅњж€ђзѕќ€гЃ®
.I /dev/initrd
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃЊгЃхЂЋђЃ‹гЃпЅѓЃџе зї«ђ€гЂЃзЇЃгѓ¤ё‹гЃхЂ”€‚жЅџѓћгѓжЅџѓ‰гЃС‚Ѕњж€ђгЃ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹:
.nf
\fB
        mknod \-m 400 /dev/initrd b 1 250
        chown root:disk /dev/initrd
\fP
.fi
.PP
гЃйљњЃџгЂЃ
.I /dev/initrd
г‚’зЇЏзќЎ”хЂ‹”Ѓ™г‚‹гЃџг‚ЃгЃхЂЏ®ЃхЂ•¦ЂЃ
"RAM disk" гЃЁ "Initial RAM disk" гЃхЂ”‰ж¤њж–йґ»ЃхЂ”‹©џиѓзґ”ЃЊ
Linux г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂЏІ›иґ‹пЅҐи…џ„гЃзІ‹ж­гЃйљњ‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„
(з®ґ‹гЃ€гЃйЃ•ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”€‚жЅџѓжЅџѓ‘г‚г‚ѓѓхЂЏ±™‚гЃхЂ”Ќв”ѓзµЋљгЃ§
.B CONFIG_BLK_DEV_RAM=y
гЃ‹гЃ¤
.B CONFIG_BLK_DEV_INITRD=y
гЃхЂ‹”Ѓ™г‚‹)гЂ‚
.I /dev/initrd
г‚’зЇЏзќЎ”хЂ‹”Ѓ™г‚‹е зї«ђ€гЃхЂЏ®ЃхЂ•¦ЂЃRAM гѓ‡г‚пЅѓ‚йґ»‚хЂ•¦ѓ‰гѓхЂЊІ‚г‚ѓѓђг‚’гѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃхЂ‹”Ѓ—гЃ¦
гѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гЃ“гЃхЂ‹”ЃхЂ•¦ЃСЃЃЌгЃхЂЋђЃ„гЂ‚
.\"
.\"
.\"
.SH иЊЇхЂ‘ЏЋ
.I /dev/initrd
г‚йґ»ѓљг‚жїЂѓпЅѓѓхЂЏ®ѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂ•«хЂЌљгЃзІ‹ж­гЃж°ґ°‚з”хЂ‹”ЃхЂ”€ѓ–гѓхЂ’Єѓѓг‚хЂ•¦ѓ‡гѓђг‚г‚ѓ‚йґ»ЃСЃЃ‚г‚‹гЂ‚
гЃ“гЃхЂ”€ѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ•¦‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЊиЋЋжЎЃ‹•гЃ•г‚Њг‚‹е‰ЌгЃхЂЏ®ѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂ (boot loader)
гЃхЂЏ®‚€гЃпЅѓЃхЂ€љ€ќжњџеЊ– (з®ґ‹гЃ€гЃйЃ•ЂЃгѓхЂ’Єѓи‹Ґѓ‰) гЃ•г‚Њг‚‹ RAM гѓ‡г‚пЅѓ‚йґ»‚хЂ•¦ЃСЃЃ‚г‚‹гЂ‚
гЃќгЃхЂ”ЉѕЊгЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЇ
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»‚’зЇ‹ЊзЅ§зґљљЋгЃхЂ”€‚жїЂ‚йґ»ѓ†гѓ иЋЋжЎЃ‹• (two-phase system boot-up)
гЃСѓ€хЂЊ¶”хЂ‹”Ѓ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
.PP
жњЂе€ќгЃхЂ”€ѓ–гѓи‹Ґѓ€г‚в‰Єѓѓгѓ—зЅ§зґљљЋ (first boot-up phase) гЃСЃЃхЂ•¦ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЇ
(з®ґ‹гЃ€гЃйЃ•ЂЃгѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгЃхЂЏ®‚€гЃпЅѓЃхЂ€љ€ќжњџеЊ–гЃ•г‚ЊгЃџ RAM disk гЃСЃЃ‚г‚‹)
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»‚’е€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ  (root file-system) гЃхЂ‹”Ѓ—гЃхЂ€ѓћг‚хЂ€ѓжЅџѓ€
гЃ—гЃхЂ€ќе„Ђе‹•гЃ™г‚‹гЂ‚
и†ѓхЂ‘ЌєЊзЅ§зґљљЋгЃСЃЃхЂ•Ё€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂЏ°ђхЂЏ®Ѓйљњ‚ЊгЃхЂ€Ѓ„г‚‹г‚‚гЃхЂ”€Ѓ‹г‚‰гЂЃиЏґйЃµЉ гЃхЂ”€ѓ‰гѓхЂЊІ‚¤
гѓђг‚„гЃќгЃхЂ”‰»–гЃхЂ”€ѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃЊгѓхЂ’Єѓи‹Ґѓ‰гЃ•г‚Њг‚‹гЂ‚
иЏґйЃµЉ гЃхЂ”€ѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃЊгѓхЂ’Єѓи‹Ґѓ‰гЃ•г‚ЊгЃџз·‡ЊгЂЃж–йЃ•Ѓ—гЃ„гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ 
(гЃ™гЃхЂЋђ‚ЏгЃпјњЂЃйЂљзµЅеѕЎ™‚гЃхЂ”€ѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ )
гЃЊе€гѓЈЃхЂ”€ѓ‡гѓђг‚г‚ѓ‚йґ»Ѓ‹г‚‰гѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚Њг‚‹гЂ‚
.\"
.\"
.\"
.SS гѓ–гѓи‹Ґѓ€г‚в‰Єѓѓгѓ—зЇЏњзЅђ­
.B initrd
г‚’е€хЂЊ¶”хЂ‹”Ѓ—гЃџж™‚гЃхЂ•¦ЂЃг‚жїЂ‚йґ»ѓ†гѓ гЃхЂ•©хЂђЉгЃхЂ”€‚€гЃ†гЃхЂЏ®ѓ–гѓи‹Ґѓ€гЃ™г‚‹:
.IP 1. 3
гѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгЃхЂ•¦‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ѓ—гѓхЂ’Є‚йЃ•ѓхЂЊІѓ гЃЁ
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»‚’гѓпјњѓв‰ЄѓхЂЋђЃхЂЏ®ѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гЂ‚
.IP 2.
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏіе„Ђе‹•ж™‚гЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЇ
.I /dev/initrd
гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ”Љ†…зµЋйґ»‚’зµ®•й–‹ (uncompress) гЃ—гЂЃ
.I /dev/ram0
гЃхЂЏ®‚жЅџѓ”гѓи‹ҐЃ™г‚‹гЂ‚гЃ•г‚‰гЃхЂЏ®ЂЃ
.I /dev/initrd
гЃхЂ”‰ж€ЋгЃпЅѓЃхЂ€Ѓ„гЃџгѓпјњѓв‰ЄѓхЂЋђ‚’иЊ№пЅ†”йљњЃ™г‚‹гЂ‚
.IP 3.
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЇ
.I /dev/ram0
гѓ‡гѓђг‚г‚ѓ‚йґ»‚’е€ќжњџгЃхЂ”€ѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ‹”Ѓ—гЃхЂ€ќхЂЌљгЃз‚Љ›еђѕЃЌех€•«ѓзґ”ЃхЂЋ’е°±з¶ЈЏгЃСЃѓћг‚хЂ€ѓі
гѓ€гЃ™г‚‹гЂ‚
.IP 4.
жЊ‡и…“е†ґЃ•г‚ЊгЃџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃЊе€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ 
(з®ґ‹гЃ€гЃ°
.IR /dev/ram0 )
гЃхЂ‹–ђЊз­ќЂгЃхЂ”Љ зї«ђ€гЃхЂ•¦ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ•©™хЂ”ЋЂљгЃхЂ”€ѓ–гѓи‹Ґѓ€г‚жїЂѓи‹Ґ‚е®ґѓжЅџ‚йґ»ЃхЂ”€Ѓџг‚ЃгЃхЂ”‹њЂз·‡ЊгЃхЂ”€‚йґ»ѓ†гѓѓгѓ—г‚’
зњЃз•гѓЈЃ™г‚‹гЂ‚
.IP 5.
.I /linuxrc
гЃхЂ‹”Ѓ„гЃ†зµЋџиЊµЊех€•«ѓзґ”ЃхЂЋђѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃЊе€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂЏ°­ењхЂ‹”Ѓ™г‚ЊгЃйЃ•ЂЃ
.I /linuxrc
г‚’ UID 0 (гЃ™гЃхЂЋђ‚ЏгЃпјњЂЃroot) гЃхЂ”‹в”¤й™ђгЃСѓ®џиЊµЊгЃ™г‚‹гЂ‚
.RI ( /linuxrc
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂ•Ё®џиЊµЊех€•«ѓзґ”ѓ‘гѓи‹Ґѓџгѓѓг‚жїЂѓСЃѓжЅџЃЊз­ќЋгЃ€г‚‰г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„гЂ‚
.I /linuxrc
гЃхЂ•©хЂ‘Єз¶µ“гЃхЂЋ’®џиЊµЊгѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃСЃЃ‚г‚ЊгЃйЃ•‚€гЃЏгЂЃг‚жїЂ‚СЃѓхЂЏ®‚йґ»‚хЂ•¦ѓхЂЋђѓ—гѓ€гЃСЃ‚‚зЅ•‹г‚ЏгЃхЂЋђЃ„гЂ‚)
.IP 6.
.I /linuxrc
гЃЊзµЋџиЊµЊгЃ•г‚ЊгЃхЂЋђЃ„гЂЃгЃйљњЃџгЃхЂ•¦ЂЃ
.I /linuxrc
гЃхЂ”Љ®џиЊµЊгЃЊи…џ‚зЇ‹†гЃ—гЃџж™‚гЃхЂ•¦ЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃЊгѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚Њг‚‹гЂ‚
.RI ( /linuxrc
г‚’и…џ‚зЇ‹†гЃ—гЃџж™‚гЂЃзЇЏ•г‚‰гЃ‹гЃхЂ”€ѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃЊе€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ з­ќЉгЃ«
гѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃхЂ€Ѓ„г‚‹е зї«ђ€гЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”Љ‹•зЇЏњгЃЇ
\fBзѕ†е†ґ‚Ѓг‚‰г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ„ (з­ќЌзµЋљгЃСЃЃ‚г‚‹)\fRгЂ‚
зж†њњхЂ‹”ЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЊгЃхЂЊІЃхЂ”€‚€гЃ†гЃхЂЏ°‹•зЇЏњгЃ™г‚‹гЃ‹гЃхЂ•¦ЂЃ
гЂЊзѕ€хЂ‹—„ЏгЂЌгЃхЂ”€‚зҐ‰‚хЂ•¦‚жїЂѓСЃѓжЅџ‚’еЏ‚з…СЃЃхЂ”€Ѓ“гЃхЂ‹”Ђ‚)
.IP 7.
йЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃ«
гѓ‡г‚пЅѓѓхЂ‘Њ‚хЂ•¦ѓ€гѓЄ
.I /initrd
гЃЊгЃ‚г‚ЊгЃйЃ•ЂЃ
.I /dev/ram0
гѓ‡гѓђг‚г‚ѓ‚йґ»ЃЇ
.I /
гЃ‹г‚‰
.I /initrd
гЃхЂЏІР©е‹•гЃ•г‚Њг‚‹гЂ‚
.I /initrd
гѓ‡г‚пЅѓѓхЂ‘Њ‚хЂ•¦ѓ€гѓхЂЋђЃЊзµ–ењхЂ‹”Ѓ—гЃхЂЋђЃ„е зї«ђ€гЃхЂ•¦ЂЃ
.I /dev/ram0
гЃхЂ•¦‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚Њг‚‹гЂ‚
.RI ( /
гЃЊ
.I /initrd
гЃхЂЏІР©е‹•гЃ•г‚ЊгЃџе зї«ђ€гЃхЂЏ®ЃхЂ•¦ЂЃ
.I /dev/ram0
гЃхЂ•¦‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃљгЂЃгЃќгЃхЂ”ЊµђжћњгЂЃ
.I /dev/ram0
гЃС†и»Њг‚Љзґ®‹г‚ЃгЃџгѓ—гѓхЂ’Є‚зҐ‰‚йґ»ЃхЂ•¦ЃќгЃхЂ”€ЃйљњЃдё€®‹г‚‹зЇ‹‹гЃЊгЃСЃЃЌг‚‹гЂ‚
г‚‚гЃ—гЂЃ
.I /initrd
гѓ‡г‚пЅѓѓхЂ‘Њ‚хЂ•¦ѓ€гѓхЂЋђЃЊйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂЏ°­ењхЂ‹”Ѓ›гЃљгЂЃ
.I /linuxrc
гЃЊи…џ‚зЇ‹†гЃ—гЃџж™‚гЃ«
.I /dev/ram0
з­ќЉгЃСѓ®џиЊµЊгЃ•г‚ЊгЃџгЂЃгЃхЂЋђ‚“г‚‰гЃ‹гЃхЂ”€ѓ—гѓхЂ’Є‚зҐ‰‚йґ»ЃЊиЋЋйЃ•‚Љи†“љгЃ‘гЃхЂ€Ѓ„гЃџе зї«ђ€гЃ®
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”Љ‹•зЇЏњгЃЇ
.BR "зѕ†е†ґ‚Ѓг‚‰г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ„ (з­ќЌзµЋљгЃСЃЃ‚г‚‹)" гЂ‚
зж†њњхЂ‹”ЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЊгЂЃгЃ“гЃхЂ”‹™‚гЃхЂЊІЃхЂ”€‚€гЃ†гЃхЂЋ’‹•зЇЏњг‚’гЃ™г‚‹гЃ‹гЃхЂЏ®Ѓг‚ѓЃ„гЃхЂ€ЃхЂ•¦ЂЃ
гЂЊзѕ€хЂ‹—„ЏгЂЌг‚’еЏ‚з…СЃЃхЂ”€Ѓ“гЃхЂ‹”Ђ‚)
.IP 8.
ж™хЂ”ЋЂљгЃхЂ”€ѓ–гѓи‹Ґѓ€г‚жїЂѓи‹Ґ‚е®ґѓжЅџ‚№ (з®ґ‹гЃ€гЃйЃ•ЂЃ
.I /sbin/init
гЃхЂ”Ќе„Ђе‹•) гЃЊйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ з­ќЉгЃС†ЎЊг‚Џг‚Њг‚‹гЂ‚
.\"
.\"
.\"
.SS г‚хЂЋђѓ—г‚жїЂѓСЃѓі
.B initrd
г‚’з”хЂ‹”Ѓ„г‚‹е зї«ђ€гЃхЂЏ®ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”€ѓ–гѓи‹Ґѓ€г‚в‰Єѓѓгѓ—ж“ЌзЇЏњгЃхЂЏ°иҐІйџеёҐ‚’з­ќЋгЃ€г‚‹
гѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгѓзҐ‰‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃхЂ•©хЂђЉгЃхЂ”€‚€гЃ†гЃхЂЋђ‚‚гЃхЂ”€ЃЊгЃ‚г‚‹гЂЃ
.TP
.BI initrd= "filename"
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»ЃхЂ‹”Ѓ—гЃхЂ€ѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚’жЊ‡зµЋљгЃ™г‚‹гЂ‚
.B LOADLIN
гЃСЃЃхЂ•¦ЂЃгЃ“г‚ЊгЃхЂ•¦‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџ‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃСЃЃ‚г‚‹гЂ‚
.B LILO
гЃСЃЃхЂ•¦ЂЃ
.B LILO
гЃхЂ”Ќв”ѓзµЋљгѓ•г‚пјњ‚г‚ѓѓ«
.I /etc/lilo.config
е†…гЃСЃ‚жЅџѓћгѓжЅџѓ‰гЃхЂ‹”Ѓ—гЃхЂ€™ж€Ћз”хЂ‹”Ѓ—гЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„гЂ‚
гЃ“гЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃС„Њ‡зµЋљгЃ•г‚Њг‚‹гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂ•¦ЂЃзґЉљгЃЏгЃхЂ”Љ зї«ђ€ gzip ењС…и»’гЃ•г‚ЊгЃџ
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚г‚ѓѓпјњѓи‹Ґ‚еђѕЃСЃЃ‚г‚‹гЂ‚
.TP
.B noinitrd
гЃ“гЃхЂ”Ќе„Ђе‹•г‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃхЂ•§єЊзЅ§зґљљЋгЃхЂ”Ќе„Ђе‹•ж“ЌзЇЏњг‚’з„в‰¦Љйґ»ЃхЂЏ®Ѓ™г‚‹гЂ‚
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃЇ
.I /dev/initrd
гЃЊе€ќжњџеЊ–гЃ•г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ„е зї«ђ€гЃхЂ‹–ђЊзЅ•гЃхЂ”€ЂЃйЂљзµЅеђѕЃхЂ”€ѓ–гѓи‹Ґѓ€г‚в‰Єѓѓгѓ—е‹•зЇЏњг‚’иЊµЊгЃ†гЂ‚
гЃ“гЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџ‚’з”хЂ‹”Ѓ„г‚‹гЃхЂ‹”ЂЃгѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгЃхЂЏ®‚€гЃпЅѓЃхЂ€ѓпјњѓв‰ЄѓхЂЋ‘ёЉгЃхЂЏ®ѓхЂ’Єѓи‹Ґѓ‰гЃ•г‚ЊгЃџ
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»ЃхЂ•¦ЃќгЃхЂ”€ЃйљњЃйћїќзµ–гЃ•г‚Њг‚‹гЂ‚
гЃг‚ѓЃйљњ‚ЉгЂЃгЃ“гЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџ‚’з”хЂ‹”Ѓ„г‚‹гЃ“гЃхЂ‹”ЃхЂЏ®‚€гЃпЅѓЃхЂ€ЂЃ
.I /dev/initrd
гЃхЂ”Љ†…зµЋйґ»‚’ (гѓ–гѓи‹Ґѓ€зЇЃгѓҐ¤–гЃхЂ”Њ›хЂ”Њљ„гЃ«) е€хЂЊ¶”хЂ‹”Ѓ™г‚‹гЃ“гЃхЂ‹”ЃЊех€•«ѓзґ”ЃхЂЏ®ЃхЂЋђ‚‹гЂ‚гЃйљњЃџгЂЃгЃќгЃхЂ”Љ†…зµЋйґ»ЃЇ
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚г‚ѓѓпјњѓи‹Ґ‚еђѕЃхЂЏґ™ђзµЋљгЃ•г‚ЊгЃхЂЋђЃ„гЂ‚
гЃ—гЃ‹гЃ—гЂЃ
.I /dev/initrd
гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ•«хЂЌљгЃеёҐЃ гЃ—гЃхЂ”€Ѓж°ґх€•«ѓзґ”ЃСЃЃ‚г‚ЉгЂЃг‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”Ќе„Ђе‹•з·‡Њ 1 з¶єхЂ€Ѓ—гЃ‹иЊЇхЂ’ЄЃж°ґ‡е†ґЃ™зЇ‹‹
гЃЊгЃСЃЃЌгЃхЂЋђЃ„гЂ‚
.TP
.BI root= "device-name"
йЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ‹”Ѓ—гЃхЂ€™ж€Ћг‚Џг‚Њг‚‹гѓ‡гѓђг‚г‚ѓ‚йґ»‚’жЊ‡зµЋљгЃ™г‚‹гЂ‚
.B LOADLIN
гЃСЃЃхЂ•¦ЂЃгЃ“г‚ЊгЃхЂ•¦‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџ‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃСЃЃ‚г‚‹гЂ‚
.B LILO
гЃСЃЃхЂ•¦‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџ‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЂЃгЃйљњЃџгЃхЂ•¦ЂЃ
.B LILO
гЃхЂ”Ќв”ѓзµЋљгѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃСЃЃ‚г‚‹
.I /etc/lilo.config
гЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџѓхЂЊІ‚г‚ѓѓжЅџЃхЂ‹”Ѓ—гЃхЂ€™ж€Ћз”хЂ‹”Ѓ™г‚‹гЂ‚
гЃ“гЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџЃС„Њ‡зµЋљгЃ•г‚Њг‚‹гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ•¦ЂЃйЃхЂЊґ€‡гЃхЂЋђѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ‹”Ѓ—
гЃхЂ€ѓћг‚хЂ€ѓжЅџѓ€ех€•«ѓзґ”ЃхЂЋђѓ‡гѓђг‚г‚ѓ‚йґ»ЃСЃЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„гЂ‚
.\"
.\"
.\"
.SS йЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”Љ¤‰ж›ґ
гѓ‡гѓ•г‚хЂЊІѓхЂЏ®ѓ€гЃСЃЃхЂ•¦ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”Ќв”ѓзµЋљ
(з®ґ‹гЃ€гЃйЃ•ЂЃ
.BR rdev (8)
г‚’з”хЂ‹”Ѓ„гЃхЂ€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ѓ•г‚пјњ‚г‚ѓѓхЂЏ°†…гЃхЂЏ®‚зҐ‰ѓѓгѓ€гЃ•г‚ЊгЃџг‚‚гЃхЂ”€ЂЃгЃйљњЃџгЃхЂ•¦ЂЃг‚жЅџѓжЅџѓ‘г‚г‚ѓѓхЂЏ±™‚гЃхЂЏ®‚хЂЏ®ѓј
гѓЌгѓхЂЏ®ѓ•г‚пјњ‚г‚ѓѓхЂЏ°†…гЃхЂЏ°џ‹г‚ЃиЋЁи‹ҐЃйљњ‚ЊгЃџг‚‚гЃ®)гЂЃ
гЃйљњЃџгЃхЂ•¦ЂЃгѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂгЃхЂ”€‚хЂЋђѓ—г‚жїЂѓСЃѓжґ»в”ѓзµЋљгЃхЂЏ®‚€гЃпЅѓЃхЂ€›Њ‡зµЋљгЃ•г‚ЊгЃџг‚‚гЃхЂ”€ЃЊйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓј
гѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ‹”Ѓ—гЃхЂ€™ж€Ћг‚Џг‚Њг‚‹гЂ‚
NFS гѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃџйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’е€хЂЊ¶”хЂ‹”Ѓ™г‚‹е зї«ђ€гЂЃ
.B nfs_root_name
гЃЁ
.B nfs_root_addrs
гѓ–гѓи‹Ґѓ€г‚хЂЋђѓ—г‚жїЂѓСЃѓжЅџ‚’зЇЏеёҐЃпЅѓЃ¦ NFS гЃхЂ”Ќв”ѓзµЋљг‚’з­ќЋгЃ€гЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„гЂ‚
NFS гѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃџгѓхЂЏ®ѓи‹Ґѓ€ (гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ ) гЃхЂЏ®Ѓг‚ѓЃ„гЃхЂ€Ѓ®
г‚€г‚ЉиЌ…жЅџЃ—гЃ„жѓ…е е®ґЃхЂ•¦ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”€ѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€гѓ•г‚пјњ‚г‚ѓѓ«
.B Documentation/filesystems/nfsroot.txt
г‚’еЏ‚з…СЃЃхЂ”€Ѓ“гЃхЂ‹”Ђ‚
гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”Ќв”ѓзµЋљгЃхЂЏ®Ѓг‚ѓЃ„гЃхЂ€ЃхЂ”€‚€г‚ЉиЌ…жЅџЃ—гЃ„жѓ…е е®ґЃхЂ•¦ЂЃ
.B LILO
гЃЁ
.B LOADLIN
гЃхЂ”€ѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€г‚‚еЏ‚з…СЃЃхЂ”€Ѓ“гЃхЂ‹”Ђ‚
.PP
гЃйљњЃџгЂЃ
.I /linuxrc
г‚’з”хЂ‹”Ѓ„г‚‹зЇ‹‹гЃхЂЏ®‚€гЃпЅѓЃхЂ€‚‚йЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гѓ‡гѓђг‚г‚ѓ‚йґ»‚’зґЉ‰ж›зњјЃ™г‚‹гЃ“гЃЁ
гЃЊгЃСЃЃЌг‚‹гЂ‚
.I /linuxrc
г‚’з”хЂ‹”Ѓ„гЃхЂ€ЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»‚’зґЉ‰ж›зњјЃ™г‚‹гЃџг‚ЃгЃхЂЏ®ЃхЂ•¦ЂЃ
.I /proc
гЃЊгѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ‘г‚ЊгЃйЃ•ЃхЂЋђ‚‰гЃхЂЋђЃ„гЂ‚
.I /proc
г‚’гѓћг‚хЂ€ѓжЅџѓ€гЃ—гЃџз·‡ЊгЃСЃЂЃ
.I /linuxrc
гЃЇ proc гѓ•г‚пјњ‚г‚ѓѓ«
.IR /proc/sys/kernel/real-root-dev ,
.IR /proc/sys/kernel/nfs-root-name ,
.I /proc/sys/kernel/nfs-root-addrs
гЃхЂЏ±›еђѕЃЌиЋЁи‹ҐЃеёҐ‚’иЊµЊгЃ„гЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»‚’зґЉ‰ж›зњјЃ™г‚‹гЂ‚
(NFS гЃСЃЃхЂ•¦ЃхЂЋђЃ„) з‰хЂЊ¶ђ†зљ„гЃхЂЋђѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ”Љ зї«ђ€гЂЃ
.I /linuxrc
гЃЊж–йЃ•Ѓ—гЃ„гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”€ѓ‡гѓђг‚г‚ѓ‚еђ€•хЂЋ’ећ©‚’
.I /proc/sys/kernel/real-root-dev
гЃхЂЏ±›еђѕЃЌиЋЁи‹Ґ‚ЂгЃ“гЃхЂ‹”ЃСЃЂЃгѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»ЃЊзґЉ‰ж›зњјЃ•г‚Њг‚‹гЂ‚
NFS гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”Љ зї«ђ€гЂЃ
.I /linuxrc
гЃЊ NFS гЃхЂ”Ќв”ѓзµЋљг‚’
.I /proc/sys/kernel/nfs-root-name
гЃЁ
.I /proc/sys/kernel/nfs-root-addrs
гЃхЂЏ±›еђѕЃЌиЋЁи‹ҐЃеёҐЂЃгЃќг‚ЊгЃ‹г‚‰
.I /proc/sys/kernel/real-root-dev
гЃ« (з–‘зЇЊј NFS гѓ‡гѓђг‚г‚ѓ‚йґ»ѓЉгѓжЅџѓђгѓи‹ҐЃСЃЃ‚г‚‹) 0xff г‚’ж›еђѕЃЌиЋЁи‹Ґ‚ЂгЃ“гЃхЂ‹”ЃСЃЂЃ
гѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»ЃЊзґЉ‰ж›зњјЃ•г‚Њг‚‹гЂ‚
з®ґ‹гЃ€гЃйЃ•ЂЃзЅЁпјњЃхЂ”€‚жїЂ‚СЃѓхЂЏ®‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџЃхЂЏ®‚€г‚ЉгЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»‚’
.I /dev/hdb1
гЃхЂЏ°¤‰ж›зњјЃСЃЃЌг‚‹гЃ г‚ЌгЃ†:
.nf

    echo 0x365 >/proc/sys/kernel/real-root-dev

.fi
гЃйљњЃџгЂЃNFS гЃхЂ”Љ зї«ђ€гЂЃзЅЁпјњЃхЂ”€‚€гЃ†гЃхЂЋђ‚жїЂ‚СЃѓхЂЏ®‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџЃхЂЏ®‚€г‚ЉгЂЃ
193.8.232.2 гЃхЂ‹”Ѓ„гЃ† IP г‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»‚’жЊЃгЃ¤ "idefix" гЃхЂ‹”Ѓ„гЃ†еђЌе‰ЌгЃ®
г‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”€ЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ‹”Ѓ—гЃхЂ€ЂЃ
гѓхЂ’Єѓи‹Ґ‚хЂЏ®ѓхЂЏ®ѓЌгѓѓгѓ€гѓхЂ•¦ѓи‹Ґ‚хЂ•¦Ѓ® 193.8.232.2 гЃхЂ‹”Ѓ„гЃ† IP г‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»‚’жЊЃгЃ¤ NFS г‚жіЈѓи‹ҐѓђгЃ®
NFS гѓ‡г‚пЅѓѓхЂ‘Њ‚хЂ•¦ѓ€гѓЄ
.I /var/nfsroot
г‚’гѓћг‚хЂ€ѓжЅџѓ€гЃ™г‚‹г‚€гЃ†гЃхЂЏ°¤‰ж›зњјЃСЃЃЌг‚‹:
.nf

    echo /var/nfsroot >/proc/sys/kernel/nfs-root-name
    echo 193.8.232.2:193.8.232.7::255.255.255.0:idefix \\
        >/proc/sys/kernel/nfs-root-addrs
    echo 255 >/proc/sys/kernel/real-root-dev
.fi

.BR зѕ€хЂ‹—„Џ :
гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’зґЉ‰ж›зњјЃ™г‚‹гЃџг‚ЃгЃ«
.I /proc/sys/kernel/real-root-dev
г‚’зЇЏеёҐЃ†гЃхЂ”€ЃхЂ•§жњ­е‰ЌгЃхЂ”‹–еЏ·і•гЃСЃЃ‚г‚‹гЂ‚
гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’зґЉ‰ж›зњјЃ™г‚‹ж–йЃ•Ѓ—гЃ„ж–еЏ·і•гЃхЂЏ®Ѓг‚ѓЃ„гЃхЂ€ЃхЂ”‹ѓ…е е®ґЃхЂ•¦ЂЃ
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®‚зґ”ѓи‹Ґ‚йґ»ЃхЂЏ°ђхЂЏ®Ѓйљњ‚Њг‚‹
.I Documentation/initrd.txt
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚„гЂЃ
.BR pivot_root (2)
г‚„
.BR pivot_root (8)
г‚’еЏ‚з…СЃЃ—гЃхЂ€ЃзҐ‰Ѓ—гЃ„гЂ‚
.\" FIXME гѓћгѓ‹гѓгѓЈ‚в‰ЄѓхЂЏ®ѓљгѓи‹Ґ‚еђѕЃ§ pivot_root гЃхЂ”‰»•и…џ„гЃеёҐ‚’иЊЇхЂ‘ЏЋгЃ™г‚‹з¶Ѕ…иЌЂЃгЃЊгЃ‚г‚‹гЂ‚
.\"
.\"
.\"
.SS зЇЏеёҐЃ„ж–№
.B initrd
гЃЊзµЋџиЊ–…гЃ•г‚ЊгЃџз­ќзҐ‰ЃхЂЋ”›хЂ”Њљ„гЃхЂ•¦ЂЃг‚жїЂ‚йґ»ѓ†гѓ г‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹ҐѓхЂЏ±™‚гЃхЂЏ®ЂЃгѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ°Њ–гЃ•г‚ЊгЃџг‚хЂЏ®ѓј
гѓЌгѓхЂЏ®ЃхЂ”Ќв”ѓзµЋљг‚’ех€•«ѓзґ”ЃхЂЏ®Ѓ™г‚‹гЃ“гЃхЂ‹”ЃСЃЃ‚гЃпЅѓЃџгЂ‚
.PP
зЅЁпјњЃхЂ”€‚€гЃ†гЃхЂЋ“µЃг‚ЊгЃхЂ”€‚жїЂ‚йґ»ѓ†гѓ г‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹ҐѓхЂЏ®ЃЊех€•«ѓзґ”ЃхЂЏ®ЃхЂЋђ‚‹:
.IP 1. 3
гѓхЂ’Єѓи‹ҐѓЂгѓ—гѓхЂ’Є‚йЃ•ѓхЂЊІѓ гЃхЂ•¦ЂЃгѓ•гѓхЂ’Єѓѓгѓ”гѓи‹Ґ‚„гЃќгЃхЂ”‰»–гЃхЂ”€ѓпјњѓ‡г‚пЅѓ‚в‰ЄЃ‹г‚‰гЂЃ
жњЂзµЁЏй™ђгЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓ« (з®ґ‹гЃ€гЃйЃ•ЂЃ
.IR /dev/ram ,
.IR /dev/initrd ,
ext2 гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”€ЃеёҐЃхЂ”€‚жіЈѓќгѓи‹Ґѓ€гЃ—гЃџг‚хЂЏ®ѓи‹ҐѓЌгѓ«) г‚’гѓ–гѓи‹Ґѓ€гЃ—гЂЃ
gzip ењС…и»’гЃ•г‚ЊгЃџе€ќжњџгѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚г‚ѓѓпјњѓи‹Ґ‚еђѕ‚’
.I /dev/initrd
гЃхЂЏ®ѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гЂ‚
.IP 2.
зµЋџиЊµЊгѓ•г‚пјњ‚г‚ѓѓ«
.I /linuxrc
гЃхЂ•¦ЂЃ(1) йЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”€ѓћг‚хЂ€ѓжЅџѓ€гЃхЂЏЇЅ•гЃЊз¶Ѕ…иЌЂЃгЃ‹
(гЃ™гЃхЂЋђ‚ЏгЃпјњЂЃгѓ‡гѓђг‚г‚ѓ‚йґ»‚еёҐ‚г‚ѓѓ—гЂЃгѓ‡гѓђг‚г‚ѓ‚йґ»ѓ‰гѓхЂЊІ‚г‚ѓѓђгЂЃгѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ )гЂЃ
(2) й…ЌзµЅѓгѓпјњѓ‡г‚пЅѓ‚в‰ЄЃхЂЏЇЅ•гЃЊз¶Ѕ…иЌЂЃгЃ‹ (з®ґ‹гЃ€гЃйЃ•ЂЃCD-ROM, гѓЌгѓѓгѓ€гѓхЂ•¦ѓи‹Ґ‚хЂ•¦ЂЃгѓ†гѓи‹Ґѓ—гЃхЂЋђЃ©)
г‚’зѕ†йЄ®љгЃ™г‚‹гЂ‚зѕ†йЄ®љгЃхЂ•¦ЂЃгѓхЂ€ѓи‹Ґ‚еђџЃеђѕЃхЂ”Љ•ЏгЃ„еђ€г‚ЏгЃ›гЂЃи‡хЂЋ’‹•зЅЋње‡е†ґЂЃгЃ‚г‚‹гЃ„гЃхЂ•¦ЃќгЃхЂ”‰ж¤њиЂ…гЃ®
ж–еЏ·і•г‚’и…џ„гЃж°ґђ€г‚ЏгЃ›гЃхЂ€ќЎЊг‚Џг‚Њг‚‹гЂ‚
.IP 3.
зµЋџиЊµЊгѓ•г‚пјњ‚г‚ѓѓ«
.I /linuxrc
гЃхЂ•¦ЂЃе€ќжњџгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃ‹г‚‰з¶Ѕ…иЌЂЃгЃхЂЋђѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®‚’гѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гЂ‚
.IP 4.
зµЋџиЊµЊгѓ•г‚пјњ‚г‚ѓѓ«
.I /linuxrc
гЃхЂ•¦ЂЃгѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’зЇЏњж€ђгЃ—гЂЃй…Ќи‡ЂхЂ”€Ѓ™г‚‹ (гЃ“гЃхЂ”‹хЂ“љйљЋгЃСЃЃхЂ•¦ЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓј
гѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ•Ё®Ње…хЂ‹”ЃхЂЋђ‚жїЂ‚йґ»ѓ†гѓ гЃСЃЃ‚г‚‹з¶Ѕ…иЌЂЃгЃхЂ•¦ЃхЂЋђЃ„)гЂ‚
.IP 5.
зµЋџиЊµЊгѓ•г‚пјњ‚г‚ѓѓ«
.I /linuxrc
гЃхЂ•¦ЂЃ
.I /proc/sys/kernel/real-root-dev
г‚’иЌђхЂ’¬®љгЃ—гЂЃ
.IR /proc "гЂЃ"
гѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃхЂ€Ѓ„г‚‹йЂљзµЅеѕЎ™‚гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ еЏЉгЃжЅџЃќгЃхЂ”‰»–гЃхЂ”€ѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ 
г‚’г‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЃ—гЂЃ
зµЋџиЊµЊг‚’и…џ‚зЇ‹†гЃ™г‚‹гЂ‚
.IP 6.
зЅЁпјњЃхЂЏ®ЂЃг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ•¦ЂЃйЂљзµЅеѕЎ™‚гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’гѓћг‚хЂ€ѓжЅџѓ€гЃ™г‚‹гЂ‚
.IP 7.
гЃ“гЃхЂ”‹хЂ“љйљЋгЃСЃЂЃгѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ•Ё…хЂ‹”ЃйЋЂ‰ж›зњјЃЊиЊµЊг‚Џг‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ„зЉеЂ¶…‹гЃСЃЂЃ
г‚в‰Є‚хЂ•¦‚зҐ‰‚йґ»ЃСЃЃЌг‚‹зЉеЂ¶…‹гЃхЂЏ®ЃхЂЋђ‚‹гЂ‚
гЃйљњЃџгЂЃгѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂг‚’г‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹ҐѓхЂЏ®Ѓ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
.IP 8.
гѓ–гѓи‹Ґѓ€гѓхЂ’Єѓи‹ҐѓЂг‚’иЌђхЂ’¬®љгЃ—гЂЃг‚жїЂ‚йґ»ѓ†гѓ иЋЋжЎЃ‹•ж™‚гЃхЂЏЇж€Ћз”хЂ‹”Ѓ•г‚Њг‚‹г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃхЂ”€‚зҐ‰ѓѓ
гѓ€г‚’еђхЂЏ®‚“гЃ гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ г‚’
.I /dev/initrd
гЃхЂЏ®ѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹ (з®ґ‹гЃ€гЃйЃ•ЂЃ
.I /dev/ram0
гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ”Љ†…зµЋйґ»‚’зЇ†хЂ”‹хЂ‘ЄгЃ—гЂЃг‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЃ™г‚‹гЂ‚жњЂз·‡ЊгЃхЂЏ®ЂЃ
.I /dev/ram0
гЃхЂ”€‚г‚ѓѓпјњѓи‹Ґ‚еђѕ‚’гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂЏ±›еђѕЃЌе‡е†ґЃ™)гЂ‚
.IP 9.
гЃ“г‚ЊгЃСЃЂЃг‚жїЂ‚йґ»ѓ†гѓ гЃЊгѓ–гѓи‹Ґѓ€ех€•«ѓзґ”ЃхЂЏ®ЃхЂЋђ‚‹гЂ‚гЃ“гЃхЂ”ЉѕЊгЂЃгЃ•г‚‰гЃхЂЏ®ЃќгЃхЂ”‰»–гЃхЂ”€‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹Ґѓ«
гЃхЂ”‰ЅњзЅђхЂ’Є‚’зµЋџиЊµЊгЃСЃЃЌг‚‹гЂ‚
.PP
з­ќЉиЌђгЃхЂ”Љ‹•зЇЏњгЃСЃЃ®
.I /dev/initrd
гЃхЂ”Љй†ње‰иљЉЃхЂ”€‚хЂ’Єѓи‹Ґѓќг‚г‚ѓѓжЅџѓ€гЃхЂ•¦ЂЃе€ќжњџг‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”ЋЃеѕЎЉћг‚„зґЉСЃЃЌгЃхЂЋђ‚еђѕ‚СЃѓЌгѓхЂЋђѓѓг‚хЂ•¦‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЂЃ
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”Љ†ЌзЅ•‹и†Ђ‰гЃхЂЋђЃ—гЃхЂЏ®ЂЃйЂљзµЅеђѕЃхЂ”€‚жїЂ‚йґ»ѓ†гѓ ж“ЌзЇЏњгЃСѓ†Ќе€хЂЊ¶”хЂ‹–х€•«ѓзґ”ЃхЂЋ•в”ѓзµЋљгѓ‡гѓи‹Ґ‚еёҐ‚’е€©
з”хЂ‹”Ѓ™г‚‹гЃ“гЃхЂ‹”ЃхЂЏ®Ѓ‚г‚‹гЂ‚
.PP
2 з•хЂЋ”›хЂ”€ЃхЂ”€‚е®ґѓи‹Ґ‚йґ»ЃхЂ•¦ЂЃз­ќЂгЃг‚ѓЃхЂ”ЊхЂ“†зђ†з­ќЉгЃхЂ”€ѓЌгѓѓгѓ€гѓхЂ•¦ѓи‹Ґ‚хЂ•¦ЃхЂЏ®ЃЉгЃ„гЃхЂ€ЂЃз•йЃ•ЃхЂЋђ‚‹иЌђхЂ’¬®љгЃхЂ”€ѓЏгѓј
гѓ‰г‚хЂ€‚СЃ‚в‰ЄЃхЂ”€‚жїЂ‚йґ»ѓ†гѓ з­ќЉгЃ§ Linux г‚’е‹•зЇЏњгЃ•гЃ›г‚‹гЃџг‚ЃгЃхЂ”€‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹ҐѓхЂЏ®‚’иЊµЊгЃ†е зї«ђ€
гЃСЃЃ‚г‚‹гЂ‚
гЃ“гЃхЂ”€‚€гЃ†гЃхЂЋђ‚е®ґѓи‹Ґ‚йґ»ЃхЂ”Љ зї«ђ€гЂЃгЃ”гЃйЋћЏж•йЃ•ЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”€‚зҐ‰ѓѓгѓ€ (зђ†жѓж‹¬љ„гЃхЂЏ®ЃхЂ•¦ЃџгЃпЅѓЃџз­ќЂ
гЃг‚ѓЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓ«) гЃхЂ”€ЃеёҐ‚’е€хЂЊ¶”хЂ‹”Ѓ—гЂЃг‚жїЂ‚йґ»ѓ†гѓ е›е єњ‰гЃхЂ”Ќв”ѓзµЋљжѓ…е е®ґЃхЂ•Ёх€•«ѓзґ”ЃхЂЋ–™ђг‚ЉзµЁЏгЃ•гЃЏгЃ™
г‚‹гЃ“гЃхЂ‹”ЃЊжњ›гЃйљњЃ—гЃ„гЃСЃЃ‚г‚ЌгЃ†гЂ‚
гЃ“гЃхЂ”Љ зї«ђ€гЂЃе…хЂ‹”ЃхЂ€ЃхЂ”Љї…иЌЂЃгЃхЂЋђѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃЊе…гѓЈЃпЅѓЃџе…жј”Ђљгѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚’зЇЏњж€ђгЃ™г‚‹гЂ‚
гЃќгЃ—гЃхЂ€ЂЃ
.I /linuxrc
гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЂЃгЃйљњЃџгЃхЂ•¦ЂЃ
.I /linuxrc
гЃ‹г‚‰зµЋџиЊµЊгЃ•г‚Њг‚‹гѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂ”€ЃеёҐ‚’з•йЃ•ЃхЂЋђЃпЅѓЃџг‚‚гЃхЂ”€ЃхЂЏ®Ѓ—гЃхЂ€ЃЉгЃЏгЂ‚
.PP
3 з•хЂЋ”›хЂ”€ЃхЂ”€‚е®ґѓи‹Ґ‚йґ»ЃхЂ•¦ЂЃг‚€г‚Љз®ґж°ґ€хЂЊІЃхЂЋ’еҐЁж—С…”хЂ‹”ѓ‡г‚пЅѓ‚йґ»‚хЂ•¦‚’зЇЏњг‚‹е зї«ђ€гЃСЃЃ‚г‚‹гЂ‚
гѓхЂЏ®ѓи‹Ґѓ€гѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ”€ѓ‘гѓи‹Ґѓ†г‚пЅѓ‚жїЂѓСЃѓжЅџЃхЂ”‰ЅЌи‡ЂхЂ”€ЃхЂ‹”Ѓ„гЃпЅѓЃџжѓ…е е®ґЃЇ
гѓ–гѓи‹Ґѓ€ж™‚гЃхЂЏ°ї…иЌЂЃгЃхЂЋђЃ„гЃџг‚ЃгЂЃ
.I /dev/initrd
гЃ‹г‚‰гѓхЂ’Єѓи‹Ґѓ‰гЃ•г‚ЊгЃџг‚жїЂ‚йґ»ѓ†гѓ гЃхЂ•¦ЂЃ
з¶Ѕ…иЌЂЃгЃхЂЋ“хЂ‘ЄзµЅеѕЎЂСЃѓЃг‚СЃѓѓг‚хЂ•¦‚’иЊµЊгЃпЅѓЃџз·‡ЊгЃСЃЂЃгѓхЂ€ѓи‹Ґ‚еђџЃеђѕЃхЂ”Љ•ЏгЃ„еђ€г‚ЏгЃ›г‚„и‡хЂЋ’‹•зЅЋње‡є
(г‚‚гЃ—гЃЏгЃхЂ•¦ЃќгЃхЂ”‰ж¤њж–№) г‚’иЊµЊгЃ†гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹г‚€гЃ†гЃхЂЏ®ЃхЂЋђ‚‹гЂ‚
.PP
(зЇЃ–гЃхЂЏ®‚‚гЃџгЃЏгЃ•г‚“з®ґ‹гЃЊгЃ‚г‚‹гЃ г‚ЌгЃ†гЃЊ) жњЂз·‡ЊгЃхЂ”‰ѕ‹гЃхЂ‹”Ѓ—гЃхЂ€ЃхЂ•¦ЂЃ
.B initrd
г‚’е€хЂЊ¶”хЂ‹”Ѓ™г‚‹гЃхЂ‹”ЂЃCD-ROM з­ќЉгЃ® Linux гѓ‡г‚пЅѓ‚йґ»ѓ€гѓхЂЋђѓ“гѓгѓЈѓи‹Ґ‚жїЂѓСЃѓжЅџ‚’
г‚€г‚Љи†‚в‰¦ЌгЃ« CD-ROM гЃ‹г‚‰г‚г‚ѓѓжЅџ‚йґ»ѓ€гѓи‹ҐѓхЂЏ®Ѓ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЃ г‚ЌгЃ†гЂ‚
гѓ‡г‚пЅѓ‚йґ»ѓ€гѓхЂЋђѓ“гѓгѓЈѓи‹Ґ‚жїЂѓСЃѓжЅџЃхЂ•¦ЂЃ
.B LOADLIN
г‚’зЇЏеёҐЃпЅѓЃхЂ€ЂЃгѓ•гѓхЂ’Єѓѓгѓ”гѓи‹Ґ‚’е…хЂ‹”ЃЏе€хЂЊ¶”хЂ‹”Ѓ›гЃљгЃ« CD-ROM гЃ‹г‚‰
.I /dev/initrd
г‚’з›иґ‹пЅҐгѓхЂ’Єѓи‹Ґѓ‰гЃ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
гЃйљњЃџгЂЃ
.B LILO
гѓ–гѓи‹Ґѓ€гѓ•гѓхЂ’Єѓѓгѓ”гѓи‹Ґ‚’зЇЏеёҐЃпЅѓЃхЂ€ѓ–гѓи‹Ґѓ€г‚’иЊµЊгЃ„гЂЃ
.I /dev/initrd
г‚’йЂљгЃ—гЃ¦ CD-ROM гЃ‹г‚‰г‚€г‚ЉзґЉСЃЃЌгЃЄ RAM гѓ‡г‚пЅѓ‚йґ»‚хЂ•¦‚’иЋЋжЎЃ‹•гЃ™г‚‹гЃ“гЃхЂ‹”‚‚гЃСЃЃЌг‚‹гЂ‚
.\"
.\"
.\"
.SH гѓ•г‚пјњ‚г‚ѓѓ«
.I /dev/initrd
.br
.I /dev/ram0
.br
.I /linuxrc
.br
.I /initrd
.\"
.\"
.\"
.SH зѕ€хЂ‹—„Џ
.IP 1. 3
зж†њњхЂ‹”ЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃСЃЃхЂ•¦ЂЃ
.I /dev/ram0
гЃЊ
.I /
гЃ‹г‚‰
.I /initrd
гЃхЂЏІР©е‹•гЃ•г‚ЊгЃџйљ›гЃхЂЏ®ЂЃи…±зіё‹•ж™‚гЃхЂЏ®ѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃхЂ€Ѓ„гЃџгѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃхЂ•¦ЂЃ
гЃќгЃхЂ”ЉѕЊг‚‚и†“™и†“љзљ„гЃхЂЏ®‚в‰Є‚хЂ•¦‚зҐ‰‚еЉ«х€•«ѓзґ”ЃСЃЃ‚г‚‹гЂ‚гЃ—гЃ‹гЃ—гЂЃ
.I /proc/mounts
гЃхЂ”€‚хЂ‹”ѓжЅџѓ€гѓхЂЋђЃхЂ•©›иґ‹–йЃ•Ѓ•г‚ЊгЃхЂЋђЃ„гЂ‚
.IP 2.
зж†њњхЂ‹”ЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃСЃЃхЂ•¦ЂЃгѓ‡г‚пЅѓѓхЂ‘Њ‚хЂ•¦ѓ€гѓЄ
.I /initrd
гЃЊзµ–ењхЂ‹”Ѓ—гЃхЂЋђЃ„е зї«ђ€гЂЃ
.I /dev/ram0
г‚’зЇЏ•г‚‰гЃ‹гЃхЂ”€ѓ—гѓхЂ’Є‚зҐ‰‚йґ»ЃЊе€хЂЊ¶”хЂ‹”Ѓ—гЃхЂ€Ѓ„гЃџг‚ЉгЂЃзЇЏ•г‚‰гЃ‹гЃхЂ”€ѓ•г‚пјњ‚г‚ѓѓхЂЏ®‚жїЂ‚йґ»ѓ†гѓ гЃЊ
.I /dev/ram0
з­ќЉгЃхЂЏ®ѓћг‚хЂ€ѓжЅџѓ€гЃ•г‚ЊгЃхЂ€Ѓ„г‚‹гЃхЂ‹”ЂЃ
.I /dev/ram0
гЃхЂ•Ё®Ње…хЂ‹”ЃхЂЏ®ЃхЂ•¦‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЂЊгЃ•г‚ЊгЃхЂЋђЃ„гЂЌгЂ‚
.I /dev/ram0
гЃЊгЂЃзµЋЊе…хЂ‹”ЃхЂЏ®‚в‰ЄѓжЅџѓћг‚хЂ€ѓжЅџѓ€гЂЊгЃ•г‚ЊгЃхЂЋђЃ‘г‚ЊгЃйЃ•ЂЌгЂЃ
.I /dev/ram0
гЃхЂ•¦ѓпјњѓв‰ЄѓхЂЋ‘ёЉгЃхЂЏ±®‹гЃпЅѓЃхЂ€Ѓ—гЃйљњЃ†гЃхЂ•¦ЃљгЃСЃЃ‚г‚‹гЂ‚
.IP 3.
.I /dev/initrd
гЃхЂ”Љ€хЂЊ¶”хЂ‹™Ђ…гЃхЂ•¦ЂЃз­ќЉиЌђгЃхЂ”‹зµµж„й‹‹‹й …гЃС†е”‡гЃйґ»Ѓџе‹•зЇЏњгЃхЂЏЇѕќзµ–гЃ—гЃхЂЋђЃ„г‚€гЃ†гЃхЂЏ®Ѓ™гЃйґ»ЃЌгЃСЃЃ‚г‚‹гЂ‚
гЃ“г‚Њг‚‰гЃхЂ”Љ‹•зЇЏњгЃЇ Linux г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂ”Љ°†жќгѓЈЃхЂ”€ѓђгѓи‹Ґ‚еђѕѓСЃѓжЅџЃСЃЃхЂ•Ё¤‰ж›зњјЃ•г‚Њг‚‹
гЃ‹г‚‚гЃ—г‚ЊгЃхЂЋђЃ„гЃ‹г‚‰гЃ гЂ‚
.\"
.\"
.\"
.\" .SH и‘—иЂ…
.\" .BR initrd
.\" гѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ”€Ѓџг‚ЃгЃхЂ”€‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®‚жЅџѓи‹Ґѓ‰гЃЇ Werner Almesberger <almesber@lrc.epfl.ch>
.\" гЃЁ Hans Lermen <lermen@elserv.ffm.fgan.de> гЃхЂЏ®‚€гЃпЅѓЃхЂ€››еђѕЃ‹г‚ЊгЃџгЂ‚
.\" .BR initrd
.\" гЃхЂ”€Ѓџг‚ЃгЃхЂ”€‚жЅџѓи‹Ґѓ‰гЃхЂ•¦ЂЃй–‹з™и‚ґЂ…еђ‘гЃ‘гѓђгѓи‹Ґ‚еђѕѓСЃѓжЅџЃ® 1.3.73 гЃ§
.\" гѓпјњ‚г‚ѓѓжЅџЃ® Linux г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂЏІµ„гЃзІ‹ж­гЃйљњ‚ЊгЃџгЂ‚
.SH й–в€«ЂпЅ‰ …з›®
.BR chown (1),
.BR mknod (1),
.BR ram (4),
.BR freeramdisk (8),
.BR rdev (8)

г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®‚зґ”ѓи‹Ґ‚йґ»ѓ‘гѓѓг‚е®ґѓи‹Ґ‚еђѕЃхЂЏ°ђхЂЏ®Ѓйљњ‚Њг‚‹гѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€гѓ•г‚пјњ‚г‚ѓѓ«
.IR initrd.txt "гЂЃ"
LILO гЃхЂ”€ѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€гЂЃLOADLIN гЃхЂ”€ѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€гЂЃSYSLINUX гЃхЂ”€ѓ‰г‚хЂ’ЄѓгѓЈѓпјњѓжЅџѓ€гЂ‚
