.\" From jt@hplb.hpl.hp.com Thu Dec 19 18:31:49 1996
.\" From: Jean Tourrilhes <jt@hplb.hpl.hp.com>
.\" Address: HP Labs, Filton Road, Stoke Gifford, Bristol BS12 6QZ, U.K.
.\" Jean II - HPLB - '96
.\" wavelan.c.4
.\"
.\" Provenance of this page is unclear.  Licensed under the GPL,
.\" after inquiries with Jean Tourrilhes and Bruce Janson
.\" (mtk, July 2006)
.\"
.\" Japanese Version Copyright (c) 1997
.\"         ISHIKAWA Mutsumi, all rights reserved.
.\" Translated Sat Sep 20 14:45:21 JST 1997
.\"         by ISHIKAWA Mutsumi <ishikawa@linux.or.jp>
.\"
.\" Japanese Version Last Modified Tue Feb 10 15:21:08 JST 1998
.\"	by ISHIKAWA Mutsumi <ishikawa@linux.or.jp>
.\"
.\" WORD:	wireless ethernet	гѓхЂ•¦‚г‚ѓ‚в‰ЄѓхЂ‘Њ‚йґ»‚г‚ѓѓи‹Ґ‚жіЈѓЌгѓѓгѓ€
.\"
.TH WAVELAN 4 1996-10-22 "Linux" "Linux Programmer's Manual"
.SH еђЌе‰Ќ
wavelan \- AT&T GIS WaveLAN ISA гѓ‡гѓђг‚г‚ѓ‚йґ»ѓ‰гѓхЂЊІ‚г‚ѓѓђ
.SH ж›еѕЊјЏ
.BI "insmod wavelan_cs.o [io=" B,B.. "] [ irq=" I,I.. "] [name=" N,N.. ]
.SH иЊЇхЂ‘ЏЋ
.I wavelan
гЃхЂ•¦ЂЃNCR / AT&T / Lucent гЃ®
.B WaveLan ISA
гЃЁ  Digital(DEC) гЃ®
.B RoamAbout DS
гЃхЂ‹”Ѓ„гЃ†гѓхЂ•¦‚г‚ѓ‚в‰ЄѓхЂ‘Њ‚йґ»ѓзҐ‰‚г‚ѓѓи‹Ґ‚жіЈѓЌгѓѓгѓ€ (wireless ethernet) г‚в‰ЄѓЂгѓ—г‚еёҐЃхЂ”€Ѓџг‚ЃгЃ®
гѓхЂ’Єѓи‹ҐѓхЂ‘Њѓ™гѓхЂЏ®ѓзҐ‰ѓ‡гѓђг‚г‚ѓ‚йґ»ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃСЃЃ‚г‚‹гЂ‚гЃ“гЃхЂ”€ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃхЂ•¦ѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃхЂ‹”Ѓ—гЃхЂ€‚‚гЂЃгЃйљњЃџгЂЃ
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂЏІµ„гЃзІ‹ж­г‚“гЃ з¶µв‰ЄЃСЃ‚‚е€хЂЊ¶”хЂ‹”ЃСЃЃЌг‚‹гЂ‚гЃйљњЃџгЂЃгЃхЂЊІЃпјњ‚‰гЃхЂ”Љ зї«ђ€гЃСЃ‚‚гЂЃиЊІ‡ж•йЃ•‚хЂЏ®ѓи‹Ґѓ‰
(жњЂзґЉ§ 4 жћљгЃйљњЃ§) г‚’г‚жіЈѓќгѓи‹Ґѓ€гЃ—гЂЃжЋзгЃљзљ„гЃхЂЏ®ѓ‡гѓђг‚г‚ѓ‚йґ»ЃхЂ”ЉђЌе‰Ќг‚’жЊ‡зµЋљгЃ—гЃхЂЋђЃ„й™ђг‚Љ
(гЃ“г‚ЊгЃхЂЏґ–в‰ЄЃ—гЃхЂ€ЃхЂ•¦ЂЃз­ќ‹г‚’иЌЂ‹г‚€)гЂЃз™и‚ґ¦‹гЃ•г‚ЊгЃџгЃќг‚ЊгЃћг‚ЊгЃхЂ”€‚хЂЏ®ѓи‹Ґѓ‰гЃхЂЏ®ЃхЂ•¦ЂЃе€хЂЊ¶”хЂ‹–х€•«ѓзґ”ЃЄ
зЅЁпјњЃхЂ”€‚г‚ѓѓи‹Ґ‚жіЈѓЌгѓѓгѓ€гѓ‡гѓђг‚г‚ѓ‚№(eth0..eth#)гЃЊе‰иљЉ‚Љз¶µ“гЃхЂ€‚‰г‚Њг‚‹гЂ‚гЃ“гЃхЂ”€ѓ‡гѓђг‚г‚ѓ‚еЉ«ђЌгЃЇ
MAC г‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»ЂЃNWIDгЂЃг‚хЂЏ®ѓи‹Ґѓ‰гЃхЂЏ®‚€гЃпЅѓЃхЂ€љ€хЂЊ¶”хЂ‹”Ѓ•г‚Њг‚‹е‘хЂ‹—ж™¦ж•йЃ•ЃхЂ‹”ЃхЂ‹”‚‚гЃ«
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ѓхЂ’Є‚йЃ•ѓ•г‚пјњ‚г‚ѓѓхЂЏ®ЃхЂЏ° жЂЁ‘ЉгЃ•г‚Њг‚‹гЂ‚
.SS з¶Ј•ж•°
гЃ“гЃхЂ”€‚зҐ‰‚хЂ•¦‚жїЂѓСЃѓжЅџЃхЂ”€ѓ‘гѓхЂЊІѓпјњѓи‹Ґ‚еёҐѓи‹ҐЃхЂ•¦ЂЃгѓв‰Є‚еђѕѓгѓЈѓи‹ҐѓхЂЏ®ЃхЂ‹”Ѓ—гЃхЂ€™ж€Ћз”хЂ‹”Ѓ™г‚‹е зї«ђ€
гЃхЂЏґЃхЂЊ¶”хЂ‹”Ѓ•г‚ЊгЂЃ
.BR insmod (8)
гЃхЂ”€‚жЅџѓћгѓжЅџѓ‰гѓзҐ‰ѓхЂЊІ‚г‚ѓѓе–ќј•гЃЌж•йЃ•ЃхЂ‹”Ѓ—гЃхЂ€њ”хЂ‹”Ѓ„г‚‹гЂ‚
г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ЃхЂЏ®ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃЊеђхЂЏ®Ѓйљњ‚ЊгЃхЂ€Ѓ„г‚‹е зї«ђ€гЃхЂ•¦ЂЃ
.I ether=IRQ,IO,NAME
гЃхЂ‹”Ѓ„гЃ†з¶µв€љјЏгЃхЂ”€ѓ‘гѓхЂЊІѓпјњѓи‹Ґ‚еёҐ‚’г‚хЂЏ®ѓи‹ҐѓЌгѓхЂЏ®ѓзҐ‰‚жЅџѓћгѓжЅџѓ‰гѓхЂЊІ‚г‚ѓѓжЅџЃхЂЏ±ж¤њгЃ™гЂ‚
.TP
.B io
wavelan г‚хЂЏ®ѓи‹Ґѓ‰г‚’зЅЋње‡е†ґЃ™г‚‹ж™‚гЃхЂЏ®ЃхЂЊІЃ“гЃхЂ”€ѓ™гѓи‹Ґ‚йґ»‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»‚’г‚жіЈѓи‹ҐѓЃгЃ™г‚‹гЃ‹гЃхЂ‹”Ѓ„гЃ†
гѓхЂЋђ‚йґ»ѓ€г‚’жЊ‡зµЋљгЃ™г‚‹ (г‚хЂЏ®ѓи‹Ґѓ‰гЃЊе€хЂЊ¶”хЂ‹”Ѓ™г‚‹гѓ™гѓи‹Ґ‚йґ»‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»ЃхЂ•¦‚хЂЏ®ѓи‹Ґѓ‰гЃхЂ”€ѓ‡г‚пЅѓѓѓгѓ—
г‚йґ»‚г‚ѓѓѓгѓЃгЃС†в”ѓзµЋљгЃ™г‚‹)гЂ‚г‚‚гЃ— io г‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»ЃЊжЊ‡зµЋљгЃ•г‚ЊгЃхЂЋђЃ‘г‚ЊгЃйЃ•ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃЇ 0x390 гЃЁ
0x3E0 г‚’г‚йґ»‚хЂ’ЄѓпЅѓѓжЅџЃ™г‚‹(гЃ“гЃхЂ”€‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»ЃхЂ•§»–гЃхЂ”€ѓЏгѓи‹Ґѓ‰гЃхЂ‹™Ўќи…¦ЃгЃ™г‚‹гЃ“гЃхЂ‹”‚‚иЂѓгЃ€г‚‰г‚Њг‚‹)гЂ‚
.TP
.B irq
гЃќг‚ЊгЃћг‚ЊгЃ® wavelan г‚хЂЏ®ѓи‹Ґѓ‰гЃЊе€хЂЊ¶”хЂ‹”Ѓ™г‚‹ irq гЃхЂ”€ѓхЂЋђ‚йґ»ѓ€г‚’г‚зҐ‰ѓѓгѓ€гЃ™г‚‹ (гЃ“гЃхЂ”ЉЂг‚ѓЃЇ
зµЁ†жќгѓ§љ„гЃхЂЋ’€хЂЊ¶”хЂ‹”ЃхЂ”€Ѓџг‚ЃгЃхЂЏ®ѓ‘гѓи‹ҐѓћгѓЌгѓжЅџѓ€гѓзҐ‰‚йґ»ѓ€гѓхЂ‘Њѓи‹Ґ‚еђѕЃхЂЏЇїќзµ–гЃ•г‚Њг‚‹)гЂ‚
.TP
.B name
гЃќг‚ЊгЃћг‚ЊгЃ® wavelan г‚хЂЏ®ѓи‹Ґѓ‰гѓ‡гѓђг‚г‚ѓ‚йґ»Ѓ«
.RB ( ifconfig (8)
гЃЊе€хЂЊ¶”хЂ‹”Ѓ™г‚‹)еђЌе‰ЌгЃхЂ”€ѓхЂЋђ‚йґ»ѓ€г‚’г‚зҐ‰ѓѓгѓ€гЃ™г‚‹гЂ‚
.SS "гѓхЂ•¦‚г‚ѓ‚в‰ЄѓхЂ‘Њ‚еЏ·‹в‰¦е®Ќ (Wireless Extentions)"
гѓхЂ•¦‚г‚ѓ‚в‰ЄѓхЂ‘Њ‚еЏ·‹в‰¦е®ЌгЃхЂ”‹“ЌзЇЏњгЃхЂЏ®ЃЇ
.BR iwconfig (8)
г‚’зЇЏеёҐЃ†гЂ‚
.SS NWID (or гѓ‰гѓпјњ‚г‚ѓѓі)
гѓЌгѓѓгѓ€гѓхЂ•¦ѓи‹Ґ‚Ї IDг‚’
.RI [ 0
гЃ‹г‚‰
.IR FFFF ]
гЃхЂЏів”ѓзµЋљгЃ™г‚‹гЃ‹гЂЃ
.RI [ off ]
гЃќгЃхЂ”Љ€хЂЊ¶”хЂ‹”‚’з„в‰¦Љйґ»ЃхЂЏ®Ѓ™г‚‹гЂ‚
NWID гЃхЂ•¦‚хЂЏ®ѓи‹Ґѓ‰гЃхЂ”€ѓ‘гѓи‹ҐѓћгѓЌгѓжЅџѓ€гѓзҐ‰‚йґ»ѓ€гѓхЂ‘Њѓи‹Ґ‚еђѕ‚хЂ‹”ѓхЂЋђ‚ў (Permanent Strage Area) гЃ«
ж дё»ґЌгЃ•г‚Њг‚‹гЃхЂ”€ЃСЃЂЃNWID гЃхЂ•¦ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃЊе‘и‹ҐЃе–ќ‡е†ґЃ•г‚Њг‚‹гЃџгЃжЅџЃхЂЏ°€хЂЊ¶”хЂ‹”ЃСЃЃЌг‚‹гЂ‚
.SS е‘хЂ‹—ж™¦ж•йЃ•ЃхЂ‹”ѓЃгѓпЅѓѓЌгѓ«
2.4GHz 2.00 гѓЏгѓи‹Ґѓ‰г‚хЂ€‚СЃ‚в‰ЄЃСЃЃхЂ•¦ЂЃ10 гЃхЂ”Љ®љи‡‚хЂЊµё€гЃеёҐЃхЂ”€ѓЃгѓпЅѓѓЌгѓ«
.RI ( 2.412
.I 2.422, 2.425, 2.4305, 2.432, 2.442, 2.452, 2.460, 2.462
.IR 2.484 )
гЃхЂ”€Ѓ†гЃпјњЃхЂ”‰ёЂгЃг‚ѓ‚’жЊ‡зµЋљгЃ™г‚‹гЃ‹гЂЃгЃќгЃхЂ”ЉЂг‚ѓ‚’з›иґ‹пЅҐжЊ‡зµЋљгЃ™г‚‹гЃ“гЃхЂ‹”ЃхЂЏ®‚€гЃпЅѓЃхЂ€љ‘хЂ‹—ж™¦ж•йЃ•‚’иЌђхЂ’¬®љ
гЃ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
е‘хЂ‹—ж™¦ж•йЃ•ЃхЂ•Є›зї«ѕЊгЃхЂЏ°¤‰ж›зњјЃ•г‚ЊгЂЃгЃйљњЃџгЂЃгЃќгЃхЂ”Љ¤‰ж›зњјЃхЂ•©Ѓ’з®™…зљ„гЃСЃЃ‚г‚‹гЂ‚
гЃхЂЊІЃхЂ”Љ‘хЂ‹—ж™¦ж•йЃ•ЃЊе€хЂЊ¶”хЂ‹”ЃСЃЃЌг‚‹гЃ‹гЃхЂ‹”Ѓ„гЃ†гЃ“гЃхЂ‹”ЃхЂ•¦ЂЃ(гЃќгЃхЂ”Љ›зґ”Ѓ®) зѕ€•з·‡‹гЃхЂЏЇѕќзµ–гЃ™г‚‹вЂ¦
.SS и…џжІїЁ€г‚йґ»ѓ‘г‚¤ (Statics spy)
(8 гЃг‚ѓЃйљњЃСЃЃ®) MAC г‚в‰Єѓ‰гѓхЂ‘Њ‚йґ»ЃхЂ”€ѓхЂЋђ‚йґ»ѓ€г‚’гѓ‰гѓхЂЊІ‚г‚ѓѓђгЃхЂЏів”ѓзµЋљгЃ—гЃхЂ€ЂЃ
гЃќг‚ЊгЃћг‚ЊгЃхЂ”€ѓхЂЋђѓжЅџ‚хЂ•¦ЃхЂ”Љ“ЃиЋ–хЂЋђ‚’з·‡—г‚‹
.RB ( iwspy (8)
г‚’еЏ‚з…§)гЂ‚
.SS /proc/net/wireless
.I status
гЃхЂ•¦ѓв‰Єѓ‡гѓ гЃ‹г‚‰е жЂЁ‘ЉгЃ•г‚ЊгЃџг‚йґ»ѓ†гѓи‹Ґ‚еёҐ‚йґ»ЃСЃЃ‚г‚‹гЂ‚
.I link quality
гЃхЂ•¬ЂљзЇ†пјћиіўгЃ®(з›иґ‹пЅҐж‹в‰§•пЅѓ‚йґ»ѓљг‚хЂ•¦ѓ€гѓхЂЊІѓ йЂљзЇ†в‰§–еЉ«јЏгЃхЂЏ®ЃЉгЃ‘г‚‹)зґЉ‰иЊЇеёҐЃхЂ”Љ“ЃиЋ–хЂЋђ‚’е жЂЁ‘ЉгЃ™г‚‹
[жњЂзґЉ§ = 16]гЂ‚
.I Level
гЃЁ
.I Noise
гЃхЂ•§ж‹­еећ©ѓхЂ‘Њѓ™гѓхЂЏ®ЃхЂ‹”ѓЋг‚г‚ѓ‚е†ґЃхЂ”€ѓхЂ‘Њѓ™гѓхЂЏ®‚’еЏ‚з…СЃЃ™г‚‹ [жњЂзґЉ§ = 64]гЂ‚
.I жљ—еећёЊ–гЃ•г‚ЊгЃхЂ€Ѓ„гЃхЂ€љ»ѓзЅЌ„гЃ•г‚ЊгЃџгѓ‘г‚е®ґѓѓгѓ€(crypt discarded packet)
гЃЁ
.I гЃќг‚ЊзЇЃгѓҐ¤–гЃхЂ”Љ»ѓзЅЌ„гЃ•г‚ЊгЃџгѓ‘г‚е®ґѓѓгѓ€(misc discarded packet)
гЃхЂ”€‚хЂЏ®‚хЂ€ѓжЅџ‚еёҐѓи‹ҐЃхЂ•Ё®џиЊ–…гЃ•г‚ЊгЃхЂ€Ѓ„гЃхЂЋђЃ„гЂ‚
.SS "гѓ‰гѓхЂЊІ‚г‚ѓѓђе›е єњ‰гЃ®IOCTL (Private Ioctl)"
.BR iwpriv (8)
г‚’гѓ‰гѓхЂЊІ‚г‚ѓѓђе›е єњ‰гЃ® ioctl гЃхЂ”‹“ЌзЇЏњгЃхЂ”€Ѓџг‚ЃгЃхЂЏ°€хЂЊ¶”хЂ‹”ЃСЃЃЌг‚‹гЂ‚
.SS е“ЃиЋ–хЂЋђЃхЂ‹”ѓхЂ‘Њѓ™гѓхЂЏ®ЃхЂ”Ћ–дёЉЂ¤ (Quality and Level threshold)
гѓв‰Єѓ‡гѓ гЃС‚ж€Ћг‚Џг‚Њг‚‹е“ЃиЋ–хЂЋђЃхЂ‹”ѓхЂ‘Њѓ™гѓхЂЏ®ЃхЂ”Ћ–дёЉЂ¤ (гЃќгЃхЂ”€ѓхЂ‘Њѓ™гѓхЂЏ®‚’з­ќ‹е›ћгЃпЅѓЃџгѓ‘г‚е®ґѓѓгѓ€гЃЇ
з иґ‹Ј„гЃ•г‚Њг‚‹) г‚’зµЋљи‡‚хЂЊІЃ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
.SS гѓ’г‚йґ»ѓ€г‚йЃ•ѓхЂЊІѓ  (Histogram)
гЃ“гЃхЂ”‹©џиѓзґ”ЃхЂЏ®‚€г‚ЉгЂЃ
г‚жїЂ‚йЃ•ѓЉгѓхЂЏ®ѓхЂ‘Њѓ™гѓхЂЏ°Ње’І–“гЃхЂ”‹•йЃ•ЃхЂ”Ќв”ѓзµЋљгЃхЂ‹”ЂЃиЌђхЂ’¬®љгЃ—гЃџгЃќг‚ЊгЃћг‚ЊгЃхЂ”ЉЊе’І–“гЃСЃЃ®
еЏ—зЇ†пјњѓ‘г‚е®ґѓѓгѓ€ж•йЃ•‚’г‚хЂЏ®‚хЂ€ѓжЅџѓ€гЃ™г‚‹гЃ“гЃхЂ‹”ЃЊгЃСЃЃЌг‚‹гЂ‚
гЃ“гЃхЂ”Љ€†зµЅѓгЃхЂ•¦‚жїЂ‚йЃ•ѓЉгѓхЂЏ®ѓхЂ‘Њѓ™гѓхЂЏ®ЃхЂ”‹њЂзЂ•еЂг‚†Ё™зѕЈ–еЃйЋґхЂ”€ЃхЂ”ЌЁ€и†Љ—гЃхЂЏ°й†њи…ґ‹гЃг‚ѓЃ г‚ЌгЃ†гЂ‚
.SS з‰еЉ«®љгЃхЂ”€ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃСЃЃхЂ”‹зµµж„Џ
гЃ“гЃхЂ”€ѓ‰гѓхЂЊІ‚г‚ѓѓђгЃхЂ•¦Ѓ„гЃЏгЃг‚ѓЃ‹гЃ®
.B NCR/AT&T/Lucent гЃСЃЃхЂ•¦ЃхЂЋђЃ„
Wavelan г‚хЂЏ®ѓи‹Ґѓ‰гЃхЂ”‹¤ње‡е†ґЃхЂЏ°гЃ‘ж•—гЃ™г‚‹гЃ г‚ЌгЃ†гЂ‚
гЃ“г‚ЊгЃЊгЃ‚гЃхЂЋђЃџгЃхЂ”‹ЊЃгЃпЅѓЃхЂ€Ѓ„г‚‹г‚хЂЏ®ѓи‹Ґѓ‰гЃС†е„ЂгЃ“гЃпЅѓЃџе зї«ђ€
гЂЃгЃќгЃхЂ”€‚хЂЏ®ѓи‹Ґѓ‰гЃхЂ”‹¤ње‡йЄ‡хЂ€њђ†г‚’гЃхЂЊІЃхЂ”€‚€гЃ†гЃхЂЏ°Љ гЃ€г‚ЊгЃйЃ•Ѓ„гЃ„гЃ‹гЃЁ
гЃ„гЃ†гЃ“гЃхЂ‹”ЃхЂЏ®Ѓг‚ѓЃ„гЃхЂ€‚зґ”ѓи‹Ґ‚йґ»‚жЅџѓи‹Ґѓ‰г‚’и…†и‚ґЄЌгЃ™г‚‹з¶Ѕ…иЌЂЃгЃЊгЃ‚г‚‹гЂ‚
.PP
гЃ“гЃ“гЃйљњЃСЃЃС†е”‡гЃйґ»ЃхЂ€ЃЌгЃџзЅџиѓзґ”ЃхЂ”€Ѓ†гЃпјњЃхЂ”€Ѓ„гЃЏгЃг‚ѓЃ‹гЃхЂ•¦ЂЃйЃеѕЎЉћех€•«ѓзґ”ЃСЃЃ‚г‚‹гЂ‚
гѓ‰гѓхЂЊІ‚г‚ѓѓђгЃхЂ”Љ…€й хЂ’°ѓхЂ‹–€†гЃхЂ”€ѓ•гѓхЂЊІ‚йЃ•‚’зґЉ‰ж›зњјЃ—гЃхЂ€‚жЅџѓжЅџѓ‘г‚г‚ѓѓхЂЏ®Ѓ—гЃхЂЋђЃЉгЃ™гЃ“гЃхЂ‹”ЃхЂЏ®‚€гЃпЅѓЃхЂ€ЂЃ
гЃќгЃхЂ”‹©џиѓзґ”‚’з„в‰¦Љйґ»ЃхЂЏ®Ѓ™г‚‹гЃ“гЃхЂ‹”‚‚ех€•«ѓзґ”ЃСЃЃ‚г‚‹гЂ‚
.\" .SH и‘—иЂ…
.\" Bruce Janson \(em bruce@cs.usyd.edu.au
.\" .br
.\" Jean Tourrilhes \(em jt@hplb.hpl.hp.com
.\" .br
.\" (гЃЉг‚€гЃжЅџЂЃгЃќгЃхЂ”‰»–гЃхЂ”‰жџ»йЃ”; иЌ…ж‹¬е®ЊгЃхЂ•¦‚зґ”ѓи‹Ґ‚йґ»‚жЅџѓи‹Ґѓ‰г‚’еЏ‚з…СЃЃхЂ”€Ѓ“гЃЁ)
.SH й–в€«ЂпЅ‰ …з›®
.BR wavelan_cs (4),
.BR ifconfig (8),
.BR insmod (8),
.BR iwconfig (8),
.BR iwpriv (8),
.BR iwspy (8)
